// Babies: hand-drawn pixel grids, 8 to 16 pixels tall, facing right. The style recolours
// them; the outline is added when they are baked. `rows` is the first walk frame;
// `walk` replaces its last rows for the second frame.
//   B body   b shade   d darkest   W pale (belly, muzzle)   A horn, beak, claw
//   E eye    G glint   N nose      I iris   e inner ear   S skin   L line
export const BABIES = {
  wolf: {
    rows: [
      "...........d..d....",
      "..........dBedBe...",
      "..........BBBBBBB..",
      ".bb......BBBBBBBB..",
      "bBb......BBBBEGBB..",
      "bBb...bbbBBBBEEBWWN",
      ".bBBBBBBBBBBBBWWWW.",
      "..BBBBBBBBBBBBWWW..",
      "..BBBBBBBBBBBWW....",
      "..BBWWWWWWBBBB.....",
      "..BB.b....BB.b.....",
      "..dd.d....dd.d.....",
    ],
    walk: [
      "...BBb...b.BB......",
      "...ddd...d.dd......",
    ],
  },
  boar: { // a striped piglet, as wild boar piglets are
    rows: [
      "...........bb.....",
      ".....BBBBBBBbB....",
      "...BBWWWWWWBBBB...",
      "..BBBBBBBBBBBBGB..",
      ".bBWWWWWWWWBBBEBBBN",
      "..BBBBBBBBBBBBBBBBN",
      "..BWWWWWWWWBBBBBb..",
      "...BBBBBBBBBBBB....",
      "...BB.b....BB.b....",
      "...dd.d....dd.d....",
    ],
    walk: [
      "....BBb...b.BB.....",
      "....ddd...d.dd.....",
    ],
  },
  owl: { // a fluffy owlet, facing us
    rows: [
      ".b......b.",
      ".bBBBBBBb.",
      "BBWWBBWWBB",
      "BWEGWWEGWB",
      "BWEEAAEEWB",
      "BBWWWAWWBB",
      "bBWWWWWWBb",
      "bBWbWWbWBb",
      "bBWWWWWWBb",
      ".bBWbWWBb.",
      "..BBBBBB..",
      "..A....A..",
    ],
    walk: [
      "...A..A...",
    ],
  },  fox: { // a kit: big ears, white chest, dark socks, a white-tipped brush
    rows: [
      "..........d...d...",
      ".........dBe.dBe..",
      ".........BBBBBBB..",
      "WB......BBBBBGBB..",
      "WBB.....BBBBBEBWWN",
      ".BBB.BBBBBBBBBWWW.",
      "..BBBBBBBBBBBWWW..",
      "..BBBBBBBBBBBW....",
      "..BBWWWWWWBBB.....",
      "..dd.d....dd.d....",
      "..dd.d....dd.d....",
    ],
    walk: [
      "...dd.d..d.dd.....",
      "...dd.d..d.dd.....",
    ],
  },
  badger: { // a cub: grey, black legs, a white face with a black stripe through the eye
    rows: [
      "..........dd.......",
      "...BBBBBBBWWWW.....",
      ".BBBBBBBBWdGdWW....",
      "BBBBBBBBBWdEddddN..",
      "BBBBBBBBBBWWWWW....",
      ".BBBBBBBBBBBBB.....",
      ".dd.d.....dd.d.....",
      ".dd.d.....dd.d.....",
    ],
    walk: [
      "..dd.d...d.dd......",
      "..dd.d...d.dd......",
    ],
  },
  stag: { // a spotted fawn on long legs
    rows: [
      "...........bb.b...",
      "..........BeBBe...",
      "..........BBBBB...",
      "..........BBBGBB..",
      "..........BBBEBBBN",
      "..W......BBBB.WW..",
      ".WBBBBBBBBBBB.....",
      ".BWBBWBBWBBBB.....",
      "..BBBBBBBBBBW.....",
      "..BBWWWWWWBB......",
      "..B.b.....B.b.....",
      "..B.b.....B.b.....",
      "..B.b.....B.b.....",
      "..N.N.....N.N.....",
    ],
    walk: [
      "...B.b...b.B......",
      "...B.b...b.B......",
      "...N.N...N.N......",
    ],
  },
  hare: { // a leveret: long ears up, white scut
    rows: [
      "........dd.......",
      "........Be.d.....",
      "........Be.Bd....",
      "........BeBBe....",
      ".......BBBBB.....",
      ".......BBBGBB....",
      "..W...BBBBEBBN...",
      ".WWBBBBBBBBWW....",
      "..BBBBBBBBBW.....",
      ".BBBBBBBBBW......",
      ".BBBWWWWBB.......",
      ".dddd...dd.......",
    ],
    walk: [
      "dddd....d.d......",
    ],
  },
  bear: { // a round cub
    rows: [
      ".........bb..bb..",
      ".........BeBBBe..",
      "........BBBBBBBB.",
      "..BBBB..BBBBBGBB.",
      ".BBBBBBBBBBBBEBWW",
      "BBBBBBBBBBBBBBWWN",
      "BBBBBBBBBBBBBBB..",
      "BBBBBBBBBBBBBB...",
      ".BBBbBBBBBBbBB...",
      ".BB.bb...BB.bb...",
      ".dd.dd...dd.dd...",
    ],
    walk: [
      "..BBbb..bBB.b....",
      "..dddd..ddd.d....",
    ],
  },
  squirrel: { // a kit with its plume up
    rows: [
      ".bb.............",
      "bBBb......d..d..",
      "bBBBb....dB.dB..",
      ".bBBb....BBBBB..",
      "..bBB...BBBBGB..",
      "..bBB...BBBBEBBN",
      "...BB..BBBBBWW..",
      "...BBBBBBBBWW...",
      "....BBBBBBBW....",
      "....BBWWWBBB....",
      "....dd...dd.....",
    ],
    walk: [
      ".....dd.d.d.....",
    ],
  },
  otter: { // a pup: long, low, pale-muzzled
    rows: [
      "............BBB....",
      "..........BBBBBB...",
      ".......BBBBBBBGBB..",
      "....BBBBBBBBBBEBWWN",
      "BBBBBBBBBBBBBBWWWW.",
      ".BBBBBBBBBBBBWWW...",
      "..BBWWWWWWBBBB.....",
      "...dd.....dd.......",
    ],
    walk: [
      "....dd...dd........",
    ],
  },
  lynx: { // a kitten with ear tufts and spots
    rows: [
      "..........d...d...",
      "..........d...d...",
      ".........BeB.Be...",
      ".........BBBBBBB..",
      ".........BBBBGBBB.",
      ".d.......BBBBEBWWN",
      ".dB......BBBBBWWW.",
      "..BBBBBBBBBBBWW...",
      "..BdBBdBBdBBBB....",
      "..BBBBBBBBBBBW....",
      "..BBWWWWWWBBB.....",
      "..BB.b....BB.b....",
      "..dd.d....dd.d....",
    ],
    walk: [
      "...BB.b..bBB......",
      "...dd.d..ddd......",
    ],
  },
  elk: { // a long-legged calf with a long nose
    rows: [
      "..........b..b....",
      "..........BBBB....",
      "..........BBBGB...",
      "..........BBBEBBB.",
      ".........BBBBBBBBN",
      ".b......BBBB..BB..",
      ".BBBBBBBBBBB......",
      ".BBBBBBBBBBB......",
      "..BBBBBBBBBB......",
      "..BBbbbbbbBB......",
      "..B.b.....B.b.....",
      "..B.b.....B.b.....",
      "..B.b.....B.b.....",
      "..N.N.....N.N.....",
    ],
    walk: [
      "...B.b...b.B......",
      "...B.b...b.B......",
      "...N.N...N.N......",
    ],
  },
  beaver: { // a kit: round, with orange teeth and a flat tail
    rows: [
      "..........bb......",
      "........BBBBBB....",
      "......BBBBBBGBB...",
      "....BBBBBBBBEBBB..",
      "...BBBBBBBBBBBBBN.",
      "...BBBBBBBBBBBAA..",
      "...BBBBBBBBBBB.A..",
      "dddBBBBBBBBBB.....",
      "ddd.BBB...BB......",
      "....dd....dd......",
    ],
    walk: [
      ".....dd..dd.......",
    ],
  },
  stoat: { // a kit: long and thin, black-tipped tail
    rows: [
      "...........BB.....",
      "..........BBBBB...",
      ".........BBBGBB...",
      "dd.BBBBBBBBBEBBN..",
      "dBBBBBBBBBBBWWW...",
      "...BBBBBBBBWWW....",
      "...BWWWWWWBB......",
      "...dd....dd.......",
    ],
    walk: [
      "....dd..dd........",
    ],
  },
  hedgehog: { // a hoglet: a ball of spines and a pale pointed face
    rows: [
      "....bdbdb......",
      "..bdbdbdbdb....",
      ".bdbdbdbdbdbe..",
      "dbdbdbdbdbWWW..",
      "bdbdbdbdbWGWW..",
      "dbdbdbdbWWEWWWN",
      ".WWWWWWWWWWWW..",
      "..dd.....dd....",
    ],
    walk: [
      "...dd...dd.....",
    ],
  },
  toad: { // a toadlet with a golden eye and a wide mouth
    rows: [
      "........BBB...",
      "......BBIEB...",
      "..BBBBBBBBBB..",
      ".BBdBBBBdBBBB.",
      "BBBBBBdBBBBBBB",
      "BBdBBBBBBBLLLL",
      "BBBBWWWWWWWWB.",
      ".BBBBWWWWWBB..",
      "BBBB....BB....",
    ],
    walk: [
      ".BBBB...BB....",
    ],
  },
  raven: { // a fledgling with a big dark beak
    rows: [
      ".......BBB.....",
      "......BBBBB....",
      "......BBGBBNN..",
      "......BBEBNNNN.",
      "....BBBBBBNN...",
      "..bbBBBBBBB....",
      "bbbBBbBBBBB....",
      "bb..bBBBBBB....",
      "......BBBB.....",
      "......N.N......",
      "......NNNN.....",
    ],
    walk: [
      "......N..N.....",
      ".....NN.NN.....",
    ],
  },
  bat: { // a pup on the wing, facing us; the second frame is the downstroke
    rows: [
      "...d.....d...",
      "...Bd...dB...",
      "...BBBBBBB...",
      "b..BGBBBGB..b",
      "bb.BEBBBEB.bb",
      "bbbbBBNBBbbbb",
      "bbbbBBBBBbbbb",
      ".bb.BBBBB.bb.",
      "b...BBBBB...b",
      ".....d.d.....",
    ],
    walk: [
      "...BGBBBGB...",
      "...BEBBBEB...",
      ".bbbBBNBBbbb.",
      "bbbbBBBBBbbbb",
      "bbbbBBBBBbbbb",
      "bb..BBBBB..bb",
      "b....d.d....b",
    ],
  },
  mole: { // a velvet pup with a pink snout and pink spades
    rows: [
      "....BBBBB......",
      "..BBBBBBBBB....",
      ".BBBBBBBBBBB...",
      "BBBBBBBBBBEBSS.",
      "BBBBBBBBBBBBSSS",
      "BBBBBBBBBBBB...",
      ".BBBBBBBSSBB...",
      "S.SS...SSSS....",
    ],
    walk: [
      ".SS.....SSSS...",
    ],
  },
  beetle: { // a little stag beetle with little jaws
    rows: [
      "..........A.A.",
      "...bbbbb..AA..",
      ".bBBBBBBbBBA..",
      "bBWBBBBBbBGB..",
      "bBBBBBBBbBB...",
      ".bbbbbbbbb....",
      ".d.d.d.d.d....",
    ],
    walk: [
      "d.d.d.d.d.....",
    ],
  },
  snail: {
    rows: [
      "...bbb....d.d",
      "..bBBBb...S.S",
      ".bBbbBBb..S.S",
      ".bBbBbBb.SSS.",
      ".bBBbbBbSSSS.",
      "..bBBBBSSSS..",
      "SSSSSSSSSS...",
    ],
    walk: [
      ".SSSSSSSSSS..",
    ],
  },
  ram: { // a woolly lamb with little horn buds
    rows: [
      "..........AA.....",
      ".........AbbbA...",
      "...W.W...bbGbb...",
      ".WWWWWWW.bbEbbbN.",
      "WWWWWWWWWWbbbbb..",
      "WWWWWWWWWWWbb....",
      "WWWWWWWWWWW......",
      ".WWWWWWWWWW......",
      "..b.b....b.b.....",
      "..b.b....b.b.....",
      "..N.N....N.N.....",
    ],
    walk: [
      "...b.b..b.b......",
      "...N.N..N.N......",
    ],
  },
  woodlouse: {
    rows: [
      "...........d.",
      "...bbbbbbb.d.",
      ".bBdBdBdBBb..",
      "bBBdBdBdBBGb.",
      "bdddddddddd..",
      ".d.d.d.d.d...",
    ],
    walk: [
      "d.d.d.d.d....",
    ],
  },
  snake: { // a snakelet with its head raised
    rows: [
      "...........BBB...",
      "..........BBGBN..",
      "..........BBBB.SS",
      "..........BB.....",
      "..BBdBBdBBBB.....",
      ".BWWWWWWWWWB.....",
      "BB...............",
    ],
    walk: [
      ".BWWWWWWWWWB.....",
      "..B..............",
    ],
  },
  moth: { // a fuzzy moth, facing us, wings up then down
    rows: [
      "....b...b....",
      ".....b.b.....",
      "BBB..WWW..BBB",
      "BWBB.WEW.BBWB",
      "BBBBBWWWBBBBB",
      ".bbbbWWWbbbb.",
      "..bbb.W.bbb..",
    ],
    walk: [
      ".BBBBWEWBBBB.",
      "BWBBBWWWBBBWB",
      "BBBbbWWWbbBBB",
      ".bb...W...bb.",
    ],
  },
  marten: { // a kit: long body, cream bib, bushy tail
    rows: [
      "...........d.d...",
      "..........BBBBB..",
      "..........BBGBB..",
      "bb.......BBBEBBN.",
      "bBBBBBBBBBBWWW...",
      ".BBBBBBBBBBWW....",
      "..BBBBBBBBBB.....",
      "..dd.d...dd.d....",
    ],
    walk: [
      "...dd.d.d.dd.....",
    ],
  },
  salamander: { // black, yellow-spotted, low
    rows: [
      "...........BBB..",
      "....BWBBWBBBGBB.",
      "BBBBBBBBBBWBBEBB",
      ".......BBBBBBBB.",
      ".....B.B...B.B..",
    ],
    walk: [
      "......BB..BB....",
    ],
  },
  glowworm: { // a larva, its tail already glowing
    rows: [
      "....bbbbbbbb...",
      "..IIBbBbBbBbBG.",
      ".IIIbBbBbBbBbBB",
      "..IIdbdbdbdbdb.",
      "....d.d.d.d.d..",
    ],
    walk: [
      "...d.d.d.d.d...",
    ],
  },
  spider: {
    rows: [
      "...bbb.........",
      ".bBBBBb..d..d..",
      "bBBWBBBbBBBd...",
      "bBWWWBBbBGGBd..",
      "bBBWBBBdBBBB.d.",
      ".bBBBBd.d..d..d",
      "..d.d..d..d..d.",
    ],
    walk: [
      ".d.d..d..d..d..",
    ],
  },
  dormouse: { // round, golden, huge-eyed, with a fluffy tail
    rows: [
      ".BB............",
      "BBBB.....e.e...",
      "BBBB....BBBBB..",
      ".BBB...BBEGBB..",
      "..BBB.BBBEEBBN.",
      "...BBBBBBBWW...",
      "....BBBBBWW....",
      "....BBWWBB.....",
      "....dd..dd.....",
    ],
    walk: [
      ".....dd.d.d....",
    ],
  },
};
