// Party objects (Ed, 2026-10-04: "a library of party objects that become scattered around party areas ... Cups, cans,
// party hats, tables and chairs, glowsticks, candles, other light sources?"): what a partified area is strewn with, so
// party ground reads at a glance from dormant forest, even in the dark and from the treetops. Readability first: many
// carry a small glow, a neon or warm light, while the dormant forest stays dark. No brands or readable text.
// Small, cheap sprites, reused heavily (many per area, unlike the once-per-map scenes). Each piece has a size class:
//   litter     cups, cans, bottles, party hats, streamers, balloons, confetti and glitter decals, crushed glowsticks;
//   small      the light sources: glowsticks, tea lights, candles, jam-jar lanterns, paper lanterns, fairy lights, a tiki
//              torch, a fire pit, an LED cube, a mirror ball, UV paint on a rock and a stump;
//   furniture  folding tables, chairs, deck chairs, a picnic blanket, a cool box, hay-bale seating, a hammock, a gazebo,
//              a little tent;
//   set        rarer set dressing: a small DJ booth, inflatables, a crate bar, bunting, neon outline signs, flags.
// Glowing pieces light in one neon (the MAGIC materials) or warm candlelight (GLOW, RUNE): `light` says which. A neon
// piece is drawn once and baked in any neon (partyColours(style, neon)): the game picks the colour per placement.
// Built in 3D (model3d.js) at the witch's scale, like the country pieces.
import { M, hsv2rgb } from "./core.js";
import { Model, v3, masks } from "./model3d.js";
import { NEON } from "./sigils.js";
import { ctHash, ctCell, ctWorn, ctPlank, ctBar, ctGlow, ctCyl, ctTufts, mark, place, pieceSprite } from "./country.js";
import { propVariant } from "./props/generator.js";
import { PARTY_PROP_GENOMES } from "./props/genomes.js";

// ---------------- building blocks ----------------
const pCup = (m, c, g, mat = M.ACCENT, tip = 0) => { const n = mark(m); m.seg([0, 0, 0], [0, .13, 0], .045, .06, mat, { group: g, paint: p => p[1] > .11 ? M.BELLY : undefined }); m.seg([0, .02, 0], [0, .15, 0], .035, .05, M.NOSE, { group: g, cut: true }); place(m, n, { roll: tip, at: c }); };
const pCan = (m, c, g, mat = M.FRAME, o = {}) => { const n = mark(m); ctCyl(m, [0, 0, 0], [0, o.crushed ? .07 : .15, 0], .045, mat, g, { paint: p => Math.abs(p[1] - .06) < .03 && !o.crushed ? M.HAT1 : undefined, end: M.FRAME }); place(m, n, { roll: o.roll ?? 0, yaw: o.yaw ?? 0, at: c }); };
const pBottle = (m, c, g, o = {}) => { const n = mark(m); m.seg([0, 0, 0], [0, .2, 0], .05, .05, M.HAT2, { group: g }); m.seg([0, .2, 0], [0, .32, 0], .045, .018, M.HAT2, { group: g }); place(m, n, { roll: o.roll ?? 0, yaw: o.yaw ?? 0, at: c }); };
const pHat = (m, c, g, o = {}) => { const n = mark(m); m.seg([0, 0, 0], [0, .28, 0], .1, .008, M.HAT1, { group: g, paint: p => ((p[1] + Math.atan2(p[2], p[0]) * .04) * 14) % 1 < .5 ? M.BODY : M.POM }); m.ell([0, .29, 0], [.03, .03, .03], M.POM, { group: g + 1 }); place(m, n, { roll: o.roll ?? 0, yaw: o.yaw ?? 0, at: c }); };
// a glowstick: a thin neon rod (MAGIC, bright core MAGIC2)
const pStick = (m, a, b, g) => m.seg(a, b, .03, .03, M.MAGIC, { group: g, paint: p => ctCell(p, 40) < .3 ? M.MAGIC2 : undefined });
// a candle: wax stub, a flame (GLOW) with a hot core (RUNE)
const pCandle = (m, c, h, r, g) => { ctCyl(m, c, v3.add(c, [0, h, 0]), r, M.BELLY, g, { end: M.CLOTH }); m.ell(v3.add(c, [0, h + .045, 0]), [.025, .05, .025], M.GLOW, { group: g + 1, paint: p => p[1] < c[1] + h + .04 ? M.RUNE : undefined }); };
// a string of bulbs along a polyline (each bulb glows: warm or neon)
const pString = (m, pts, n, g, mat = M.GLOW) => { const seg = []; for (let i = 0; i + 1 < pts.length; i++) seg.push([pts[i], pts[i + 1]]); const L = seg.map(([a, b]) => Math.hypot(...v3.sub(b, a))), T = L.reduce((a, b) => a + b, 0);
  m.chain(pts.map(p => [...p, .006]), M.NOSE, { group: g }); for (let k = 0; k < n; k++) { let d = (k + .5) / n * T, i = 0; while (i < L.length - 1 && d > L[i]) { d -= L[i]; i++; } const p = v3.lerp(seg[i][0], seg[i][1], d / L[i]); m.ell(v3.add(p, [0, -.03, 0]), [.035, .04, .035], k % 3 === 1 && mat === M.GLOW ? M.MAGIC : mat, { group: g + 1 }); } };
// a sagging curve between two points
const pSag = (a, b, sag, n = 10) => Array.from({ length: n + 1 }, (_, i) => { const t = i / n; return v3.add(v3.lerp(a, b, t), [0, -Math.sin(t * Math.PI) * sag, 0]); });
const pChair = (m, c, g, { yaw = 0, mat = M.BELLY } = {}) => { const n = mark(m); m.box([0, .4, 0], [.2, .025, .2], mat, { round: .02, group: g }); m.box([-.19, .63, 0], [.025, .22, .2], mat, { round: .02, group: g }); for (const x of [-.17, .17]) for (const z of [-.17, .17]) m.seg([x, 0, z], [x * .95, .4, z * .95], .02, .02, mat, { group: g }); place(m, n, { yaw, at: c }); };
const pNeon = shape => (s, t) => { const d = shape(s, t); return d < .06 ? M.MAGIC2 : d < .14 ? M.MAGIC : null; }; // a neon tube along an outline, as a distance

const PARTY = {
  // ---- litter: small and many ----
  "cup-red": { cls: "litter", desc: "a red party cup on its side", build(m) { pCup(m, [0, .045, 0], 1, M.ACCENT, 1.5); } },
  "cup-paper": { cls: "litter", desc: "a paper cup, standing, a little crushed", build(m) { pCup(m, [0, 0, 0], 1, M.CLOTH); } },
  "cups": { cls: "litter", desc: "three party cups, two knocked over", build(m) { pCup(m, [0, 0, 0], 1); pCup(m, [.2, .045, .1], 2, M.ACCENT, 1.5); pCup(m, [-.15, .045, .15], 3, M.CLOTH, -1.4); } },
  "can": { cls: "litter", desc: "a drinks can lying in the grass (no label)", build(m) { pCan(m, [0, .045, 0], 1, M.FRAME, { roll: 1.57, yaw: .4 }); } },
  "cans": { cls: "litter", desc: "a few cans, one crushed flat", build(m) { pCan(m, [0, 0, 0], 1, M.FRAME); pCan(m, [.18, .045, .08], 2, M.BODY2, { roll: 1.57, yaw: -.5 }); pCan(m, [-.14, .02, .14], 3, M.HAT1, { crushed: true, roll: 1.4 }); } },
  "bottle": { cls: "litter", desc: "a green glass bottle, standing", build(m) { pBottle(m, [0, 0, 0], 1); } },
  "bottle-fallen": { cls: "litter", desc: "a bottle on its side", build(m) { pBottle(m, [0, .05, 0], 1, { roll: 1.57, yaw: .6 }); } },
  "party-hat": { cls: "litter", desc: "a striped party hat fallen in the grass, its pompom gold", build(m) { pHat(m, [0, .06, 0], 1, { roll: 1.2, yaw: .3 }); } },
  "party-hat-up": { cls: "litter", desc: "a party hat set upright on the ground", build(m) { pHat(m, [0, 0, 0], 1); } },
  "streamers": { cls: "litter", desc: "curls of party streamer across the ground", decal: true, build(m) { for (let k = 0; k < 3; k++) { const pts = []; for (let i = 0; i <= 14; i++) { const t = i / 14; pts.push([-.4 + t * .8, .012, (k - 1) * .12 + Math.sin(t * 9 + k) * .08, .012]); } m.chain(pts, [M.BODY, M.HAT1, M.POM][k], { group: 1 + k }); } } },
  "confetti": { cls: "litter", desc: "a scatter of confetti over the ground", decal: true, build(m) { m.flat([0, .008, 0], [1, 0, 0], [0, 0, 1], .6, .45, (u, v) => { const p = [u * 3, 0, v * 3], r = Math.hypot(u, v), n = ctCell(p, 8, 1); if (r > .6 + ctCell(p, 2, 4) * .4 || n > .4) return null; return n < .1 ? M.BODY : n < .2 ? M.HAT1 : n < .28 ? M.POM : n < .34 ? M.TOP : M.BELLY; }, { group: 1, bend: 0 }); } },
  "glitter": { cls: "litter", desc: "spilt glitter catching the light, a faint sparkle on the ground", decal: true, glow: true, light: "neon", build(m) { m.flat([0, .008, 0], [1, 0, 0], [0, 0, 1], .45, .35, (u, v) => { const p = [u * 3, 0, v * 3], r = Math.hypot(u, v), n = ctCell(p, 9, 2); if (r > .55 + ctCell(p, 2, 6) * .45 || n > .45) return null; return n < .12 ? M.MAGIC2 : n < .3 ? M.MAGIC : M.FRAME; }, { group: 1, bend: 0 }); } },
  "glowstick-crushed": { cls: "litter", desc: "a glowstick snapped and crushed, its glow leaking into the grass", glow: true, light: "neon", build(m) { pStick(m, [-.1, .02, 0], [.02, .02, .03], 1); pStick(m, [.04, .02, .02], [.13, .02, -.05], 2); m.flat([0, .006, .01], [1, 0, 0], [0, 0, 1], .14, .1, (u, v) => Math.hypot(u, v) < .8 && ctCell([u * 3, 0, v * 3], 6) < .6 ? M.MAGIC : null, { group: 3, bend: 0 }); } },

  // ---- light sources: the readability workhorses ----
  "glowsticks-stuck": { cls: "small", desc: "glowsticks stuck upright in the ground like candles", glow: true, light: "neon", build(m) { for (let i = 0; i < 5; i++) { const a = i * 1.3, x = Math.cos(a) * .18 * (i % 2 + .4), z = Math.sin(a) * .14; pStick(m, [x, 0, z], [x + (ctHash(i) - .5) * .06, .2 + ctHash(i, 2) * .06, z], 1 + i); } } },
  "glowsticks-strewn": { cls: "small", desc: "glowsticks strewn across the grass", glow: true, light: "neon", build(m) { for (let i = 0; i < 6; i++) { const x = (ctHash(i, 5) - .5) * .9, z = (ctHash(5, i) - .5) * .6, a = ctHash(i, 6) * 6.28; pStick(m, [x, .02, z], [x + Math.cos(a) * .15, .02, z + Math.sin(a) * .15], 1 + i); } } },
  "glowstick-bracelets": { cls: "small", desc: "glowstick bracelets looped over a stick in the ground", glow: true, light: "neon", build(m) { ctBar(m, [0, 0, 0], [.03, .45, 0], 1, .015, M.WOOD, undefined); for (let i = 0; i < 3; i++) m.flat([.02, .15 + i * .1, 0], [1, .2 * (i - 1), 0], [0, .3, 1], .08, .08, (s, t) => Math.abs(Math.hypot(s, t) - .8) < .18 ? (i === 1 ? M.MAGIC2 : M.MAGIC) : null, { group: 2 + i, bend: .1 }); } },
  "tea-lights": { cls: "small", desc: "a little cluster of tea lights flickering on a flat stone", glow: true, light: "warm", build(m) { m.ell([0, .03, 0], [.25, .035, .2], M.STONE, { group: 1, rough: .006 }); for (let i = 0; i < 5; i++) { const a = i * 1.26, c = [Math.cos(a) * .13, .06, Math.sin(a) * .09]; ctCyl(m, c, v3.add(c, [0, .025, 0]), .035, M.FRAME, 2 + i, { end: M.BELLY }); m.ell(v3.add(c, [0, .06, 0]), [.022, .04, .022], M.GLOW, { group: 10 + i, paint: p => p[1] < c[1] + .055 ? M.RUNE : undefined }); } } },
  "candles": { cls: "small", desc: "a cluster of pillar candles of different heights, wax pooled round them", glow: true, light: "warm", build(m) { m.ell([0, .01, 0], [.2, .012, .16], M.BELLY, { group: 1 }); [[0, 0, .3, .05], [.09, .04, .2, .04], [-.08, .05, .15, .04], [.03, -.07, .1, .035]].forEach(([x, z, h, r], i) => pCandle(m, [x, .01, z], h, r, 2 + i * 2)); } },
  "jam-jar-lantern": { cls: "small", desc: "a jam-jar lantern, a candle glowing inside", glow: true, light: "warm", pointLight: { rgb: [255, 186, 96], radius: 2.5, height: .2 }, build(m) { ctCyl(m, [0, 0, 0], [0, .18, 0], .07, M.SHADES, 1, { paint: p => p[2] > .04 && p[1] > .03 && p[1] < .15 ? M.GLOW : undefined, end: M.FRAME }); m.ell([0, .08, 0], [.03, .05, .03], M.RUNE, { group: 2, extra: true }); m.chain([[-.07, .18, 0, .005], [0, .28, 0, .005], [.07, .18, 0, .005]], M.FRAME, { group: 3 }); } },
  "lantern-pole": { cls: "small", desc: "a paper lantern hanging from a shepherd's-crook pole, glowing warm amber", glow: true, light: "warm", bob: [.04, 2.8], pointLight: { rgb: [255, 186, 96], radius: 3.5, height: 1.3 }, build(m) { m.chain([[0, 0, 0, .018], [0, 1.4, 0, .015], [.1, 1.55, 0, .012], [.25, 1.5, 0, .012]], M.FRAME, { group: 1 }); m.seg([.25, 1.5, 0], [.25, 1.38, 0], .004, .004, M.NOSE, { group: 2 }); m.ell([.25, 1.24, 0], [.14, .15, .14], M.GLOW, { group: 3, paint: p => Math.abs(Math.sin(p[1] * 60)) > .85 ? M.RUNE : undefined }); } },
  "lantern-string": { cls: "small", desc: "a string of round paper lanterns sagging between two poles", glow: true, light: "warm", bob: [.05, 3.2], pointLight: { rgb: [255, 186, 96], radius: 4.5, height: 1.2 }, build(m) { for (const x of [-.9, .9]) ctBar(m, [x, 0, 0], [x, 1.45, 0], 1, .02, M.WOOD, undefined); const pts = pSag([-.9, 1.42, 0], [.9, 1.42, 0], .25); m.chain(pts.map(p => [...p, .005]), M.NOSE, { group: 2 }); [2, 4, 6, 8].forEach((i, k) => m.ell(v3.add(pts[i], [0, -.12, 0]), [.09, .1, .09], k % 2 ? M.RUNE : M.GLOW, { group: 3 + k })); } },
  "fairy-bush": { cls: "small", desc: "a bush draped in warm fairy lights, a few bulbs in neon", glow: true, light: "warm", bob: [.015, 3.6], build(m) { for (const [x, y, z, r] of [[0, .3, 0, .38], [-.25, .22, .1, .25], [.25, .24, -.05, .26]]) m.ell([x, y, z], [r, r * .85, r], M.LEAF, { group: 1, rough: .03, paint: p => ctCell(p, 10, 2) < .3 ? M.LEAF3 : undefined }); const pts = []; for (let i = 0; i <= 16; i++) { const a = i / 16 * Math.PI * 2.4 - 1, y = .12 + i * .032; pts.push([Math.cos(a) * .5, y, Math.sin(a) * .42]); } pString(m, pts, 12, 3); } },
  "fairy-branch": { cls: "small", desc: "a fallen bough propped up, wound with fairy lights", glow: true, light: "warm", bob: [.02, 3.4], build(m) { m.chain([[-.7, 0, 0, .06], [-.3, .45, 0, .05], [.2, .6, .05, .04], [.6, .4, .05, .03]], M.TRUNK, { group: 1, rough: .01 }); m.seg([-.3, .45, 0], [-.4, 0, .1], .03, .03, M.TRUNK, { group: 1 }); const pts = []; for (let i = 0; i <= 18; i++) { const t = i / 18, b = t < .33 ? v3.lerp([-.7, 0, 0], [-.3, .45, 0], t * 3) : t < .66 ? v3.lerp([-.3, .45, 0], [.2, .6, .05], (t - .33) * 3) : v3.lerp([.2, .6, .05], [.6, .4, .05], (t - .66) * 3); pts.push(v3.add(b, [0, Math.sin(i * 1.7) * .06, Math.cos(i * 1.7) * .06])); } pString(m, pts, 10, 2); } },
  "tiki-torch": { cls: "small", desc: "a bamboo tiki torch, its flame burning", glow: true, light: "warm", build(m) { m.seg([0, 0, 0], [0, 1.25, 0], .025, .03, M.STRAW, { group: 1, paint: p => (p[1] * 6) % 1 < .08 ? M.WOOD : undefined }); m.seg([0, 1.2, 0], [0, 1.38, 0], .06, .05, M.STRAW, { group: 2, paint: p => ctCell(p, 30) < .3 ? M.WOOD : undefined }); m.flat([0, 1.52, .01], [1, 0, .3], [0, 1, 0], .1, .17, (s, t) => { const u = (t + 1) / 2, half = Math.sin(Math.PI * Math.min(1, u * 1.1)) * (1 - u) * 1.4; return Math.abs(s) > half ? null : Math.abs(s) < half * .45 && u < .6 ? M.RUNE : M.GLOW; }, { group: 3, bend: .2 }); } },
  "fire-pit-lit": { cls: "small", desc: "a little fire pit in a ring of stones, its fire lit", glow: true, light: "warm", build(m) { for (let i = 0; i < 8; i++) { const a = i / 8 * 6.283; m.ell([Math.cos(a) * .32, .06, Math.sin(a) * .26], [.08, .065, .07], M.STONE, { group: 1 + (i % 2), rough: .01 }); } for (const [a, b] of [[[-.18, .04, -.05], [.15, .1, .06]], [[-.06, .04, .14], [.12, .08, -.12]]]) m.seg(a, b, .035, .03, M.BARKD, { group: 3, paint: p => ctCell(p, 25) < .4 ? M.GLOW : undefined }); [[0, 0], [.05, .05], [-.05, .03]].forEach(([x, z], i) => m.flat([x, .2 + i * .02, z], [1, 0, .4], [0, 1, 0], .08 - i * .015, .16 - i * .03, (s, t) => { const u = (t + 1) / 2, half = Math.sin(Math.PI * Math.min(1, u * 1.1)) * (1 - u) * 1.4; return Math.abs(s) > half ? null : Math.abs(s) < half * .45 && u < .6 ? M.RUNE : M.GLOW; }, { group: 4 + i, bend: .2 })); } },
  "led-cube": { cls: "small", desc: "a glowing LED cube seat, lit from within in a neon", glow: true, light: "neon", build(m) { m.box([0, .2, 0], [.2, .2, .2], M.MAGIC, { round: .03, group: 1, paint: p => p[1] > .38 || ctCell(p, 8) < .15 ? M.MAGIC2 : undefined }); } },
  "mirror-ball": { cls: "small", desc: "a little mirror ball hanging from a crooked branch stand, throwing sparkles", glow: true, light: "neon", bob: [.03, 4.0], build(m) { m.chain([[0, 0, 0, .03], [.02, .9, 0, .025], [.2, 1.25, 0, .02], [.45, 1.32, 0, .015]], M.TRUNK, { group: 1, rough: .006 }); m.seg([.45, 1.32, 0], [.45, 1.12, 0], .004, .004, M.NOSE, { group: 2 }); m.ell([.45, 1.0, 0], [.12, .12, .12], M.FRAME, { group: 3, paint: p => { const a = Math.atan2(p[2], p[0] - .45), b = p[1]; return (Math.floor(a * 5) + Math.floor(b * 30)) % 2 ? M.SHADES : ctCell(p, 30) < .25 ? M.MAGIC2 : undefined; } }); for (let i = 0; i < 4; i++) ctGlow(m, [.45 + Math.cos(i * 1.6) * .35, .55 + ctHash(i) * .5, Math.sin(i * 1.6) * .3], .018, 4 + i, M.MAGIC2); } },
  "uv-rock": { cls: "small", desc: "a mossy rock splashed with ultraviolet paint, glowing", glow: true, light: "neon", build(m) { m.ell([0, .2, 0], [.4, .25, .3], M.STONE, { group: 1, rough: .03, paint: p => { const n = ctCell(p, 9, 2), s = Math.hypot(p[0] - .1, p[1] - .3) < .12 || Math.hypot(p[0] + .2, p[2] - .2) < .08; return s || n < .08 ? M.MAGIC : n > .85 ? M.MOSS : undefined; } }); } },
  "uv-stump": { cls: "small", desc: "a stump daubed with glowing ultraviolet spirals", glow: true, light: "neon", build(m) { ctCyl(m, [0, 0, 0], [0, .35, 0], .22, M.TRUNK, 1, { paint: p => { const a = Math.atan2(p[2], p[0]); return Math.abs(Math.sin(a * 2 + p[1] * 18)) > .9 && p[2] > 0 ? M.MAGIC : ctCell(p, 12) < .15 ? M.BARKD : undefined; }, end: p => (Math.hypot(p[0], p[2]) * 30) % 1 < .2 ? M.MAGIC : M.STRAW }); } },

  // ---- hanging from real branches (Ed: hang them from real branch points; the pole versions stay for open ground). Each hangs from its
  // `hang` anchor (the top attach point, pixels from the sprite's top-left), which the prototype puts on a branch point; `bob` swings it ----
  "lantern-hanging": { cls: "small", desc: "a paper lantern hanging on its cord from a branch, glowing warm amber", glow: true, light: "warm", hang: true, anchors: { hang: [0, 1.6, 0] }, bob: [.05, 2.8], pointLight: { rgb: [255, 186, 96], radius: 3.5, height: 1.2 }, build(m) { m.seg([0, 1.6, 0], [0, 1.4, 0], .004, .004, M.NOSE, { group: 1 }); m.ell([0, 1.26, 0], [.14, .15, .14], M.GLOW, { group: 2, paint: p => Math.abs(Math.sin(p[1] * 60)) > .85 ? M.RUNE : undefined }); m.seg([0, 1.1, 0], [0, 1.06, 0], .03, .02, M.BODY3, { group: 3 }); } },
  "lanterns-hanging": { cls: "small", desc: "three paper lanterns hanging at different heights from one branch", glow: true, light: "warm", hang: true, anchors: { hang: [0, 1.7, 0] }, bob: [.06, 3.1], pointLight: { rgb: [255, 186, 96], radius: 4, height: 1.2 }, build(m) { [[-.2, 1.25, .02, .11], [.05, 1.0, -.05, .14], [.25, 1.3, .04, .1]].forEach(([x, y, z, r], i) => { m.chain([[0, 1.7, 0, .004], [x, y + r + .02, z, .004]], M.NOSE, { group: 1 }); m.ell([x, y, z], [r, r * 1.08, r], i === 1 ? M.RUNE : M.GLOW, { group: 2 + i, paint: p => Math.abs(Math.sin(p[1] * 70)) > .85 ? M.RUNE : undefined }); }); } },
  "jar-hanging": { cls: "small", desc: "a jam-jar lantern hanging on a wire from a branch, its candle lit", glow: true, light: "warm", hang: true, anchors: { hang: [0, 1.3, 0] }, bob: [.04, 2.6], pointLight: { rgb: [255, 186, 96], radius: 2.5, height: 1.0 }, build(m) { m.chain([[0, 1.3, 0, .005], [0, 1.15, 0, .005]], M.FRAME, { group: 1 }); m.chain([[-.07, 1.1, 0, .005], [0, 1.15, 0, .005], [.07, 1.1, 0, .005]], M.FRAME, { group: 1 }); ctCyl(m, [0, .92, 0], [0, 1.1, 0], .07, M.SHADES, 2, { paint: p => p[2] > .04 && p[1] > .95 && p[1] < 1.07 ? M.GLOW : undefined, end: M.FRAME }); m.ell([0, 1.0, 0], [.03, .05, .03], M.RUNE, { group: 3, extra: true }); } },
  "fairy-lights-hanging": { cls: "small", desc: "a strand of warm fairy lights hanging in loops from a branch", glow: true, light: "warm", hang: true, anchors: { hang: [0, 1.6, 0] }, bob: [.02, 3.3], build(m) { const pts = []; for (let i = 0; i <= 20; i++) { const t = i / 20; pts.push([Math.sin(t * Math.PI * 3) * .3, 1.6 - Math.sin(t * Math.PI) * .9 - t * .2, Math.cos(t * Math.PI * 3) * .08]); } pString(m, pts, 12, 1); } },
  "mirror-ball-hanging": { cls: "small", desc: "a little mirror ball hanging on a cord from a branch, throwing sparkles", glow: true, light: "neon", hang: true, anchors: { hang: [0, 1.5, 0] }, bob: [.03, 4.0], build(m) { m.seg([0, 1.5, 0], [0, 1.2, 0], .004, .004, M.NOSE, { group: 1 }); m.ell([0, 1.08, 0], [.12, .12, .12], M.FRAME, { group: 2, paint: p => { const a = Math.atan2(p[2], p[0]), b = p[1]; return (Math.floor(a * 5) + Math.floor(b * 30)) % 2 ? M.SHADES : ctCell(p, 30) < .25 ? M.MAGIC2 : undefined; } }); for (let i = 0; i < 4; i++) ctGlow(m, [Math.cos(i * 1.6) * .35, .6 + ctHash(i) * .5, Math.sin(i * 1.6) * .3], .018, 3 + i, M.MAGIC2); } },
  // ---- furniture ----
  "folding-table": { cls: "furniture", desc: "a folding table left out, cups, cans and a bottle on it", build(m) { m.box([0, .55, 0], [.6, .02, .3], M.BELLY, { round: .02, group: 1, paint: p => ctCell(p, 14) < .1 ? M.STONED : undefined }); for (const x of [-.5, .5]) for (const s of [-1, 1]) ctBar(m, [x, 0, s * .25], [x, .54, -s * .2], 2, .015, M.FRAME, undefined); pCup(m, [-.3, .57, .1], 3); pCup(m, [-.15, .57, -.1], 4, M.CLOTH); pCan(m, [.1, .57, .05], 5, M.FRAME); pBottle(m, [.35, .57, -.05], 6); pCup(m, [.25, .6, .15], 7, M.ACCENT, 1.5); } },
  "plastic-chair": { cls: "furniture", desc: "a white plastic garden chair", build(m) { pChair(m, [0, 0, 0], 1); } },
  "plastic-chair-tipped": { cls: "furniture", desc: "a plastic chair tipped on its back", build(m) { const n = mark(m); pChair(m, [0, 0, 0], 1); place(m, n, { roll: 0, pitch: 1.3, at: [.3, .12, 0] }); } },
  "camping-chair": { cls: "furniture", desc: "a folding camping chair in bright fabric, a can in its cup holder", build(m) { for (const s of [-1, 1]) { ctBar(m, [-.2, 0, s * .22], [.2, .42, s * .22], 1, .015, M.FRAME, undefined); ctBar(m, [.2, 0, s * .22], [-.2, .42, s * .22], 1, .015, M.FRAME, undefined); ctBar(m, [-.2, .42, s * .22], [-.28, .82, s * .22], 1, .015, M.FRAME, undefined); } m.box([0, .38, 0], [.21, .04, .22], M.TOP, { round: .03, group: 2 }); m.box([-.25, .62, 0], [.02, .2, .22], M.TOP, { round: .01, group: 2 }); pCan(m, [.05, .4, .3], 3, M.HAT1); } },
  "deck-chair": { cls: "furniture", desc: "a striped deck chair", build(m) { for (const z of [-.25, .25]) { ctBar(m, [-.4, 0, z], [.2, .75, z], 1, .018, M.WOOD, undefined); ctBar(m, [.3, 0, z], [-.15, .35, z], 1, .018, M.WOOD, undefined); } m.box([-.08, .38, 0], [.42, .01, .24], M.BODY, { dir: [.8, .9, 0], up: [-.9, .8, 0], round: .005, group: 2, paint: p => Math.floor((p[2] + 1) * 12) % 2 ? M.BELLY : undefined }); } },
  "picnic-rug": { cls: "furniture", desc: "a bright picnic rug with crisps, cups and a birthday cake, its candle lit", glow: true, light: "warm", build(m) { m.box([0, .012, 0], [.55, .012, .42], M.BODY, { round: .006, group: 1, paint: p => (Math.floor((p[0] + 5) * 7) + Math.floor((p[2] + 5) * 7)) % 2 ? M.HAT1 : undefined }); pCup(m, [-.3, .02, .1], 2); pCup(m, [.25, .02, -.2], 3, M.CLOTH); m.box([.05, .04, .1], [.08, .02, .1], M.POM, { group: 4, dir: [1, 0, .4] }); ctCyl(m, [-.05, .02, -.15], [-.05, .1, -.15], .09, M.BELLY, 5, { end: M.BODY }); pCandle(m, [-.05, .1, -.15], .05, .01, 7); } },
  "cool-box": { cls: "furniture", desc: "a cool box, its lid open, cans inside", build(m) { m.box([0, .18, 0], [.3, .18, .2], M.HAT1, { round: .04, group: 1, paint: p => p[1] > .3 ? M.BELLY : undefined }); m.box([0, .32, 0], [.26, .1, .16], M.NOSE, { group: 1, cut: true }); const n = mark(m); m.box([0, 0, 0], [.3, .03, .2], M.BELLY, { round: .02, group: 2 }); place(m, n, { roll: -1.3, at: [0, .52, -.24] }); for (let i = 0; i < 3; i++) pCan(m, [-.12 + i * .12, .2, 0], 3 + i, i % 2 ? M.BODY2 : M.FRAME); } },
  "hay-seat": { cls: "furniture", desc: "a square hay bale with a blanket thrown over it for a seat", build(m) { m.box([0, .2, 0], [.42, .2, .24], M.STRAW, { round: .05, group: 1, rough: .008, paint: p => ctCell(p, 22) < .16 ? M.BARK2 : undefined }); m.box([.05, .41, 0], [.32, .02, .27], M.TOP, { round: .02, group: 2, rough: .006, paint: p => Math.floor((p[0] + 5) * 10) % 2 ? M.POM : undefined }); } },
  "hammock": { cls: "furniture", desc: "a hammock slung between two posts, a cushion in it", build(m) { for (const x of [-1.0, 1.0]) m.seg([x, 0, 0], [x * 1.02, 1.1, 0], .05, .045, M.TRUNK, { group: 1, rough: .006 }); const pts = pSag([-.95, .95, 0], [.95, .95, 0], .5, 12); m.chain(pts.map(p => [...p, .006]), M.CLOTH, { group: 2 }); m.ell([0, .5, 0], [.62, .1, .22], M.HAT1, { group: 3, paint: p => Math.floor((p[0] + 5) * 8) % 2 ? M.POM : undefined }); m.ell([.4, .62, 0], [.12, .06, .12], M.BODY, { group: 4 }); } },
  "gazebo": { cls: "furniture", desc: "a pop-up gazebo, string lights round its edge, one leg bent", glow: true, light: "warm", build(m) { for (const [x, z, bend] of [[-.8, -.8, 0], [.8, -.8, 0], [.8, .8, .15], [-.8, .8, 0]]) ctBar(m, [x, 0, z], [x - bend, 1.55, z], 1, .02, M.FRAME, undefined); m.seg([0, 1.55, 0], [0, 1.95, 0], 1.1, .05, M.BELLY, { group: 2, paint: p => Math.floor((Math.atan2(p[2], p[0]) + 4) * 2.5) % 2 ? M.BODY : undefined }); m.box([0, 1.0, 0], [1.4, .8, 1.4], M.BELLY, { group: 2, cut: true }); const c = [[-.8, 1.55, -.8], [.8, 1.55, -.8], [.8, 1.55, .8], [-.8, 1.55, .8]]; for (let i = 0; i < 4; i++) pString(m, pSag(c[i], c[(i + 1) % 4], .12, 6), 6, 3 + i * 2); } },
  "party-tent": { cls: "furniture", desc: "a little dome tent, a lantern glowing inside it", glow: true, light: "warm", build(m) { m.ell([0, 0, 0], [.75, .62, .6], M.HAT2, { group: 1, paint: p => p[2] > .35 && Math.abs(p[0]) < .2 && p[1] < .45 ? M.GLOW : Math.abs(Math.sin(Math.atan2(p[2], p[0]) * 2)) > .97 ? M.BODY3 : undefined }); m.box([0, -.5, 0], [1, .5, 1], M.NOSE, { group: 1, cut: true }); } },

  // ---- set dressing: rarer ----
  "dj-booth": { cls: "set", desc: "a small DJ booth: decks on a trestle table, a speaker beside it, lights on the decks", glow: true, light: "neon", build(m) { m.box([0, .7, 0], [.6, .03, .3], M.WOOD, { round: .02, group: 1, paint: ctPlank(7, 0) }); for (const x of [-.5, .5]) ctBar(m, [x, 0, 0], [x, .68, 0], 1, .025, M.FRAME, undefined); m.box([0, .65, .29], [.6, .3, .01], M.TOP, { group: 2, paint: p => Math.floor((p[0] + 5) * 6) % 2 ? M.BODY3 : undefined }); for (const x of [-.32, .32]) { m.box([x, .76, 0], [.22, .03, .2], M.BODY3, { round: .02, group: 3 }); m.ell([x, .8, 0], [.13, .012, .13], M.NOSE, { group: 4, paint: p => Math.abs(Math.hypot(p[0] - x, p[2]) - .1) < .012 ? M.MAGIC : undefined }); } m.box([0, .78, .1], [.07, .02, .09], M.BODY3, { group: 5, paint: p => ctCell(p, 30) < .4 ? M.MAGIC2 : undefined }); m.box([.95, .45, 0], [.22, .45, .22], M.BODY3, { round: .03, group: 6, paint: p => p[2] > .2 && (Math.hypot(p[0] - .95, p[1] - .3) < .14 || Math.hypot(p[0] - .95, p[1] - .7) < .08) ? M.NOSE : undefined }); } },
  "inflatable-flamingo": { cls: "set", desc: "a pink inflatable flamingo, a little saggy", build(m) { m.ell([0, .3, 0], [.45, .28, .3], M.BODY, { group: 1 }); m.chain([[.35, .4, 0, .09], [.5, .75, 0, .07], [.45, 1.0, 0, .06], [.55, 1.1, 0, .06]], M.BODY, { group: 1 }); m.ell([.6, 1.12, 0], [.1, .07, .07], M.BODY, { group: 1 }); m.seg([.68, 1.12, 0], [.8, 1.0, 0], .035, .02, M.BELLY, { group: 2, paint: p => p[1] < 1.04 ? M.NOSE : undefined }); m.ell([.6, 1.15, .06], [.015, .015, .015], M.NOSE, { group: 3 }); m.ell([-.4, .4, 0], [.15, .1, .2], M.BODY, { group: 1 }); } },
  "inflatable-ring": { cls: "set", desc: "an inflatable unicorn ring left on the grass, its horn gold", build(m) { m.ell([0, .12, 0], [.55, .14, .5], M.BELLY, { group: 1, paint: p => Math.floor((Math.atan2(p[2], p[0]) + 4) * 2) % 2 ? M.TOP : undefined }); m.ell([0, .12, 0], [.28, .3, .24], M.NOSE, { group: 1, cut: true }); m.chain([[.5, .2, 0, .1], [.65, .45, 0, .08], [.75, .55, 0, .08]], M.BELLY, { group: 2 }); m.seg([.78, .62, 0], [.85, .85, 0], .03, .006, M.POM, { group: 3 }); } },
  "crate-bar": { cls: "set", desc: "a bar built of stacked crates, bottles on top, fairy lights along its front", glow: true, light: "warm", build(m) { for (const [x, y] of [[-.55, .18], [0, .18], [.55, .18], [-.55, .54], [0, .54], [.55, .54]]) m.box([x, y, 0], [.26, .17, .2], M.WOOD, { round: .015, group: 1 + (y > .3 ? 1 : 0), paint: p => ((p[1] + 5) * 9 % 1) < .22 ? M.NOSE : ctPlank(7, 0)(p) }); m.box([0, .74, 0], [.85, .025, .25], M.WOOD, { round: .01, group: 3, paint: ctPlank(7, 0) }); for (let i = 0; i < 5; i++) pBottle(m, [-.6 + i * .3, .77, (ctHash(i) - .5) * .2], 4 + i); pString(m, pSag([-.82, .72, .22], [.82, .72, .22], .12, 10), 9, 10); } },
  "bunting-run": { cls: "set", desc: "a run of bright bunting on two poles", build(m) { for (const x of [-1.2, 1.2]) ctBar(m, [x, 0, 0], [x, 1.6, 0], 1, .025, M.WOOD, undefined); const pts = pSag([-1.2, 1.55, 0], [1.2, 1.55, 0], .3, 12), cols = [M.BODY, M.HAT1, M.POM, M.TOP, M.HAT2]; m.chain(pts.map(p => [...p, .006]), M.CLOTH, { group: 2 }); for (let i = 1; i < 12; i++) m.flat(v3.add(pts[i], [0, -.1, 0]), [1, 0, 0], [0, 1, 0], .07, .1, (s, t) => Math.abs(s) < (t + 1) / 2 ? cols[i % 5] : null, { group: 3, bend: .1 }); } },
  "neon-heart": { cls: "set", desc: "a neon heart outline on a stake, glowing (no words)", glow: true, light: "neon", build(m) { ctBar(m, [0, 0, -.02], [0, .9, -.02], 1, .02, M.FRAME, undefined); m.flat([0, 1.15, 0], [1, 0, 0], [0, 1, 0], .35, .35, pNeon((s, t) => { const x = s * 1.2, y = t * 1.2 + .25; const a = x * x + y * y - 1; return Math.abs(a * a * a - x * x * y * y * y) * 2.2; }), { group: 2, bend: .05 }); } },
  "neon-star": { cls: "set", desc: "a neon star outline on a stake, glowing", glow: true, light: "neon", build(m) { ctBar(m, [0, 0, -.02], [0, .9, -.02], 1, .02, M.FRAME, undefined); m.flat([0, 1.15, 0], [1, 0, 0], [0, 1, 0], .35, .35, pNeon((s, t) => { const a = Math.atan2(t, s) + Math.PI / 2, r = Math.hypot(s, t), R = .45 + .4 * Math.abs(Math.cos(a * 2.5)); return Math.abs(r - R * .95); }), { group: 2, bend: .05 }); } },
  "neon-moon": { cls: "set", desc: "a neon crescent moon on a stake, glowing", glow: true, light: "neon", build(m) { ctBar(m, [0, 0, -.02], [0, .9, -.02], 1, .02, M.FRAME, undefined); m.flat([0, 1.15, 0], [1, 0, 0], [0, 1, 0], .35, .35, pNeon((s, t) => { const a = Math.hypot(s, t) - .8, b = Math.hypot(s - .35, t - .15) - .65; return Math.abs(Math.max(a, -b)); }), { group: 2, bend: .05 }); } },
  "flag-poles": { cls: "set", desc: "festival flags on tall bending poles: plain bright colours and stripes", build(m) { [[-.4, 0, 2.1, M.BODY], [.1, -.15, 2.4, M.HAT1], [.5, .1, 1.9, M.POM]].forEach(([x, z, h, mat], i) => { m.chain([[x, 0, z, .025], [x, h * .6, z, .02], [x + .08, h, z, .012]], M.FRAME, { group: 1 + i }); m.flat([x + .22, h - .45, z + .01], [.2, 1, 0], [1, -.1, 0], .4, .14, (s, t) => { const w = .7 + .3 * (1 - (s + 1) / 2); return Math.abs(t) > w ? null : i === 1 && Math.abs(t) < .3 ? M.BELLY : mat; }, { group: 5 + i, bend: .2 }); }); } },
};


// ---------------- balloons (Ed: "they don't emit light but they reflect it well, and they come in many colours and in bunches") ----------------
// Shiny, never glowing: saturated colour and a crisp highlight pixel or two, true normals, so they pop when a light is near and fall dark when
// not. Seven colour slots (BALLOON), filled at bake by a palette (partyColours(style, neon, palette): neon, pastel, metallic or mixed); a bunch
// cycles through them. Each balloon piece has a `bob` hint (amplitude in metres, period in seconds, phase 0 to 1) for the game to sway it, and a
// `tie` anchor where its strings meet.
const BALLOON = [M.SKIN, M.HAIR, M.IRIS, M.JACKET, M.JEANS, M.SHOES, M.PHONES], SHINE = M.WEB;
const pShine = (c, dirH = [-.35, .55, .76], k = .95) => p => { const d = v3.norm(v3.sub(p, c)); return v3.dot(d, dirH) > k ? SHINE : undefined; };
// one round balloon: a slightly tall sphere, its knot below; returns the knot
const pBalloon = (m, c, r, mat, g, o = {}) => { m.ell(c, [r, r * 1.15, r * (o.flat ?? 1)], mat, { group: g, dir: o.dir, paint: pShine(c) }); const k = v3.add(c, [0, -r * 1.15, 0]); m.seg(v3.add(k, [0, r * .1, 0]), v3.add(k, [0, -r * .12, 0]), r * .14, r * .05, mat, { group: g }); return v3.add(k, [0, -r * .12, 0]); };
// a bunch of n balloons on strings from `tie`, lifted `lift` above it, colours from slot `from`
const pBunch = (m, tie, n, g, { lift = 1.0, spread = .32, from = 0, seed = 1, r = .13 } = {}) => {
  for (let i = 0; i < n; i++) { const a = i * 2.4 + seed, d = spread * Math.sqrt((i + .5) / n), c = v3.add(tie, [Math.cos(a) * d, lift + (ctHash(i, seed) - .3) * .25 + (i % 2) * .12, Math.sin(a) * d * .8]); const knot = pBalloon(m, c, r * (.9 + ctHash(seed, i) * .2), BALLOON[(from + i) % 7], g + i); m.chain([[...tie, .006], [...v3.lerp(tie, knot, .5).map((v, j) => j === 0 ? v + (ctHash(i, 9) - .5) * .06 : v), .006], [...knot, .006]], M.CLOTH, { group: g + 10 }); }
};
const pStake = (m, top, g) => m.seg([top[0], 0, top[2]], top, .016, .012, M.WOOD, { group: g });
const BALLOONS = {
  "balloon-single": { desc: "a single balloon on its string, tied to a stake", bob: [.08, 3.2], anchors: { tie: [0, .3, 0] }, build(m) { pStake(m, [0, .3, 0], 1); pBunch(m, [0, .3, 0], 1, 2, { lift: .9, spread: 0, from: 2 }); } },
  "balloons-stake": { desc: "a bunch of five balloons tied to a stake in the ground", bob: [.1, 3.6], anchors: { tie: [0, .35, 0] }, build(m) { pStake(m, [0, .35, 0], 1); pBunch(m, [0, .35, 0], 5, 2, { from: 0 }); } },
  "balloons-bunch": { desc: "a bunch of seven balloons, their strings gathered to one knot, to tie to a branch, a fence or anything (its tie anchor)", bob: [.12, 4.0], anchors: { tie: [0, 0, 0] }, build(m) { pBunch(m, [0, 0, 0], 7, 1, { lift: 1.1, spread: .4, from: 3, seed: 2 }); } },
  "balloons-table": { desc: "a folding table with four balloons tied to its leg", bob: [.09, 3.4], anchors: { tie: [.5, .55, .25] }, build(m) { PARTY["folding-table"].build(m); pBunch(m, [.5, .55, .25], 4, 20, { from: 1, seed: 3 }); } },
  "balloons-chair": { desc: "a plastic chair with three balloons tied to its back", bob: [.08, 3.0], anchors: { tie: [-.2, .85, .15] }, build(m) { pChair(m, [0, 0, 0], 1); pBunch(m, [-.2, .85, .15], 3, 20, { lift: .85, from: 4, seed: 4 }); } },
  "balloons-post": { desc: "a fence post with five balloons tied to its top", bob: [.1, 3.8], anchors: { tie: [0, .95, 0] }, build(m) { m.box([0, .48, 0], [.06, .48, .06], M.WOOD, { round: .02, group: 1, paint: ctPlank(7, .3) }); pBunch(m, [0, .95, 0], 5, 2, { lift: .95, from: 5, seed: 5 }); } },
  "balloons-long": { desc: "long twisty balloons, three on a stake, one twisted into a spiral", bob: [.07, 3.3], anchors: { tie: [0, .3, 0] }, build(m) { pStake(m, [0, .3, 0], 1); [[-.15, 1.1, .02, -.25, 0], [.12, 1.2, -.04, .2, 1]].forEach(([x, y, z, lean, i]) => { const c = [x, y, z]; m.ell(c, [.06, .32, .06], BALLOON[i], { group: 2 + i, dir: [lean, 1, 0], up: [1, -lean, 0], paint: pShine(c, [-.5, .2, .84], .97) }); m.chain([[0, .3, 0, .006], [x * .6, .6, z, .006], [x - lean * .3, y - .32, z, .006]], M.CLOTH, { group: 9 }); }); const pts = []; for (let k = 0; k <= 10; k++) { const t = k / 10; pts.push([.02 + Math.cos(t * 12) * .06, .85 + t * .55, .15 + Math.sin(t * 12) * .06, .05]); } m.chain(pts, BALLOON[2], { group: 5, paint: pShine([.02, 1.1, .15], [-.4, .3, .86], .9) }); m.chain([[0, .3, 0, .006], [.02, .6, .1, .006], [.08, .85, .15, .006]], M.CLOTH, { group: 9 }); } },
  "balloon-foil-star": { desc: "a foil star balloon on a string weighted to the ground", bob: [.09, 3.5], anchors: { tie: [0, .06, 0] }, build(m) { m.ell([0, .04, 0], [.06, .05, .06], M.BODY3, { group: 1 }); m.chain([[0, .06, 0, .006], [.04, .6, 0, .006], [0, 1.05, 0, .006]], M.CLOTH, { group: 2 }); m.flat([0, 1.3, 0], [1, 0, .2], [0, 1, 0], .25, .25, (s, t) => { const a = Math.atan2(t, s) + Math.PI / 2, r = Math.hypot(s, t), R = .5 + .45 * Math.abs(Math.cos(a * 2.5)); return r > R ? null : Math.hypot(s + .25, t - .3) < .12 ? SHINE : BALLOON[0]; }, { group: 3, bend: .5 }); } },
  "balloon-foil-heart": { desc: "a foil heart balloon on a string weighted to the ground", bob: [.09, 3.1], anchors: { tie: [0, .06, 0] }, build(m) { m.ell([0, .04, 0], [.06, .05, .06], M.BODY3, { group: 1 }); m.chain([[0, .06, 0, .006], [-.04, .6, 0, .006], [0, 1.05, 0, .006]], M.CLOTH, { group: 2 }); m.flat([0, 1.3, 0], [1, 0, .2], [0, 1, 0], .25, .25, (s, t) => { const x = s * 1.15, y = t * 1.15 + .2, a = x * x + y * y - 1; return a * a * a - x * x * y * y * y > 0 ? null : Math.hypot(s + .3, t - .25) < .12 ? SHINE : BALLOON[1]; }, { group: 3, bend: .5 }); } },
  "balloon-deflated": { desc: "a deflated balloon, wrinkled on the ground, its string trailing", build(m) { m.ell([0, .02, 0], [.11, .025, .08], BALLOON[0], { group: 1, rough: .012, paint: pShine([0, 0, 0], [-.3, .9, .3], .97) }); m.chain([[.1, .01, 0, .005], [.25, .01, .06, .005], [.38, .01, -.03, .005]], M.CLOTH, { group: 2 }); } },
  "balloon-half": { desc: "a half-deflated balloon sagging on the ground at the end of its string", bob: [.02, 4.5], build(m) { pBalloon(m, [0, .12, 0], .13, BALLOON[5], 1, { dir: [.3, 1, .2], flat: .8 }); m.chain([[0, .0, .05, .005], [.2, .01, .1, .005], [.35, .01, 0, .005]], M.CLOTH, { group: 2 }); } },
  // tall ones (Ed, round 11: "taller balloon variants, with single balloons as well as bunches"): long strings, the balloons up high
  "balloon-tall": { desc: "a single balloon high on a long string, tied to a stake", bob: [.14, 3.9], anchors: { tie: [0, .3, 0] }, build(m) { pStake(m, [0, .3, 0], 1); pBunch(m, [0, .3, 0], 1, 2, { lift: 2.3, spread: 0, from: 6 }); } },
  "balloon-tall-weight": { desc: "a single balloon very high on its string, held down by a little weight", bob: [.16, 4.3], anchors: { tie: [0, .06, 0] }, build(m) { m.ell([0, .04, 0], [.06, .05, .06], M.BODY3, { group: 1 }); pBunch(m, [0, .06, 0], 1, 2, { lift: 2.7, spread: 0, from: 3, r: .15 }); } },
  "balloons-tall-three": { desc: "three balloons high on long strings from one stake", bob: [.13, 4.1], anchors: { tie: [0, .3, 0] }, build(m) { pStake(m, [0, .3, 0], 1); pBunch(m, [0, .3, 0], 3, 2, { lift: 2.1, spread: .3, from: 1, seed: 6 }); } },
  "balloons-tall-big": { desc: "a big bunch of nine balloons high on long strings from one stake", bob: [.15, 4.6], anchors: { tie: [0, .35, 0] }, build(m) { pStake(m, [0, .35, 0], 1); pBunch(m, [0, .35, 0], 9, 2, { lift: 2.0, spread: .55, from: 4, seed: 7 }); } },
  "balloon-caught": { desc: "an escaped balloon caught high in a tree, its string hanging down; hangs from its `tie` (top) anchor in a crown", bob: [.05, 2.6], hang: true, anchors: { tie: [0, 1.0, 0], hang: [0, 1.0, 0] }, build(m) { pBalloon(m, [0, 1.12, 0], .13, BALLOON[6], 1); const pts = []; for (let k = 0; k <= 8; k++) { const t = k / 8; pts.push([Math.sin(t * 7) * .04, .97 - t * .97, 0, .005]); } m.chain(pts, M.CLOTH, { group: 2 }); } },
};

// ---------------- campfires (Ed: "Put campfires into the party objects library") ----------------
// The world campfire's look (areas.js: grey ring stones, crossed logs, flame planes in its fire orange and gold), in three flickering frames
// (`frames`), with embers and sparks rising. Lit ones are few and bright, so they carry `pointLight` { rgb, radius m, height m } for real lights.
const FIRE = M.WOKEN, FIRE2 = M.COLLAR; // fire orange and its gold core (the world campfire's colours, in partyColours)
const pFire = (m, c, k, frame, g) => {
  const H = [[.42, .3, .34, .26], [.36, .4, .28, .32], [.46, .32, .38, .24]][frame % 3];
  [[-.05, 0], [.08, .06], [-.02, -.08], [.05, -.03]].forEach(([x, z], i) => { const hh = H[i] * k; m.flat(v3.add(c, [x * k, hh * .5, z * k]), [1, 0, .3], [((frame + i) % 3 - 1) * .1, 1, 0], hh * .38, hh * .5, masks.flame(FIRE, FIRE2), { group: g + i, bend: .1 }); });
  for (let i = 0; i < 5; i++) { const y = (.3 + ((i * .37 + frame * .21) % 1) * .9) * k; ctGlow(m, v3.add(c, [Math.sin(i * 2.3 + frame) * .12 * k, y + .2 * k, Math.cos(i * 1.7) * .08 * k]), .012 + .01 * (i % 2), g + 10 + i, i % 2 ? FIRE2 : FIRE); } // embers and sparks rising
};
const pRing = (m, c, R, g, n = 9) => { for (let i = 0; i < n; i++) { const a = i / n * Math.PI * 2; m.ell(v3.add(c, [Math.cos(a) * R, .05 * R / .32, Math.sin(a) * R * .9]), [.09 * R / .32, .06 * R / .32, .08 * R / .32], i % 3 ? M.STONE : M.STONED, { dir: [-Math.sin(a), 0, Math.cos(a)], group: g + (i % 3), rough: .006 }); } };
const pLogs = (m, c, k, g, cold = false) => { m.seg(v3.add(c, [-.22 * k, .06 * k, -.12 * k]), v3.add(c, [.22 * k, .1 * k, .12 * k]), .05 * k, .045 * k, M.TRUNK, { group: g, paint: p => p[0] > c[0] + .1 * k ? M.BARKD : cold && ctCell(p, 20) < .4 ? M.NOSE : undefined }); m.seg(v3.add(c, [-.2 * k, .1 * k, .14 * k]), v3.add(c, [.2 * k, .06 * k, -.14 * k]), .05 * k, .045 * k, M.TRUNK, { group: g + 1, paint: p => p[0] < c[0] - .1 * k ? M.BARKD : cold && ctCell(p, 20) < .4 ? M.NOSE : undefined }); };
const pLogSeat = (m, c, yaw, g) => { const d = [Math.cos(yaw), 0, Math.sin(yaw)]; ctCyl(m, v3.add(c, v3.mul(d, -.45)), v3.add(c, v3.mul(d, .45)), .12, M.TRUNK, g, { paint: p => ctCell(p, 14) < .15 ? M.BARKD : ctCell(p, 6, 2) < .12 ? M.MOSS : undefined, end: p => (Math.hypot(...v3.sub(p, c).map((v, i) => i === 1 ? v : 0)) * 30) % 1 < .2 ? M.BARK2 : M.STRAW }); };
const WARM_FIRE = [255, 150, 60];
const CAMPFIRES = {
  "campfire-small": { cls: "small", desc: "a small ring of stones round a little fire", glow: true, light: "warm", frames: 3, pointLight: { rgb: WARM_FIRE, radius: 6, height: .5 }, build(m, f = 0) { pRing(m, [0, 0, 0], .32, 1); pLogs(m, [0, 0, 0], 1, 5); pFire(m, [0, .1, 0], .9, f, 10); } },
  "campfire-logs": { cls: "furniture", desc: "a campfire with log seats round it and toasting sticks leaning in", glow: true, light: "warm", frames: 3, pointLight: { rgb: WARM_FIRE, radius: 9, height: .6 }, build(m, f = 0) { pRing(m, [0, 0, 0], .4, 1, 10); pLogs(m, [0, 0, 0], 1.2, 5); pFire(m, [0, .12, 0], 1.15, f, 10); pLogSeat(m, [0, .12, -1.0], 0, 30); pLogSeat(m, [-1.0, .12, .2], 1.4, 31); pLogSeat(m, [1.0, .12, .3], -1.3, 32); for (const [x, z] of [[-.6, .6], [.5, .55]]) { ctBar(m, [x * 1.3, 0, z * 1.3], [x * .3, .45, z * .3], 33, .008, M.WOOD, undefined); m.ell([x * .3, .46, z * .3], [.03, .025, .03], M.BELLY, { group: 34 }); } } },
  "campfire-kettle": { cls: "furniture", desc: "a campfire with a kettle hanging from a tripod over it, mugs on a stone", glow: true, light: "warm", frames: 3, pointLight: { rgb: WARM_FIRE, radius: 8, height: .6 }, build(m, f = 0) { pRing(m, [0, 0, 0], .36, 1); pLogs(m, [0, 0, 0], 1.05, 5); pFire(m, [0, .1, 0], .8, f, 10); for (let i = 0; i < 3; i++) { const a = i / 3 * 6.283 + .4; ctBar(m, [Math.cos(a) * .5, 0, Math.sin(a) * .45], [0, .95, 0], 30, .015, M.WOOD, undefined); } m.seg([0, .95, 0], [0, .62, 0], .004, .004, M.NOSE, { group: 31 }); m.ell([0, .52, 0], [.11, .1, .1], M.BODY3, { group: 32, paint: pShine([0, .52, 0], [-.35, .55, .76], .9) }); m.seg([.08, .55, 0], [.18, .62, 0], .02, .012, M.BODY3, { group: 32 }); m.ell([.75, .06, .3], [.18, .06, .14], M.STONE, { group: 33 }); for (const x of [.68, .82]) ctCyl(m, [x, .11, .3], [x, .19, .3], .035, x > .7 ? M.ACCENT : M.HAT1, 34, { end: M.NOSE }); } },
  "bonfire": { cls: "set", desc: "a big bonfire: a tall cone of logs roaring, sparks flying high", glow: true, light: "warm", frames: 3, pointLight: { rgb: WARM_FIRE, radius: 16, height: 1.2 }, build(m, f = 0) { for (let i = 0; i < 9; i++) { const a = i / 9 * 6.283; ctBar(m, [Math.cos(a) * .7, 0, Math.sin(a) * .6], [Math.cos(a) * .08, 1.4, Math.sin(a) * .07], 1 + (i % 3), .06, M.TRUNK, p => p[1] < .5 && ctCell(p, 10) < .4 ? M.BARKD : ctCell(p, 16) < .2 ? M.NOSE : undefined); } pFire(m, [0, .05, 0], 3.0, f, 10); pFire(m, [.15, .4, .1], 1.6, (f + 1) % 3, 30); } },
  "campfire-cold": { cls: "small", cold: true, desc: "a cold, burnt-out campfire: charred logs in grey ash inside its ring", build(m) { pRing(m, [0, 0, 0], .32, 1); m.ell([0, .02, 0], [.26, .025, .22], M.STONED, { group: 4, paint: p => ctCell(p, 18) < .3 ? M.STONE : undefined }); pLogs(m, [0, -.02, 0], .9, 5, true); } },
  "bonfire-ashes": { cls: "furniture", cold: true, desc: "the ashes of a bonfire: a heap of charred ends in a wide grey ring", build(m) { m.ell([0, .03, 0], [.85, .05, .72], M.STONED, { group: 1, paint: p => ctCell(p, 14) < .25 ? M.STONE : ctCell(p, 9, 3) < .15 ? M.NOSE : undefined }); for (let i = 0; i < 6; i++) { const a = i * 1.1; ctBar(m, [Math.cos(a) * .6, .04, Math.sin(a) * .5], [Math.cos(a + .3) * .1, .18, Math.sin(a + .3) * .1], 2 + (i % 2), .05, M.BARKD, p => ctCell(p, 12) < .5 ? M.NOSE : undefined); } } },
};


// ---------------- the home stretch (Ed's playtest: decorate the home area between the dancefloor and the home soundsystem) ----------------
// A small set, class "home", for the prototype to place along that stretch, never on the dancefloor itself: a path edge of stepping stones,
// a glowing mushroom ring, warm lantern posts and little path lights, a speaker stack, a crate stack, flower pots, a signpost (blank arrows
// and a glowing note, no words) and a fairy-lit branch arch to walk under. Same conventions as the rest: glow and light (neon or warm),
// pointLight on the lantern posts.
const HOME = {
  "stepping-stones": { desc: "a curve of flat stepping stones set in the moss, to edge the path", build(m) { for (let i = 0; i < 5; i++) { const t = i / 4, x = -.9 + t * 1.8, z = Math.sin(t * Math.PI) * .25; m.ell([x, .02, z], [.16 + ctHash(i) * .04, .035, .13], M.STONE, { group: 1 + (i % 2), rough: .006, paint: p => ctCell(p, 12, i) < .2 ? M.MOSS : undefined }); } } },
  "mushroom-ring": { desc: "a fairy ring of little mushrooms, their caps glowing softly", glow: true, light: "neon", build(m) { for (let i = 0; i < 11; i++) { const a = i / 11 * Math.PI * 2, x = Math.cos(a) * .45, z = Math.sin(a) * .36, h = .05 + ctHash(i, 2) * .05; m.seg([x, 0, z], [x, h, z], .012, .01, M.CLOTH, { group: 1 }); m.ell([x, h + .012, z], [.035, .018, .035], i % 3 ? M.MAGIC : M.MAGIC2, { group: 2 + (i % 2) }); } m.ell([0, .004, 0], [.42, .004, .33], M.LEAF3, { group: 9 }); } },
  "lantern-post": { desc: "a wooden lantern post, an iron lantern on its arm glowing warm", glow: true, light: "warm", bob: [.02, 3.0], pointLight: { rgb: [255, 186, 96], radius: 4, height: 1.4 }, build(m) { m.box([0, .7, 0], [.05, .7, .05], M.WOOD, { round: .015, group: 1, paint: ctPlank(7, .2) }); m.box([.12, 1.36, 0], [.15, .025, .025], M.WOOD, { round: .01, group: 1 }); m.seg([.24, 1.33, 0], [.24, 1.26, 0], .004, .004, M.NOSE, { group: 2 }); m.box([.24, 1.16, 0], [.06, .09, .06], M.BODY3, { round: .01, group: 3, paint: p => Math.abs(p[0] - .24) < .045 && Math.abs(p[1] - 1.16) < .07 && Math.abs(p[2]) > .045 ? M.GLOW : undefined }); m.ell([.24, 1.16, 0], [.03, .05, .03], M.RUNE, { group: 4, extra: true }); m.seg([.24, 1.25, 0], [.24, 1.3, 0], .065, .01, M.BODY3, { group: 3 }); } },
  "path-lights": { desc: "little garden stake lights along a path edge, glowing warm", glow: true, light: "warm", build(m) { for (let i = 0; i < 4; i++) { const x = -.75 + i * .5, z = (i % 2) * .08; ctBar(m, [x, 0, z], [x, .2, z], 1, .012, M.BODY3, undefined); m.ell([x, .24, z], [.035, .04, .035], M.GLOW, { group: 2 + i, paint: p => p[1] > .25 ? M.RUNE : undefined }); m.seg([x, .27, z], [x, .3, z], .045, .01, M.BODY3, { group: 6 }); } } },
  "speaker-stack": { desc: "a small stack of speaker cabinets, their cone rims glowing in a neon", glow: true, light: "neon", build(m) { for (const [y, w, h, g] of [[.32, .28, .32, 1], [.84, .24, .2, 3]]) { m.box([0, y, 0], [w, h, .22], M.BODY3, { round: .025, group: g }); const cones = h > .25 ? [[0, y - .1, .14], [0, y + .14, .07]] : [[-.1, y, .06], [.1, y, .06]]; for (const [cx, cy, r] of cones) { m.ell([cx, cy, .23], [r, r, .045], M.NOSE, { group: g + 1, paint: p => Math.hypot(p[0] - cx, p[1] - cy) > r * .72 ? M.MAGIC : undefined }); } } } },
  "crate-stack": { desc: "wooden crates stacked by the path, one full of records", build(m) { const crate = (c, g) => m.box(c, [.24, .17, .19], M.WOOD, { round: .015, group: g, paint: p => ((p[1] - c[1] + 1) * 9 % 1) < .2 && Math.abs(p[1] - c[1]) < .14 ? M.NOSE : ctPlank(7, .1)(p) }); crate([0, .17, 0], 1); crate([.46, .17, .05], 2); crate([.2, .51, .02], 3); for (let i = 0; i < 6; i++) m.box([.2 - .15 + i * .06, .72, .02], [.012, .1, .14], i % 2 ? M.BODY3 : M.TOP, { round: .004, group: 4 }); } },
  "flower-pots": { desc: "terracotta pots of flowers clustered by the path", build(m) { [[0, 0, .14, M.BODY], [.3, .1, .1, M.POM], [-.25, .12, .11, M.TOP]].forEach(([x, z, r, fl], i) => { ctCyl(m, [x, 0, z], [x, r * 1.6, z], r, M.BODY2, 1 + i, { paint: p => p[1] > r * 1.45 ? M.STRAW : undefined, end: M.BARK2 }); for (let k = 0; k < 5; k++) { const a = k * 1.3 + i, d = r * .5; const c = [x + Math.cos(a) * d, r * 1.6 + .08 + ctHash(k, i) * .1, z + Math.sin(a) * d * .8]; m.seg([x + Math.cos(a) * d * .5, r * 1.6, z], c, .008, .006, M.LEAF2, { group: 10 + i }); m.ell(c, [.03, .025, .03], fl, { group: 14 + i }); } m.ell([x, r * 1.6 + .03, z], [r * .9, .05, r * .9], M.LEAF, { group: 18 + i }); }); } },
  "signpost": { desc: "a wooden signpost, two blank arrow boards pointing the way, a glowing note painted on one (no words)", glow: true, light: "neon", build(m) { m.box([0, .7, 0], [.045, .7, .045], M.WOOD, { round: .015, group: 1, paint: ctPlank(7, .3) }); const arrow = (y, dir, g, note) => m.flat([dir * .3, y, .05], [1, 0, 0], [0, 1, 0], .36, .13, (s, t) => { const u = s * dir; if (u > .7 && Math.abs(t) > (1 - u) * 3.3) return null; if (u < -.95) return null; if (note && Math.hypot(u - .05, t + .2) < .22) return M.MAGIC; if (note && Math.abs(u - .22) < .06 && t > -.2 && t < .75) return M.MAGIC; return Math.abs(Math.sin(t * 9)) > .95 ? M.BARK2 : M.WOOD; }, { group: g, bend: .05 }); arrow(1.25, 1, 2, true); arrow(1.0, -1, 3, false); } },
  "branch-arch": { desc: "an arch of bent branches over the path, fairy lights wound through it", glow: true, light: "warm", bob: [.015, 3.4], build(m) { const pts = []; for (let i = 0; i <= 10; i++) { const a = Math.PI * (1 - i / 10); pts.push([Math.cos(a) * .95, Math.sin(a) * 1.8, 0]); } m.chain(pts.map((p, i) => [...p, .06 - Math.abs(i - 5) * .006]), M.TRUNK, { group: 1, rough: .008 }); for (let i = 0; i < 6; i++) { const a = Math.PI * (.1 + i * .16); m.ell([Math.cos(a) * .95, Math.sin(a) * 1.8, .04], [.12, .07, .1], M.LEAF, { group: 2 + (i % 2), rough: .02 }); } pString(m, pts.map((p, i) => v3.add(p, [0, Math.sin(i * 1.9) * .05, .07])), 12, 5); } },
};

// ---------------- picnics (Ed, round 11: "there should be picnic blankets, and also picnic tables with chairs") ----------------
// Made by two small generators, so they vary: a blanket by its pattern, colours and what's on it; a table by its length, what's
// round it (chairs or benches) and whether it has a cloth.
// a cloth pattern's paint at a point: gingham (two stripe sets, the crossings deeper), stripes, tartan (two scales), or a border
const pCloth = (kind, a, b, k = 7) => p => { const u = Math.floor((p[0] + 5) * k), v = Math.floor((p[2] + 5) * k);
  if (kind === "gingham") return u % 2 && v % 2 ? b : u % 2 || v % 2 ? M.BELLY : a;
  if (kind === "stripes") return u % 2 ? b : a;
  if (kind === "tartan") { const U = Math.floor((p[0] + 5) * k * .5), V = Math.floor((p[2] + 5) * k * .5); return (U + V) % 2 ? (u % 3 === 0 || v % 3 === 0 ? M.BELLY : b) : a; }
  return undefined; };
const pBasket = (m, c, g) => { m.box(v3.add(c, [0, .08, 0]), [.13, .08, .09], M.STRAW, { round: .02, group: g, paint: p => Math.floor((p[0] + p[1]) * 40) % 2 ? M.WOOD : undefined }); m.chain([[c[0] - .1, c[1] + .16, c[2], .01], [c[0], c[1] + .3, c[2], .01], [c[0] + .1, c[1] + .16, c[2], .01]], M.WOOD, { group: g + 1 }); };
const pPlate = (m, c, g) => ctCyl(m, c, v3.add(c, [0, .012, 0]), .07, M.BELLY, g, { end: M.BELLY });
const pCake = (m, c, g) => { ctCyl(m, c, v3.add(c, [0, .09, 0]), .09, M.BELLY, g, { end: M.BODY }); pCandle(m, v3.add(c, [0, .09, 0]), .05, .01, g + 2); };
const pFruit = (m, c, g) => { [[0, 0, M.ACCENT], [.05, .03, M.HAT2], [-.04, .04, M.POM]].forEach(([dx, dz, mat], i) => m.ell(v3.add(c, [dx, .03, dz]), [.03, .03, .03], mat, { group: g + i })); };
// a blanket: { pattern, a, b (its two colours), w, d (half sizes, m), on: what's on it, as [thing, x, z] }
function pBlanket(m, { pattern, a, b, w = .6, d = .45, on = [] }) {
  m.box([0, .012, 0], [w, .012, d], a, { round: .006, group: 1, paint: pCloth(pattern, a, b) });
  on.forEach(([what, x, z], i) => { const c = [x, .024, z], g = 10 + i * 4; if (what === "basket") pBasket(m, c, g); else if (what === "cup") pCup(m, c, g); else if (what === "plate") pPlate(m, c, g); else if (what === "cake") pCake(m, c, g); else if (what === "fruit") pFruit(m, c, g); else if (what === "bottle") pBottle(m, c, g); });
}
// a picnic table: { len (half length, m), seats: "benches" or a number of chairs, cloth: a pattern and its colours or null, on: what's on it }
function pPicnicTable(m, { len = .7, seats = 4, cloth = null, on = [] }) {
  const top = .72, wd = .38;
  m.box([0, top, 0], [len, .03, wd], M.WOOD, { round: .01, group: 1, paint: ctPlank(9, .15) });
  if (cloth) m.box([0, top + .035, 0], [len * .96, .006, wd * 1.1], cloth.a, { group: 2, paint: pCloth(cloth.pattern, cloth.a, cloth.b, 9) });
  for (const x of [-len * .8, len * .8]) for (const sz of [-1, 1]) m.seg([x, top, sz * wd * .6], [x + (sz > 0 ? 0 : 0), 0, sz * wd * 1.25], .03, .03, M.WOOD, { group: 3 }); // A-frame legs
  if (seats === "benches") for (const sz of [-1, 1]) { m.box([0, .42, sz * wd * 1.55], [len, .025, .12], M.WOOD, { round: .01, group: 4 + (sz > 0 ? 1 : 0), paint: ctPlank(9, .15) }); }
  else for (let i = 0; i < seats; i++) { const side = i % 2 ? 1 : -1, k = Math.floor(i / 2), n = Math.ceil(seats / 2), x = n > 1 ? -len * .6 + k * (len * 1.2 / (n - 1)) : 0; pChair(m, [x, 0, side * (wd + .42)], 20 + i * 3, { yaw: side > 0 ? Math.PI / 2 : -Math.PI / 2, mat: i % 3 === 2 ? M.HAT1 : M.BELLY }); }
  on.forEach(([what, x, z], i) => { const c = [x, top + .04, z], g = 50 + i * 4; if (what === "basket") pBasket(m, c, g); else if (what === "cup") pCup(m, c, g); else if (what === "plate") pPlate(m, c, g); else if (what === "cake") pCake(m, c, g); else if (what === "fruit") pFruit(m, c, g); else if (what === "bottle") pBottle(m, c, g); });
}
const PICNIC_BLANKETS = [
  ["picnic-gingham-red", "a red gingham picnic blanket, a wicker basket and two cups on it", { pattern: "gingham", a: M.ACCENT, b: M.ACCENT, on: [["basket", -.25, -.1], ["cup", .3, .15], ["cup", .2, -.2]] }],
  ["picnic-gingham-blue", "a blue gingham picnic blanket, spread out empty", { pattern: "gingham", a: M.HAT1, b: M.HAT1 }],
  ["picnic-stripes", "a striped picnic blanket with a cake, its candle lit, and plates", { pattern: "stripes", a: M.POM, b: M.TOP, w: .55, on: [["cake", 0, 0], ["plate", -.3, .15], ["plate", .3, -.15]] }],
  ["picnic-tartan", "a tartan picnic blanket with a basket, a bottle and fruit", { pattern: "tartan", a: M.HAT2, b: M.ACCENT, w: .65, d: .5, on: [["basket", .25, .1], ["bottle", -.2, -.15], ["fruit", -.3, .2]] }],
  ["picnic-gingham-pink", "a pink gingham picnic blanket laid for tea: cups, plates and a cake", { pattern: "gingham", a: M.BODY, b: M.BODY, on: [["cake", .15, -.05], ["cup", -.3, .15], ["cup", -.2, -.2], ["plate", .35, .2]] }],
  ["picnic-border", "a plain orange picnic blanket, a basket at one corner", { pattern: "plain", a: M.BODY2, b: M.BODY2, w: .5, d: .4, on: [["basket", .3, .2]] }],
];
const PICNIC_TABLES = [
  ["picnic-table-benches", "a wooden picnic table with its benches, a basket on top", { len: .75, seats: "benches", on: [["basket", .3, 0]] }],
  ["picnic-table-four", "a picnic table with a red gingham cloth and four chairs round it, cups and a cake", { len: .7, seats: 4, cloth: { pattern: "gingham", a: M.ACCENT, b: M.ACCENT }, on: [["cake", 0, 0], ["cup", -.4, .15], ["cup", .4, -.15]] }],
  ["picnic-table-two", "a small picnic table with two chairs, a bottle and two cups", { len: .45, seats: 2, on: [["bottle", 0, 0], ["cup", -.2, .1], ["cup", .2, -.1]] }],
  ["picnic-table-long", "a long picnic table with a blue gingham cloth and six chairs, laid with plates and fruit", { len: 1.1, seats: 6, cloth: { pattern: "gingham", a: M.HAT1, b: M.HAT1 }, on: [["plate", -.6, .15], ["plate", 0, -.15], ["plate", .6, .15], ["fruit", -.2, .05], ["fruit", .35, 0]] }],
];
const PICNIC = Object.fromEntries([
  ...PICNIC_BLANKETS.map(([id, desc, o]) => [id, { desc, decal: !o.on?.length, ...(o.on?.some(([w]) => w === "cake") ? { glow: true, light: "warm" } : {}), build(m) { pBlanket(m, o); } }]),
  ...PICNIC_TABLES.map(([id, desc, o]) => [id, { desc, ...(o.on?.some(([w]) => w === "cake") ? { glow: true, light: "warm" } : {}), build(m) { pPicnicTable(m, o); } }]),
]);

// ---------------- the table ----------------
const SIZE = { litter: 1.5, balloon: 1.2, small: 1.2, furniture: 1, set: 1, home: 1, picnic: 1 }; // litter a touch larger than life, to read at all
// ---------------- generated (the prop generator, #119; behind ?props=gen): a few seeded variants each of the bunting, the balloon bunches
// and the paper lanterns, so they vary in shape (their genomes: PARTY_PROP_GENOMES, art/props/genomes.js). Each variant is a piece of
// its own ("gen-<kind>-<n>") that `replaces` the hand-made ones: the game swaps them in with partyObjects.generated (?props=gen). ----------------
const pgVar = (kind, k) => propVariant(kind, k * 7 + 3, {}, PARTY_PROP_GENOMES);
const PG_FLAG = { triangle: (s, t) => Math.abs(s) < (t + 1) / 2, square: (s, t) => t > -.8, round: (s, t) => s * s + (t - .2) ** 2 < .7, pennant: (s, t) => t > -1 + Math.abs(s) * 1.6 && (t < .6 || Math.abs(s) < .9) };
function pgBunting(m, v) {
  const L = v.span / 2, h = v.height, cols = [M.BODY, M.HAT1, M.POM, M.TOP, M.HAT2];
  for (const x of [-L, L]) ctBar(m, [x, 0, 0], [x * 1.01, h, 0], 1, .025, M.WOOD, undefined);
  for (let s = 0; s < v.strands; s++) {
    const y = h - .05 - s * .24, pts = pSag([-L, y, 0], [L, y, 0], v.sag * (1 + s * .35), v.flags + 1);
    m.chain(pts.map(p => [...p, .006]), M.CLOTH, { group: 2 + s * 3 });
    for (let i = 1; i < pts.length - 1; i++) { const mat = cols[(i + v.offset + s) % v.colours], sz = v.size * (1 - s * .15), f = PG_FLAG[v.shape]; m.flat(v3.add(pts[i], [0, -sz, 0]), [1, 0, 0], [0, 1, 0], sz * .75, sz, (a, b) => f(a, b) ? mat : null, { group: 3 + s * 3, bend: .1 }); }
    for (let i = 0; i < v.bulbs; i++) { const p = pts[Math.min(pts.length - 1, 1 + Math.floor((i + .5) / v.bulbs * (pts.length - 2)))]; m.ell(v3.add(p, [.03, -.02, .01]), [.018, .022, .018], M.GLOW, { group: 4 + s * 3 }); } // warm bulbs along it
  }
}
function pgBalloons(m, v) {
  const tie = v.anchor === "stake" ? [0, .3, 0] : [0, .06, 0];
  if (v.anchor === "stake") pStake(m, tie, 1); else m.ell([0, .04, 0], [.06, .05, .06], M.BODY3, { group: 1 }); // a stake, or a little weight on the ground
  pBunch(m, tie, v.count, 2, { lift: v.lift, spread: v.spread, from: v.from, seed: v.seed + 11, r: v.size });
}
function pgLanternShape(m, c, r, shape, i, g) { const tall = shape === "tall" || (shape === "mixed" && i % 2); m.ell(c, tall ? [r * .8, r * 1.5, r * .8] : [r, r * 1.05, r], i % 2 ? M.RUNE : M.GLOW, { group: g, paint: p => Math.abs(Math.sin((p[1] - c[1]) / r * 6)) > .88 ? M.RUNE : undefined }); return tall ? r * 1.5 : r * 1.05; } // warm amber paper (the art director, round 1: the party as warm pools of light)
function pgLanternString(m, v) {
  const L = v.span / 2, h = v.height;
  for (const x of [-L, L]) ctBar(m, [x, 0, 0], [x, h, 0], 1, .02, M.WOOD, undefined);
  const pts = pSag([-L, h - .03, 0], [L, h - .03, 0], v.sag, 12); m.chain(pts.map(p => [...p, .005]), M.NOSE, { group: 2 });
  for (let i = 0; i < v.count; i++) { const p = pts[1 + Math.round((i + .5) / v.count * 10)], r = v.size * (.8 + ((i * 37) % 5) / 10), drop = .04 + r; m.seg(p, v3.add(p, [0, -drop + r, 0]), .004, .004, M.NOSE, { group: 2 }); pgLanternShape(m, v3.add(p, [0, -drop, 0]), r, v.shape, i, 3 + i); }
}
function pgLanternsHanging(m, v, top) {
  for (let i = 0; i < v.count; i++) { const a = i / Math.max(1, v.count) * 2.4 - 1.2, x = Math.sin(a) * .38 * (v.count > 1), z = Math.cos(a) * .05, r = v.size * (.8 + ((i * 53) % 5) / 10), y = top[1] - v.drop * (.55 + ((i * 29) % 7) / 10); m.chain([[...top, .004], [x, y + r * 1.4, z, .004]], M.NOSE, { group: 1 }); pgLanternShape(m, [x, y, z], r, v.shape, i, 2 + i); }
}
const PARTY_GEN = {};
for (let k = 0; k < 4; k++) {
  const b = pgVar("buntingRun", k), bl = pgVar("balloonBunch", k), ls = pgVar("lanternString", k), lh = pgVar("lanternsHanging", k), top = [0, .45 + lh.drop * 1.6, 0];
  PARTY_GEN[`gen-bunting-${k}`] = { cls: "set", replaces: ["bunting-run"], desc: `bunting: ${b.strands} ${b.shape} strand${b.strands > 1 ? "s" : ""} of ${b.flags} flags, warm bulbs along it`, glow: true, light: "warm", bob: [.02, 3.4], build(m) { pgBunting(m, pgVar("buntingRun", k)); } };
  PARTY_GEN[`gen-balloons-${k}`] = { cls: "balloon", replaces: ["balloons-stake", "balloon-single"], desc: `a bunch of ${bl.count} balloons tied to a ${bl.anchor}`, bob: [.1, 3.6], anchors: { tie: bl.anchor === "stake" ? [0, .3, 0] : [0, .06, 0] }, build(m) { pgBalloons(m, pgVar("balloonBunch", k)); } };
  PARTY_GEN[`gen-lanterns-${k}`] = { cls: "small", replaces: ["lantern-string"], desc: `${ls.count} ${ls.shape} paper lanterns sagging between two poles, glowing warm amber`, glow: true, light: "warm", bob: [.05, 3.2], pointLight: { rgb: [255, 186, 96], radius: 4.5, height: 1.2 }, build(m) { pgLanternString(m, pgVar("lanternString", k)); } };
  PARTY_GEN[`gen-lanterns-hanging-${k}`] = { cls: "small", replaces: ["lanterns-hanging", "lantern-hanging"], desc: `${lh.count} ${lh.shape} paper lantern${lh.count > 1 ? "s" : ""} hanging from a branch, glowing warm amber`, glow: true, light: "warm", hang: true, anchors: { hang: top }, bob: [.06, 3.1], pointLight: { rgb: [255, 186, 96], radius: 4, height: 1.2 }, build(m) { pgLanternsHanging(m, pgVar("lanternsHanging", k), top); } };
}

export const PARTY_CLASSES = ["litter", "balloon", "small", "furniture", "set", "home", "picnic"];
const bobOf = (id, b) => b && { amplitude: b[0], period: b[1], phase: +((id.length * .137 + id.charCodeAt(id.length - 1) * .071) % 1).toFixed(2) };
export const PARTY_OBJECTS = [...Object.entries(PARTY), ...Object.entries(BALLOONS).map(([id, d]) => [id, { cls: "balloon", ...d }]), ...Object.entries(CAMPFIRES), ...Object.entries(HOME).map(([id, d]) => [id, { cls: "home", ...d }]), ...Object.entries(PICNIC).map(([id, d]) => [id, { cls: "picnic", ...d }]), ...Object.entries(PARTY_GEN)].map(([id, d]) => ({ id, size: SIZE[d.cls], split: null, glow: false, decal: false, light: null, frames: 1, ...d, bob: bobOf(id, d.bob) }));
export const PARTY_BY_ID = Object.fromEntries(PARTY_OBJECTS.map(d => [d.id, d]));
// The party neons (the sigils' neon palette) a neon piece can be baked in; warm light is candle gold.
export const PARTY_LIGHT_NEONS = Object.keys(NEON);
export const PARTY_WARM = [255, 186, 96];
// Balloon palettes for the seven balloon colour slots: the party neons, pastels, metallics and foils, or a mix.
export const BALLOON_PALETTES = {
  neon: [NEON.pink, NEON.cyan, NEON.acid, NEON.violet, NEON.orange, NEON.lemon, NEON.red],
  pastel: [[255, 182, 214], [168, 218, 255], [196, 250, 190], [214, 192, 255], [255, 214, 168], [255, 248, 176], [255, 196, 196]],
  metallic: [[232, 192, 84], [206, 210, 222], [226, 158, 148], [118, 158, 232], [232, 192, 84], [206, 210, 222], [206, 128, 78]], // gold, silver, rose gold, blue foil, copper
  mixed: [NEON.pink, [232, 192, 84], [168, 218, 255], NEON.cyan, [206, 210, 222], NEON.lemon, [214, 192, 255]],
};
export function partyColours(st = {}, neon = "pink", balloons = "mixed") {
  const leaf = st.leafHue ?? .3, trunk = st.trunkHue ?? .07, n = NEON[neon] || NEON.pink, core = n.map(v => Math.round(v + (255 - v) * .7)), bp = BALLOON_PALETTES[balloons] || BALLOON_PALETTES.mixed;
  return {
    ...Object.fromEntries(BALLOON.map((mat, i) => [mat, bp[i]])), [SHINE]: [255, 255, 255], // balloon colours, their highlight
    [FIRE]: [255, 130, 40], [FIRE2]: [255, 228, 120], // fire, as the world campfire's
    [M.MAGIC]: n, [M.MAGIC2]: core, [M.GLOW]: PARTY_WARM, [M.RUNE]: [255, 240, 200], // the neon and its white-hot core; candle gold and its core
    [M.ACCENT]: [214, 40, 50], [M.BODY]: [240, 90, 170], [M.HAT1]: [40, 190, 230], [M.POM]: [245, 200, 60], [M.TOP]: [150, 80, 230], [M.HAT2]: [44, 120, 70], [M.BODY2]: [235, 120, 40], // party red, hot pink, cyan, gold, violet, bottle green, orange
    [M.BELLY]: [236, 234, 228], [M.CLOTH]: [222, 210, 186], [M.FRAME]: [170, 174, 182], [M.BODY3]: [36, 34, 42], [M.NOSE]: [14, 12, 18], [M.SHADES]: [60, 70, 80], // white plastic, paper, metal, black kit, dark, glass
    [M.WOOD]: [150, 116, 78], [M.STRAW]: [200, 172, 104], [M.BARK2]: [110, 82, 54], [M.STONE]: [118, 116, 122], [M.STONED]: [60, 58, 66],
    [M.MOSS]: hsv2rgb(.26, .45, .45), [M.TRUNK]: hsv2rgb(trunk, .45, .36), [M.BARKD]: hsv2rgb(trunk + .03, .5, .17),
    [M.LEAF]: hsv2rgb(leaf, .55, .45), [M.LEAF2]: hsv2rgb(leaf - .03, .5, .6), [M.LEAF3]: hsv2rgb(leaf + .03, .6, .28), [M.LINE]: [24, 22, 30],
  };
}
export function partyModel(id, frame = 0) { const d = PARTY_BY_ID[id]; if (!d) throw new Error(`no party object "${id}"`); const m = new Model({ blend: .03 }); d.build(m, frame % d.frames); if (d.anchors?.hang) m.ell(d.anchors.hang, [.022, .022, .022], M.BODY3, { group: 99 }); return m; } // a hanging piece's knot at its hang point, so the crop keeps it
// One party object, drawn: { whole, top, bot, crownY, origin, anchors?, metres }, like the country pieces; `frame` for the animated ones
// (frames > 1: the campfires). Bake it with partyColours(style, neon, balloonPalette).
export function partySprite(id, st = {}, { ppm = 16, frame = 0 } = {}) { return pieceSprite(partyModel(id, frame), PARTY_BY_ID[id], st, ppm); }

// ---------------- clusters ----------------
// Small groupings of 3 to 8 objects, scattered many times over party ground (unlike scenes, not once per map). Each piece:
// [object, x, z, facing, neon] in model units (x right, z towards the viewer); sceneLayout(id) gives metres, like a scene's.
const CLUSTERS = {
  "table-and-chairs": { desc: "a folding table with cups and cans, chairs pulled round it, one tipped", pieces: [["folding-table", 0, 0], ["plastic-chair", -.9, .3], ["plastic-chair", .9, .4, "left"], ["plastic-chair-tipped", .2, -.8], ["cups", -.4, .9], ["cans", .7, 1.0]] },
  "candle-ring": { desc: "tea lights and candles in a ring round a picnic rug", pieces: [["picnic-rug", 0, 0], ["tea-lights", -.9, -.4], ["candles", .9, -.5], ["tea-lights", .8, .6, "left"], ["candles", -.7, .7, "left"], ["jam-jar-lantern", 0, -.9]] },
  "glowstick-scatter": { desc: "glowsticks in mixed neons, stuck in the ground and strewn about", pieces: [["glowsticks-stuck", 0, 0, undefined, "pink"], ["glowsticks-strewn", .7, .3, undefined, "cyan"], ["glowstick-crushed", -.6, .4, undefined, "acid"], ["glowsticks-stuck", -.4, -.5, "left", "lemon"], ["glowstick-crushed", .5, -.4, undefined, "violet"]] },
  "chill-corner": { desc: "deck chairs and a cool box under a paper lantern", pieces: [["deck-chair", -.5, 0], ["deck-chair", .5, .1, "left"], ["cool-box", 0, .7], ["lantern-pole", -1.0, -.6, undefined, "cyan"], ["can", .3, 1.1]] },
  "bar-corner": { desc: "a crate bar between two tiki torches, cups and cans in front", pieces: [["crate-bar", 0, 0], ["tiki-torch", -1.2, .1], ["tiki-torch", 1.2, .1, "left"], ["cups", -.3, .8], ["cans", .4, .9], ["bottle-fallen", .9, .7]] },
  "dj-corner": { desc: "a little DJ booth with a neon star and glowsticks round it", pieces: [["dj-booth", 0, 0, undefined, "magenta"], ["neon-star", -1.3, -.3, undefined, "cyan"], ["glowsticks-strewn", .2, .9, undefined, "acid"], ["cups", -.6, .8], ["led-cube", 1.5, .7, undefined, "pink"]] },
  "campfire-circle": { desc: "a campfire with a kettle on, camping chairs and a hay seat round it", pieces: [["campfire-kettle", 0, 0], ["camping-chair", -.9, -.2], ["camping-chair", .9, -.3, "left"], ["hay-seat", 0, .9], ["cans", .6, .7], ["party-hat", -.5, .7]] },
  "balloon-spot": { desc: "balloons on a stake, a stray, a deflated one, confetti and a fallen party hat", pieces: [["confetti", 0, 0], ["balloons-stake", .1, -.2], ["balloon-single", .9, -.5], ["party-hat", -.3, .2], ["balloon-deflated", .4, .3], ["streamers", -.2, -.4]] },
  "home-path": { desc: "a stretch of the home path's edge: stepping stones, path lights, flower pots, a lantern post", pieces: [["stepping-stones", 0, 0], ["path-lights", .3, .7], ["flower-pots", -1.4, .5], ["lantern-post", 1.5, -.4], ["mushroom-ring", -.6, -.8]] },
  "home-corner": { desc: "a corner by the home soundsystem: a speaker stack on crates' side, a signpost, a fairy ring", pieces: [["speaker-stack", 0, 0, undefined, "cyan"], ["crate-stack", 1.0, .3], ["signpost", -1.1, .2, undefined, "pink"], ["mushroom-ring", .2, 1.1, undefined, "acid"]] },
  "fireside": { desc: "a campfire with log seats, camping chairs, cups, a rug, and balloons tied nearby", pieces: [["campfire-logs", 0, 0], ["camping-chair", 1.5, .9, "left"], ["picnic-rug", -1.4, .9], ["cups", .4, 1.4], ["balloons-post", -1.6, -1.1], ["balloon-half", .9, 1.6]] },
  "bonfire-night": { desc: "a bonfire with hay seats round it, cans, glowsticks and a bunch of balloons on a post", pieces: [["bonfire", 0, 0], ["hay-seat", -1.6, .6], ["hay-seat", 1.5, .8, "left"], ["cans", .3, 1.4], ["glowsticks-strewn", -.6, 1.5, undefined, "acid"], ["balloons-post", 2.0, -.9, "left"]] },
};
export const PARTY_CLUSTERS = Object.entries(CLUSTERS).map(([id, d]) => ({ id, size: "party", ...d, pieces: d.pieces.map(([p, x, z, f, neon]) => [`party:${p}${neon && PARTY_BY_ID[p]?.light === "neon" ? "@" + neon : ""}`, x, z, f]) })); // (a warm piece carries no neon)
export const PARTY_CLUSTER_BY_ID = Object.fromEntries(PARTY_CLUSTERS.map(d => [d.id, d]));

// A sample patch of party ground, for the lab and previews: clusters and loose litter and lights scattered over a w × h
// pixel patch, as the prototype might. Returns [{ ref, x, y, depth }] (each piece's origin on the patch, in pixels; depth for
// sorting); compose with scenePiece(ref) and draw decals first. Clusters come from layout(id, { mirror }) (scenePlacements).
export function partyPatch(seed, layout, { w = 420, h = 250, clusters = 5, loose = 46 } = {}) {
  let t = seed * 9301 + 49297; const r = () => (t = (t * 9301 + 49297) % 233280) / 233280;
  const out = [], spots = [[.21, .28], [.71, .24], [.48, .6], [.17, .76], [.81, .76]].slice(0, clusters);
  spots.forEach(([fx, fy], i) => { const id = PARTY_CLUSTERS[(i * 3 + seed) % PARTY_CLUSTERS.length].id; for (const p of layout(id, { mirror: r() < .5 })) out.push({ ref: p.ref, x: fx * w + p.ox, y: fy * h + p.oy, flip: p.flip, depth: fy * h + p.oy }); });
  const pool = PARTY_OBJECTS.filter(d => d.cls === "litter" || d.cls === "small");
  for (let i = 0; i < loose; i++) { const d = pool[Math.floor(r() * pool.length)], n = PARTY_LIGHT_NEONS[Math.floor(r() * PARTY_LIGHT_NEONS.length)], x = 10 + r() * (w - 20), y = 14 + r() * (h - 20); out.push({ ref: `party:${d.id}${d.light === "neon" ? "@" + n : ""}`, x, y, flip: r() < .5, depth: y }); }
  return out;
}
