// Her face's features as hand-placed pixel parts (art direction round 1, docs/PORTRAIT-STYLE.md "Face"), each placed on the head
// box (64 x 64, art/target.ts) by FACE below: her left eye's parts drawn, her right eye's mirrored (the iris never: its
// highlights stay at the upper left, the light being on the left), the brows, the 16 mouths, the blush, sweat and tears.
// Letters as sprite.ts's LEGEND: L the lash line, W w * the whites, J I i P the iris and pupil, K the skin's outline (the lower
// lid), B the brows, M T t W the mouth, R blush, a b v sweat.

import { mirror, sprite, type Sprite } from "../sprite";

/** Where each feature's box goes on the head box (top-left, whole pixels). */
export const FACE = { eyeL: [10, 24], eyeR: [38, 24], iris: [6, 4], browL: [11, 21], browR: [43, 21], mouth: [25, 45], blushL: [14, 38], blushR: [42, 38], sweat: [54, 4], tearL: [11, 36], tearR: [49, 36] } as const;

// ---- eyes: 16 x 13, her left (our left: the outer corner, with the lashes' flick, on the left) ----
/** Open: a 2-3 px upper lid with its flick, whites (a cool shade under the lid), a soft lower lid in the skin's outline tone. */
const OPEN = `
L...............
.LL...LLLLL.....
.LLLLLLLLLLLLL..
..LLLLLLLLLLLLL.
...LwwwwwwwwwwL.
...LWWWWWWWWWWK.
...KWWWWWWWWWW..
....WWWWWWWWWW..
....WWWWWWWWWW..
....WWWWWWWWWW..
....WWWWWWWWWW..
.....WWWWWWWWW..
.....kKKKKKKk...`;
/** Half shut (a heavy lid: smug, determined, mid-blink). */
const HALF = `
................
................
................
L...............
.LLLLLLLLLLLLL..
..LLLLLLLLLLLLL.
...LwwwwwwwwwwK.
....WWWWWWWWWW..
....WWWWWWWWWW..
....WWWWWWWWWW..
....WWWWWWWWWW..
.....WWWWWWWWW..
.....kKKKKKKk...`;
/** Sleepy: the lid low over the iris. */
const SLEEPY = `
................
................
................
................
................
L...............
.LLLLLLLLLLLLL..
..LLLLLLLLLLLLL.
...LwwwwwwwwwwK.
....WWWWWWWWWW..
....WWWWWWWWWW..
.....WWWWWWWWW..
.....kKKKKKKk...`;
/** Shut (a blink): the lashes along the lid's line. */
const SHUT = `
................
................
................
................
................
................
L...............
.LLLLLLLLLLLLL..
..LLLLLLLLLLLL..
.....kKKKKKk....
................
................
................`;
/** Closed and content: the lashes curving down. */
const CLOSED = `
................
................
................
................
................
................
L...............
.LL..........LL.
..LLL......LLL..
....LLLLLLLL....
................
................
................`;
/** Happy: ^ arcs. */
const HAPPY = `
................
................
................
................
......LLLL......
....LLLLLLLL....
...LLL....LLL...
..LL........LL..
.LL..........LL.
................
................
................
................`;
/** Wide: the lid up and thin, more white round a smaller iris. */
const WIDE = `
....LLLLLLL.....
..LLLLLLLLLLLL..
.LLwwwwwwwwwwLL.
.LWWWWWWWWWWWWK.
.KWWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
...WWWWWWWWWW...
....kKKKKKKk....
................`;
/** Wince: > (her right eye's mirror gives <). */
const WINCE = `
................
................
................
.LL.............
...LLL..........
......LLLL......
.........LLLL...
......LLLL......
...LLL..........
.LL.............
................
................
................`;
/** Dizzy: a spiral. */
const DIZZY = `
................
................
.....LLLLLL.....
....L......L....
...L..LLLL..L...
...L.L....L.L...
...L.L..L.L.L...
...L.L.LL.L.L...
...L..L..L..L...
....L.....L.....
.....LLLLL......
................
................`;
/** The iris and pupil (7 x 8: the white 2 px on the outer side, 1 px on the inner, art direction round 2): dark at the top
 *  under the lid, light at the bottom, a 4 x 4 pupil, a 2 x 2 highlight at the upper left and a spark at the lower right. Moved
 *  1 px at a time for her gaze, clipped to the whites. */
const IRIS = `
JJJJJJJ
J**JJJJ
I**PPPI
IIPPPPI
IIPPPPI
IiIPPiI
iiiii*i
IiiiiiI`;
/** The iris with a sparkle (awed, aww): a second highlight and a star. */
const IRIS_SPARKLE = `
JJJJJJJ
J**JJ*J
I**PP**
IIPPPP*
IIP*PPI
IiIPPiI
iii*i*i
IiiiiiI`;
/** The small iris (wide eyes). */
const IRIS_SMALL = `
.......
.JJJJ..
J**JJJ.
I*PPJI.
IIPPII.
iiiiii.
.iIIi..
.......`;
const eye = (t: string) => { const l = sprite(t); return { l, r: mirror(l) }; };
export const EYES: Record<string, { l: Sprite; r: Sprite }> = { open: eye(OPEN), half: eye(HALF), sleepy: eye(SLEEPY), shut: eye(SHUT), closed: eye(CLOSED), happy: eye(HAPPY), wide: eye(WIDE), wince: eye(WINCE), dizzy: eye(DIZZY) };
export const IRISES = { plain: sprite(IRIS), sparkle: sprite(IRIS_SPARKLE), small: sprite(IRIS_SMALL) };

// ---- brows: 10 x 5, her left (outer end on the left), a thin arc in the hair's deep tone ----
const brow = (t: string) => { const l = sprite(t); return { l, r: mirror(l) }; };
export const BROWS: Record<string, { l: Sprite; r: Sprite }> = {
  flat: brow(`
..........
..........
...BBBBBBB
.BB.......
..........`),
  arched: brow(`
..........
...BBBBB..
.BB.....B.
B.........
..........`),
  cross: brow(`
..........
.BBB......
....BBB...
.......BBB
..........`),
  worried: brow(`
.......BBB
....BBB...
.BBB......
..........
..........`),
  low: brow(`
..........
..........
..........
..BBBBBBBB
.B........`),
};

// ---- mouths: 15 x 8, the mouth's middle at column 7; one corner a pixel higher (confident), no wider than the space between
// the eyes' outer corners less 4 px ----
const m = (t: string) => sprite(t);
export const MOUTHS: Record<string, Sprite> = {
  rest: m(`
...............
...............
.........M.....
.....MMMM......
...............
...............
...............
...............`),
  smile: m(`
...............
..........M....
...M.....M.....
....MMMMM......
...............
...............
...............
...............`),
  grin: m(`
..............M
.MMMMMMMMMMMMM.
.MWWWWWWWWWWWM.
..MTTTTttTTTM..
....MMMMMMM....
...............
...............
...............`),
  laugh: m(`
...............
..MMMMMMMMMMMM.
..MWWWWWWWWWWM.
..MTTTTTTTTTTM.
...MTTttttTTM..
....MMttttMM...
......MMMM.....
...............`),
  O: m(`
...............
...............
......MMM......
.....MTTTM.....
.....MTtTM.....
......MMM......
...............
...............`),
  gasp: m(`
...............
.....MMMMM.....
....MTTTTTM....
....MTTTTTM....
....MTTTTTM....
....MTtttTM....
.....MMMMM.....
...............`),
  A: m(`
...............
...............
....MMMMMMM....
....MWWWWWM....
....MTTTTTM....
.....MTttM.....
......MMM......
...............`),
  E: m(`
...............
...............
...MMMMMMMMM...
...MWWWWWWWM...
....MTTTTTM....
.....MMMMM.....
...............
...............`),
  U: m(`
...............
...............
...............
......MMM......
......MTM......
......MMM......
...............
...............`),
  M: m(`
...............
...............
...............
....MMMMMMM....
...............
...............
...............
...............`),
  F: m(`
...............
...............
...............
....MMMMMMM....
....MWWWWWM....
.....MMMMM.....
...............
...............`),
  frown: m(`
...............
...............
...............
.....MMMMM.....
....M.....M....
...............
...............
...............`),
  eww: m(`
...............
...............
...MMMMMMMMMM..
..MWMWMWMWMWMM.
..MMMMMMMMMMMM.
.M............M
...............
...............`),
  wavy: m(`
...............
...............
...............
...MM...MM.....
.....MMM..MMM..
...............
...............
...............`),
  smirk: m(`
...............
...........MM..
..........M....
.....MMMMM.....
...............
...............
...............
...............`),
  cat: m(`
...............
...............
...............
....M..M..M....
.....MM.MM.....
...............
...............
...............`),
};

// ---- blush (short diagonal strokes), sweat, tears ----
export const BLUSH = { l: sprite(`
.R..R..R
R..R..R.`), r: sprite(`
.R..R..R
R..R..R.`) };
export const SWEAT = sprite(`
..v..
.vav.
vaabv
vbbbv
.vvv.`);
export const TEAR = sprite(`
.v.
vav
vbv
.v.`);
