// Round 1's target head (art direction on #529, art builder 2: docs/art-review/portrait/direction/round1-target-*.txt), cut into
// parts by layer: her face's skin and her neck (art builder 1's maps, maps/, draw the hair, hats and robe; the face's features
// are face.ts's).

import { sprite } from "../sprite";

/** Her face and its skin, in the head box (64 x 52; the box is 64 x 64, its middle at the face's). */
export const HEAD_SKIN = sprite(`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
...............................kk...............................
..............................kSSk..............................
..............................SSSS..............................
......................k......kSSSSk......k......................
.............k........Sk.....SSSSSS.....kS........k.............
.............S.......kSS.....SSSSSS.....SSk.......S.............
.............Sk......SSSk...kSSSSSSk...kSSS......kS.............
............kSSk....kSSSS...SSSSSSSS...SSSSk....kSSk............
............SSSS....SSSSSk.kSSSSSSSSk.kSSSSS....SSSS............
...........kSSSSk..kSSSSSSkSSSSSSSSSSkSSSSSSk..kSSSSk...........
...........SSSSSSkkSSSSSSSSSSSSSSSSSSSSSSSSSSkkSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
.............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.............
...........s.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.s...........
............sSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSs............
.............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.............
..............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..............
..............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..............
..............SSSSSSSSSSSSSSSSSSSkSSSSSSSSSSSSSSSS..............
..............KSSSSSSSSSSSSSSSSSkKSSSSSSSSSSSSSkkK..............
...............KSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSK...............
................KSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSK................
.................KSSSSSSSSSSSSSSSSSSSSSSSSSSSSK.................
..................KSSSSSSSSSSSSSSSSSSSSSSSSSSK..................
...................KSSSSSSSSSSSSSSSSSSSSSSSSK...................
.....................KSSSSSSSSSSSSSSSSSSSSK.....................
.......................KSSSSSSSSSSSSSSSSK.......................
.........................KSSSSSSSSSSSSK.........................
............................KSSSSSSK............................
`);
/** Her neck under the chin, at head-box row 52 (drawn under the collar). */
export const NECK = sprite(`
..........................KkkkkkkkkkkK..........................
..........................KkkkkkkkkkkK..........................
..........................KkkkkkkkkkkK..........................
..........................KkkkkkkkkkkK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
`);
