// Round 1's target head (art direction on #529, art builder 2: docs/art-review/portrait/direction/round1-target-*.txt), cut into
// parts by layer: her face's skin and her neck (art builder 1's maps, maps/, draw the hair, hats and robe; the face's features
// are face.ts's).

import { sprite } from "../sprite";

/** Her face and its skin (the forehead filled whole behind any fringe: art builder 1, round 4), in the head box (64 x 52; the box is 64 x 64, its middle at the face's). */
export const HEAD_SKIN = sprite(`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
..........................SSSSSSSSSSSS..........................
........................SSSSSSSSSSSSSSSS........................
......................SSSSSSSSSSSSSSSSSSSS......................
....................SSSSSSSSSSSSSSSSSSSSSSSS....................
...................SSSSSSSSSSSSSSSSSSSSSSSSSS...................
..................SSSSSSSSSSSSSSSSSSSSSSSSSSSS..................
.................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.................
................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS................
...............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...............
.............S.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.S.............
.............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.............
.............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.............
............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS............
............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS............
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........
.............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.............
...........s.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.s...........
............sSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSkk............
.............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSkk.............
..............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSkk..............
..............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSkk..............
..............SSSSSSSSSSSSSSSSSSSkSSSSSSSSSSSSSSkk..............
..............KSSSSSSSSSSSSSSSSSkkSSSSSSSSSSSSSkkK..............
...............KSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSkkK...............
................KSSSSSSSSSSSSSSSSSSSSSSSSSSSSkkK................
.................KSSSSSSSSSSSSSSSSSSSSSSSSSSkkK.................
..................KSSSSSSSSSSSSSSSSSSSSSSSSkkK..................
...................KSSSSSSSSSSSSSSSSSSSSSSkkK...................
.....................KSSSSSSSSSSSSSSSSSSkkK.....................
.......................KSSSSSSSSSSSSSSSkK.......................
.........................KSSSSSSSSSSSkK.........................
............................KSSSSSSK............................
`);
/** Her neck under the chin, at head-box row 52 (drawn under the collar). */
export const NECK = sprite(`
..........................KkkkkkkkkkkK..........................
..........................KkkkkkkkkkkK..........................
..........................KkkkkkkkkkkK..........................
..........................KkkkkkkkkkkK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
..........................KSSSSSSSSSSK..........................
`);
