// Bark faces (Ed, 2026-10-07, the eerie forest: "subtle faces in tree bark, at most TWO per area"): which trees wear one.
// Each area has two seeded anchor spots, away from its clearing (22 to 40 m from its middle, each its own direction); the
// tree of the area's own kind, on its own ground, nearest each anchor (within 20 m) wears the face, so an area has two at
// most and often fewer.
// Drawing only, from the map's seed: the same trees every run. Lazy: an anchor finds its tree the first time the view draws
// near it (its chunk generated by then), then keeps it; each tree's check is a numeric bucket lookup, no allocation.
import type { ForestMap } from "../rules/map";
import type { Plant as Tree } from "../rules/forest";
import { hash2 } from "../rules/random";

const BUCKET = 64, REACH = 20;
interface Anchor { x: number; z: number; cx: number; cy: number; type: number; chosen: number | null }

/** A tree's key: its spot to a quarter metre. */
export const treeKey = (x: number, z: number): number => Math.round(x * 4) * 1e7 + Math.round(z * 4);

export class BarkFaces {
  private buckets = new Map<number, Anchor[]>();
  private used = new Set<number>();
  constructor(private map: ForestMap, home?: readonly [number, number]) {
    for (const [cx, cy] of map.cells) {
      if (home && cx === home[0] && cy === home[1]) continue; // (home's ground is the party's own: no faces there)
      const s = map.siteOf(cx, cy), seed = map.seed;
      for (let k = 0; k < 2; k++) {
        const a = (hash2(cx, cy, seed + 731 + k * 17) + k * 0.5) * Math.PI * 2, d = 22 + 18 * hash2(cx, cy, seed + 733 + k * 17);
        const x = s.x + Math.cos(a) * d, z = s.z + Math.sin(a) * d, at = map.areaAt(x, z);
        if (at.cell[0] !== cx || at.cell[1] !== cy) continue; // (off its own ground: none from this anchor)
        const b = Math.floor(x / BUCKET) * 100003 + Math.floor(z / BUCKET), list = this.buckets.get(b) ?? [];
        list.push({ x, z, cx, cy, type: at.look, chosen: null }); this.buckets.set(b, list); // (its look: what a tree of its own kind carries as its type)
      }
    }
  }

  /** How many anchors there are (two an area at most). */
  get anchors(): number { let n = 0; for (const l of this.buckets.values()) n += l.length; return n; }

  /** Whether this tree wears a face; near(x, z, r) lists the trees round a spot (the forest's treesNear). */
  isFace(p: Tree, near: (x: number, z: number, r: number) => Iterable<Tree>): boolean {
    const key = treeKey(p.x, p.z), bx = Math.floor(p.x / BUCKET), bz = Math.floor(p.z / BUCKET);
    for (let i = -1; i <= 1; i++) for (let j = -1; j <= 1; j++) {
      const list = this.buckets.get((bx + i) * 100003 + bz + j);
      if (!list) continue;
      for (const A of list) {
        if ((A.x - p.x) ** 2 + (A.z - p.z) ** 2 > REACH * REACH) continue;
        if (A.chosen === null) { // its tree: the nearest of the area's own kind, not already another anchor's
          let best = -1, bd = Infinity;
          for (const q of near(A.x, A.z, REACH)) {
            if (q.type !== A.type) continue;
            const d = (q.x - A.x) ** 2 + (q.z - A.z) ** 2, k = treeKey(q.x, q.z);
            if (d >= bd || this.used.has(k)) continue;
            const c = this.map.areaAt(q.x, q.z).cell; if (c[0] !== A.cx || c[1] !== A.cy) continue; // (standing on its own area's ground: never a neighbour's third)
            bd = d; best = k;
          }
          A.chosen = best; if (best >= 0) this.used.add(best);
        }
        if (A.chosen === key) return true;
      }
    }
    return false;
  }
}
