// The jacket at the bust and the hat-tip hand, as hand-placed maps (art builder 1, round 2; docs/PORTRAIT-STYLE.md "Body").

import { rows, type PixMap } from "./pixmap";
import type { Look } from "../rig";
import { CLASSIC_SLIDERS } from "./hatClassic";

/** The jacket at the bust: sloped shoulders with armpit folds, a layered collar with its V and the top in it, shaded by form. Its anchor the neck pivot. */
export const ROBE_JACKET: PixMap = {
  anchor: [64, -2],
  rows: rows(String.raw`
........................................................xx...........xx.........................................................
...................................................xxxxxzx...........xzxxxxx....................................................
...................................................xXzzzzx...........xzzzzXx....................................................
...................................................xXzzzzx...........xzzzzXx....................................................
...................................................xXzzzzx...........xzzzzXx....................................................
...................................................xXzzzzx...........xzzzzXx....................................................
...................................................xXzzzZEEEEEEEEEEEEECzzzXx....................................................
...................................................xXzzCZEEEEEEEEEEEEECzzzXx....................................................
...................................................xXzCCZEEEEEEEEEEEEECzzzXx....................................................
...................................................xXCCCZZEEEEEEEEEEECCzzzXx....................................................
...................................................xCCCCCZAAAAAAAAAAACzzzzzx....................................................
.................................................xxXCCCCCZAAAAAAAAAAACzzzzzXxx..................................................
.............................................xxxxZzzXCCCCZAAAAAAAAAAACzzzzXzzCxxxx..............................................
.........................................xxxxZZZZZzzXCCCCCZAAAAAAAAACzzzzzXzzCCCCCxxxx..........................................
...............................xxxxxxxxxxZZZZZZZZCzzzXCCCCZAAAAAAAAACzzzzXzzzCCCCCCCCCxxxxxxxxxx................................
................xxxxxxxxxxxxxxxZZZZZZZZZZZZZZZCCCCCzzXCCCCZAAAAAAAAACzzzzXzzCCCCCCCCCCCCCCCCCCCCxxxxxxxxxxxxxxx.................
.............xxxZZZZZZZZZZZZZZZZZZZZZZZZZZCCCCCCCCCzzXCCCCZAAAAAAAAACzzzzXzzCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCxxx..............
...........xxZZZZZZZZZZZZZZZZZZZZZCCCCCCCCCCCCCCCCCCzzXCCCCZAAAAAAACzzzzXzzCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXCCCxx............
.........xxZZzzZZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzXCCCCZAAAAAAACzzzzXzzCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXCCxx..........
.......xxZZzzzCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzXCCCZAAAAAAACzzzXzzzCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXCCxx........
......xZZzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzXCCCZZAAAAACCzzzXzzCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXCCx.......
....xxZzzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzXCCCCZAAAAACzzzzXzzCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXCxx.....
...xZZzzzzzzzZZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzXCCCZAAAAACzzzXzzCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXCCx....
..xZzzzzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzXCCCZAAAAACzzzXzzCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXCx...
.xZzzzzzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzXCCCZAAACzzzXzzzCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXCx..
xZzzzzzzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzXCCCZAAACzzzXzzCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXCx.
ZzzzzzzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzXCCCZAAACzzzXzzCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXXCx
zzzzzXzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzXCCZAAACzzXzzCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXXC
zzzzzXXXzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzXCCCZACzzzXzzCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXXX
zzzzzzzXXzzZZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzCCCZACzzzzzzCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXXX
zzzzzzzzzXXZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXXX
zzzzzzzzzzXXXCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXXX
zzzzzzzzzzZZXXCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzXXXXXXXXXXXXXXX
XzzzzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCYCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXX
XXXzzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCYyyCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXX
zzXXzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCyCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXX
zzzzXXzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXX
zzzzzXXXzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXX
zzzzzzzXXZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXX
zzzzzzzzZZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXX
zzzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCYCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXX
zzzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCYyyCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXXX
zzzzzzzZZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCyCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXX
zzzzzzzZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCzzzzzzzzzzzzXXXXXXXXXXXX
`),
};

/** The hat-tip hand on the brim's right end (fingers over it, thumb under), its cuff and the sleeve out of frame. Its anchor the hat's brim centre (as drawn). */
export const HAND_HAT_TIP: PixMap = {
  anchor: [-26, 3],
  rows: rows(String.raw`
.KKKKKKKKKKKK.........................
.KSSSSSSSSSSSKK.......................
..KSSSSSSSSssSSK......................
.KSnnnnnnnnnnSSSK.....................
KSSSSssssssssSSSSK....................
.KSSSSSSSssssSSSSK....................
..KnnnnnnnnnnSSSSkK...................
.KSSSSSSSSSSSSSSSkK...................
..KKKKKKKKSSSSSSSkkK..................
..........KSSSSSSkkK..................
...........KSSSSSkkkK.................
...KKKKKKK.KSSSSSkkkK.................
...KSSSSSSKSSSSSSkkK..................
....KKKKnnkknSSSSkknx.................
........xmnnmnnSSnnzzx................
.......xmmmmmmmnnmCCzzx...............
.......xccccmmmmmmmmmzzx..............
.......xcccccccmmmmmmmmmx.............
........xcccccccccmmmmmmmx............
.........xcccccccccccmmmmx............
..........xzccccccccccccmmx...........
..........xzZZZccccccccccczx..........
..........xzZZZZZZcccccccCzzx.........
..........xzzZZZZZZZCcccCCCzzx........
...........xzzZZZZZZZCCCCCCCzzx.......
............xzZZZZZZZZCCCCCCCzzx......
.............xzZZZZZZZZCCCCCCCzx......
..............xzZZZZZZZCCCCCCCCzx.....
..............xzzZZZZZZZCCCCCCCzzx....
...............xzzZZZZZZZCCCCCCCzzx...
................xzzZZZZZZZCCCCCCCzzx..
.................xzzZZZZZZZCCCCCCCzzx.
..................xzZZZZZZZZCCCCCCCzx.
...................xzZZZZZZZCCCCCCCCzx
...................xzzZZZZZZZCCCCCCCCx
....................xzzZZZZZZZCCCCCCCx
.....................xzzZZZZZZZCCCCCCx
......................xzzZZZZZZZCCCCCx
.......................xzZZZZZZZZCCCCx
........................xzZZZZZZZZCCCx
.........................xzZZZZZZZCCCx
.........................xzzZZZZZZZCCx
..........................xzzZZZZZZZCx
...........................xzzZZZZZZZx
............................xzzZZZZZZx
.............................xzZZZZZZx
..............................xzZZZZZx
..............................xzzZZZZx
...............................xzzZZZx
................................xzzZZx
.................................xzzZx
..................................xzzx
...................................xzx
....................................xx
....................................xx
.....................................x
`),
};

/** The hat-tip hand for a hat with the creator's brim: it holds the brim's right end, so it moves out (or in) with the brim. */
export function handHatTip(l: Pick<Look, "hatBrim">): PixMap {
  const k = Math.max(-(CLASSIC_SLIDERS.brimRight[1] - CLASSIC_SLIDERS.brimRight[0]), Math.round((l.hatBrim - 1) * 12));
  return { ...HAND_HAT_TIP, anchor: [HAND_HAT_TIP.anchor[0] - k, HAND_HAT_TIP.anchor[1]] };
}
