// The jacket at the bust and the hat-tip hand, as hand-placed maps (art builder 1, round 2; docs/PORTRAIT-STYLE.md "Body").

import { BASE, DEEP, LIGHT, MAT, SHADE } from "../palette";
import { OUTLINE, rows, type PixMap } from "./pixmap";
import type { Look } from "../rig";
import { CLASSIC_SLIDERS } from "./hatClassic";

export const ROBE_LEGEND = {
  X: [MAT.JACKET, OUTLINE], N: [MAT.JACKET, DEEP], n: [MAT.JACKET, SHADE], J: [MAT.JACKET, BASE], j: [MAT.JACKET, LIGHT],
  T: [MAT.TOP, BASE], t: [MAT.TOP, SHADE], G: [MAT.GOLD, BASE], g: [MAT.GOLD, SHADE],
} as const;
export const HAND_LEGEND = {
  ...ROBE_LEGEND, O: [MAT.SKIN, OUTLINE], K: [MAT.SKIN, DEEP], k: [MAT.SKIN, SHADE], S: [MAT.SKIN, BASE], s: [MAT.SKIN, LIGHT],
  C: [MAT.TRIM, BASE], c: [MAT.TRIM, SHADE],
} as const;

/** The jacket at the bust: sloped shoulders with armpit folds, a layered collar with its V and the top in it, shaded by form. Its anchor the neck pivot. */
export const ROBE_JACKET: PixMap = {
  anchor: [47, -2],
  legend: ROBE_LEGEND,
  rows: rows(String.raw`
.......................................XX...........XX.......................................
..................................XXXXXnX...........XnXXXXX..................................
..................................XNnnnnX...........XnnnnNX..................................
..................................XNnnnnX...........XnnnnNX..................................
..................................XNnnnnX...........XnnnnNX..................................
..................................XNnnnntttttttttttttnnnnNX..................................
..................................XNnnJjtttttttttttttJnnnNX..................................
..................................XJJJJjtttttttttttttJnnnnX..................................
.................................XJJJJJjtttttttttttttJnnnnnX.................................
..............................XXXnNJJJJjjtttttttttttJJnnnnNnXXX..............................
............................XXjjnnNJJJJJjTTTTTTTTTTTJnnnnnNnnJJXX............................
.........................XXXjjjjnnNJJJJJjTTTTTTTTTTTJnnnnnNnnJJJJXXX.........................
.......................XXjjjjjjJJnnNJJJJjTTTTTTTTTTTJnnnnNnnJJJJJJJJXX.......................
....................XXXjjjjjJJJJJnnNJJJJJjTTTTTTTTTJnnnnnNnnJJJJJJJJJJXXX....................
..................XXjjjjjjJJJJJJJnnnNJJJJjTTTTTTTTTJnnnnNnnnJJJJJJJJJJJJJXX..................
...............XXXjjjjjJJJJJJJJJJJnnNJJJJjTTTTTTTTTJnnnnNnnJJJJJJJJJJJJJJJJXXX...............
.............XXjjjjjjJJJJJJJJJJJJJnnNJJJJjTTTTTTTTTJnnnnNnnJJJJJJJJJJJJJJJJJJJXX.............
...........XXjjjjjJJJJJJJJJJJJJJJJJnnNJJJJjTTTTTTTJnnnnNnnJJJJJJJJJJJJJJJJJJJJJJXX...........
..........XjjjjjJJJJJJJJJJJJJJJJJJJnnNJJJJjTTTTTTTJnnnnNnnJJJJJJJJJJJJJJJJJJJJnnJJX..........
........XXjjjJJJJJJJJJJJJJJJJJJJJJJnnnNJJJjTTTTTTTJnnnNnnnJJJJJJJJJJJJJJJJJJJJnnnnJXX........
.......XjjjJJJJJJJJJJJJJJJJJJJJJJJJJnnNJJJjjTTTTTJJnnnNnnJJJJJJJJJJJJJJJJJJJJJnnnnnJJX.......
.......XjjJJJJJJJJJJJJJJJJJJJJJJJJJJnnNJJJJjTTTTTJnnnnNnnJJJJJJJJJJJJJJJJJJJJJnnnnnnnX.......
......XjjJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnNJJJjTTTTTJnnnNnnJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnX......
.....XjjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnNJJJjTTTTTJnnnNnnJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnJX.....
....XjnjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnnNJJJjTTTJnnnNnnnJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnnJX....
....XnnjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnNJJJjTTTJnnnNnnJJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnnnX....
...XnnnjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnNJJJjTTTJnnnNnnJJJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnnnX...
...XnnnjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnNJJjTTTJnnNnnJJJJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnnnX...
..XnnnnjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnNJJJjTJnnnNnnJJJJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnnnnX..
..XnnnjjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnnJJJjTJnnnnnnJJJJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnnnnX..
.XnnnnjjNNJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnnNNnnnnnNX.
.XnnnnjJJNNNJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJNNNnnnnnnNX.
XnnnnnjJJJJNNJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJNNnnnnnnnnNNX
XnnnnnjJJJJJJNNJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJGJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJNNJnnnnnnnnnNNX
XnnnnnjJJJJJJJNNJJJJJJJJJJJJJJJJJJJJJJJJJJJJJGggJJJJJJJJJJJJJJJJJJJJJJJJJJJJJNNJJnnnnnnnnnNNX
XnnnNNjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJgJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnnnnNNnNNX
XnnnnNNNJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnnNNNnnNNX
XnnnnjjNNJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnNNnnnnNNX
XnnnnjjJJNNJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJNNnnnnnnNNX
XnnnnjJJJJNNJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJNNnnnnnnnNNX
XnnnnjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJGJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnNNX
XnnnnjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJGggJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnNNX
XnnnnjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJgJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnNNX
XnnnnjJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnnnnnnnNNX
`),
};

/** The hat-tip hand on the brim's right end (fingers over it, thumb under), its cuff and the sleeve out of frame. Its anchor the hat's brim centre (as drawn). */
export const HAND_HAT_TIP: PixMap = {
  anchor: [-26, 3],
  legend: HAND_LEGEND,
  rows: rows(String.raw`
.OOOOOOOOOOOO.........................
.OSSSSSSSSSSSOO.......................
..OSSSSSSSSssSSO......................
.OSKKKKKKKKKKSSSO.....................
OSSSSssssssssSSSSO....................
.OSSSSSSSssssSSSSO....................
..OKKKKKKKKKKSSSSkO...................
.OSSSSSSSSSSSSSSSkO...................
..OOOOOOOOSSSSSSSkkO..................
..........OSSSSSSkkO..................
...........OSSSSSkkkO.................
...OOOOOOO.OSSSSSkkkO.................
...OSSSSSSOSSSSSSkkO..................
....OOOOKKkkKSSSSkkO..................
........XCKKCKKSSKO...................
.......XCCCCCCCKKX....................
.......XccccCCCCCCXXX.................
.......XcccccccCCCCCCXXX..............
........XcccccccccCCCCCCX.............
.........XXXcccccccccCCCCX............
............XXXcccccccccCX............
...............XcccccccccX............
..............XJJJcccccccNX...........
.............XjJJJJJJcccnNNX..........
.............XjJJJJJJJJnnnNNX.........
..............XjJJJJJJJnnnnNNX........
...............XjJJJJJJJnnnnNNX.......
...............XjJJJJJJJJnnnnNNX......
................XjJJJJJJJJnnnnNNX.....
.................XjJJJJJJJJnnnnNNX....
..................XJJJJJJJJJnnnnNNX...
..................XjJJJJJJJJJnnnnNNX..
...................XjJJJJJJJJnnnnnNNX.
....................XJJJJJJJJJnnnnnNNX
....................XjJJJJJJJJJnnnnNNX
.....................XjJJJJJJJJJnnnnNX
......................XjJJJJJJJJJnnnnX
......................XjJJJJJJJJJJnnnX
.......................XjJJJJJJJJJnnnX
........................XjJJJJJJJJJnnX
........................XjJJJJJJJJJJnX
.........................XjJJJJJJJJJJX
..........................XjJJJJJJJJJX
..........................XjJJJJJJJJJX
...........................XjJJJJJJJJX
............................XjJJJJJJJX
............................XjJJJJJJJX
.............................XjJJJJJJX
..............................XjJJJJJX
..............................XjJJJJJX
...............................XjJJJJX
................................XjJJJX
................................XjJJJX
.................................XjJJX
..................................XjJX
...................................XJX
...................................XjX
....................................XX
.....................................X
.....................................X
`),
};

/** The hat-tip hand for a hat with the creator's brim: it holds the brim's right end, so it moves out (or in) with the brim. */
export function handHatTip(l: Pick<Look, "hatBrim">): PixMap {
  const k = Math.max(-(CLASSIC_SLIDERS.brimRight[1] - CLASSIC_SLIDERS.brimRight[0]), Math.round((l.hatBrim - 1) * 12));
  return { ...HAND_HAT_TIP, anchor: [HAND_HAT_TIP.anchor[0] - k, HAND_HAT_TIP.anchor[1]] };
}
