// The other hair styles as hand-placed maps (art builder 1, round 2), drawn like the long hair (hairLong.ts) and in its four
// layers: the bob (locks to her jaw), the buns (a coiled knot each side of her head, short locks), and the mohawk (no fringe,
// her head shaved, the crest standing up along the middle: with her hat on, only her bare forehead shows under the brim).

import { HAIR_LEGEND, HAIR_LONG_BACK, HAIR_LONG_CROWN, HAIR_LONG_FRONT, HAIR_LONG_HAT_SHADOW } from "./hairLong";
import { rows, type PixMap } from "./pixmap";

/** bob: back. */
export const HAIR_BOB_BACK: PixMap = {
  anchor: [27, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
oHHH..............................................HHHo
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
.....DDD......................................DDD.....
.....D..........................................D.....
.....DD........................................DD.....
.....DDd......................................DDD.....
.....DdDD....................................DDDd.....
.....DdDD....................................DDDd.....
.....DdDD....................................DDDd.....
.....dDDD....................................DDdD.....
.....dDDDD..................................DDDdD.....
.....dDDDDD................................DDDDdD.....
.....DDDDDDd..............................DDDDdDD.....
.....DDDDDDdD............................DDDDDdDD.....
.....oDDDDDdDD..........................DDDDDDdDo.....
.....oDDDDdDDDDD......................dDDDDDDdDDo.....
.....oDDDDdDDDDDDd..................DDdDDDDDDdDDo.....
.....oDDDDdDDDDDDdDD..............DDDDdDDDDDDdDDo.....
.....oDDDdDDDDDDdDDDDDD........DDDDDDdDDDDDDdDDDo.....
.....oDDDdDDDDDDdDDDD............DDDDdDDDDDDdDDDo.....
.....oDDDdDDDDDDdDDDD............DDDDdDDDDDDdDDDo.....
.....oDDdDDDDDDdDDDDD............DDDdDDDDDDdDDDDo.....
.....oDDdDDDDDDdDDDDD............DDDdDDDDDDdDDDDo.....
.....oDDdooDDDDdDDooD............DDDooDDDDDdDooDo.....
.....oDdo..oDDdDDo..o............DDo..oDDDdDo..oo.....
.....oDo....oDdDo................Do....oDDdo....o.....
.....ooo.....oooo................oo.....ooo...........
`),
};

/** bob: front. */
export const HAIR_BOB_FRONT: PixMap = {
  anchor: [29, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
......HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH......
.ohHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDHo.
.ohHHHhhHHHHHdhHHHHHdhHHHHHdhHHHHHdhHHHHHdhhHHHHHDDdDDDHo.
.ohHHHhhHHHHHdhHHHHHdhHHHHHdhHHHHHdhhHHHHdhhHHHHHDDdDDDHo.
.ohHHHhhHHHHHdhHHHHHdhHHHHHdhHHHHHdhhHHHHDdhHHHHHDDdDDDHo.
.ohHHHhhHHHHDdhHHHHHdhhHHHDdhhHHHHdhhHHHHDdhhHHHHDDdDDDHo.
.ohHHHhhHHHHDdhHHHHHdhhHHHDdhhHHHHDdhHHHHDDkhHHHHDDdDDDHo.
.ohHHHDhHHHHDdhHHHHDdHHHHHDdhhHHHHDdhhHHHDD.HHHHDDddDDDHo.
.ohHHHDHHHHDDkhhHHHDDkHHHDDkkhHHHHDDkHHHDDD.kHHHDDddDDDHo.
.ohHHHDHHHDDD.hhHHHDD.HHHDD..HHHHHDk.HHHDDk..kHHDDddDDDHo.
.ohHHHDHHHDDk.HHHHHDk.kHDDk..HHHDDD..kHHDD....kHDkddDDDHo.
.ohHHHDDHDDk..kHHDDD...HDk...kHHDDD...kHDD.....kH.ddDDDHo.
.ohHHHDDHDD....HHDDD...kD.....HHDDk....kDk......k.ddDDDHo.
.ohHHHDDHDk....HHDDk....k.....kHDD......H.........ddDDDHo.
.ohHHHDDHk.....HHDD............HDD......k.........ddDDDHo.
.ohHHHDDk......kHDk............kDk................ddDDDHo.
.ohdHHDD........HD..............H.................ddDDdHo.
.ohdHHDD........Hk..............k.................ddDDdHo.
.ohdHHDD........k.................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohhHHHHDD......................................ddDDDDHHo.
ohHHHHDD..........................................ddDDDDHo
ohhHHHHDD........................................ddDDDDHHo
ohhdHHHHDD......................................ddDDDDdHHo
ohhdHHHHDD......................................ddDDDDdHHo
ohhdHHdHDD......................................ddDdDDdHHo
ohhdHHdHDD......................................ddDdDDdHHo
ohhdHHdHDD......................................ddDdDDdHHo
ohhdHHdHDD......................................ddDdDDdHHo
ohhdHHdHDD......................................ddDdDDdHHo
ohhdHHdHDD......................................ddDdDDdHHo
ohhdHHoHDD......................................ddDoDDdHHo
ohhdHo.oD........................................do.oDdHHo
.ohdHo.oD........................................do.oDdHo.
.ohoHo.oD........................................do.oDoHo.
.oo.oo..............................................oo.oo.
....oo..............................................oo....
....oo..............................................oo....
`),
};

/** bob: crown. */
export const HAIR_BOB_CROWN: PixMap = {
  anchor: [29, 39],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
......................ooooooooooooo......................
..................ooooHHHdHHHHHHHHHoooo..................
...............oooHHHdddddddddHHHHHHHHHooo...............
.............ooHHdddddddddddddd+ddHHHHHHHHoo.............
...........oodddddHHH+dddHddddHHHdddddHHHHHDoo...........
.........oodddHHHHHddHdddHdddHddHHHHHdddddHDDDoo.........
........odhhhHHHHHddHddhhhhhhhhhhhHHHHHHHddddDDDo........
.......ohhhhhH+HddHhhhhhhhhhhhhhhhhhhhHHHHHDDddddo.......
......ohhhhhhHHddhhhhhhhhhHdHHdhhhhhhhhhHHHDDDDDddo......
.....ohhhhhhhddhhhhhhhddHHHddHHdHHHhhhhhhhHDDDDDDDDo.....
....ohhhhhhdddhhhhhdHHdHHHHHdHHddHHHHdhhhhhDDDDDDDDDo....
...ohhhhhhddhhhhhddHHHdHHHHHdHHHddHHHHHdhhHDDDDDDDDDDo...
..ohhhhhdddhhhhhHdHHHddHHHHHddHHHdHHHHHHdddDDDDDDDDDDDo..
..ohhhhddhhhhhhHdHHHHdHHHHHHHHHHHHdHHHHHHHddDDDDDDDDDDo..
.ohhhdddhhhhhHHddHHHHHHHHHHHHHHHHHHHHHHHHHHdddDDDDDDDDDo.
.ohhddhhhhhhhHddHHHHHHHHHHHHHHHHHHHHHHHHHHHDDddDDDDDDDDo.
.odddhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDdddDDDDDDo.
oddhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDddDDDDDDo
ohhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDddDDDDo
ohhhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDDddDDDo
hhhhhhhhhhddhHHHHHHHHHHHHHHHHHHHHHHHHHHHdHHDDDDDDDDDDddDD
`),
};

/** bob: hat shadow. */
export const HAIR_BOB_HAT_SHADOW: PixMap = {
  anchor: [28, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
.oDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDo.
oHDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdddDo
oHDDDHHDDDDDdHDDDDDdHDDDDDdHDDDDDdHDDDDDdHHDDDDDddddddDo
`),
};

/** buns: back. */
export const HAIR_BUNS_BACK: PixMap = {
  anchor: [38, 23],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
.......h...........................................................H.......
....hhhhhHH.....................................................HHHHHDD....
..oddhhhdHHHdHH..............................................HHddHHHdDDDo..
.ohhhhhHHddHHd...............................................dHHHHHDDddDDo.
.ohhhddHHHdHHd...............................................HHHHddDDDdDDo.
ohhddHHHdHHdHHd.............................................dHHddDDDdDDdDDo
ohdhHHHHHHHdHHd.............................................HHdHDDDDDDDdDDo
ohdHHdHHHHHdHDd.............................................HHdDDdDDDDDdDdo
ohdHHdHHHHdHDdD.............................................HHdDDdDDDDdDddo
oHdHHHHHHddDDdD.............................................HDdDDDDDDdddddo
oHdHHdHHHHDDdDD.............................................DDdDDdDDDDddddo
.odHHHdHHDDdDD...............................................DdDDDdDDddddo.
.oHdHHHddddDDD...............................................DDdDDDddddddo.
..oodHHDDDDDD.................................................DDdDDddddoo..
....oooDooD.....................................................Ddodooo....
.......o...........................................................o.......
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
................DDD......................................DDD...............
................D..........................................D...............
................DD........................................DD...............
................DDd......................................DDD...............
................DdDD....................................DDDd...............
................DdDD....................................DDDd...............
................odDD....................................DDDo...............
................oDDD....................................DDdo...............
................oDDDD..................................DDDdo...............
................oDDDDD................................DDDDdo...............
................oDDDDDd..............................DDDDdDo...............
................oDDDDDdD............................DDDDDdDo...............
................oDDDDDdDD..........................DDDDDDdDo...............
................oDDDDdDDDDD......................dDDDDDDdDDo...............
................oDDDDdDDDDDDd..................DDdDDDDDDdDDo...............
................oDDDDdDDDDDDdDD..............DDDDdDDDDDDdDDo...............
................oDDDdDDDDDDdDDDDDD........DDDDDDdDDDDDDdDDDo...............
................oDDDooDDDDDdDooD............DDDooDDDDDDdooDo...............
................oDDo..oDDDDdo..o............DDo..oDDDDDo..oo...............
................oDo....oDDdo................Do....oDDDo....o...............
................oDo.....oDdo................Do.....oDo.....................
................oo.......oo.................o.......oo.....................
`),
};

/** buns: front. */
export const HAIR_BUNS_FRONT: PixMap = {
  anchor: [29, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
......HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH......
.hhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDHH.
.hhHHHhhHHHHHdhHHHHHdhHHHHHdhHHHHHdhHHHHHdhhHHHHHDDdDDDHH.
.hhHHHhhHHHHHdhHHHHHdhHHHHHdhHHHHHdhhHHHHdhhHHHHHDDdDDDHH.
.hhHHHhhHHHHHdhHHHHHdhHHHHHdhHHHHHdhhHHHHDdhHHHHHDDdDDDHH.
.hhHHHhhHHHHDdhHHHHHdhhHHHDdhhHHHHdhhHHHHDdhhHHHHDDdDDDHH.
.hhHHHhhHHHHDdhHHHHHdhhHHHDdhhHHHHDdhHHHHDDkhHHHHDDdDDDHH.
.hhHHHDhHHHHDdhHHHHDdHHHHHDdhhHHHHDdhhHHHDD.HHHHDDddDDDHH.
.hhHHHDHHHHDDkhhHHHDDkHHHDDkkhHHHHDDkHHHDDD.kHHHDDddDDDHH.
.hhHHHDHHHDDD.hhHHHDD.HHHDD..HHHHHDk.HHHDDk..kHHDDddDDDHH.
.hhHHHDHHHDDk.HHHHHDk.kHDDk..HHHDDD..kHHDD....kHDkddDDDHH.
.hhHHHDDHDDk..kHHDDD...HDk...kHHDDD...kHDD.....kH.ddDDDHH.
.hhHHHDDHDD....HHDDD...kD.....HHDDk....kDk......k.ddDDDHH.
.ohHHHDDHDk....HHDDk....k.....kHDD......H.........ddDDDHo.
.ohHHHDDHk.....HHDD............HDD......k.........ddDDDHo.
.ohHHHDDk......kHDk............kDk................ddDDDHo.
.ohdHHDD........HD..............H.................ddDDdHo.
.ohdHHDD........Hk..............k.................ddDDdHo.
.ohdHHDD........k.................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohdHHDD..........................................ddDDdHo.
.ohhHHHHDD......................................ddDDDDHHo.
ohHHHHDD..........................................ddDDDDHo
ohhHHHHDD........................................ddDDDDHHo
ohhdHHHHDD......................................ddDDDDdHHo
ohhdHHHHDD......................................ddDDDDdHHo
ohhdHHoHDD......................................ddDoDDdHHo
.ohdHo.oD........................................do.oDdHo.
.ohoHo.oD........................................do.oDoHo.
.oo.oo.oD........................................do.oo.oo.
....oo..............................................oo....
....oo..............................................oo....
`),
};

/** buns: crown. */
export const HAIR_BUNS_CROWN: PixMap = {
  anchor: [29, 39],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
......................ooooooooooooo......................
..................ooooHHHdHHHHHHHHHoooo..................
...............oooHHHdddddddddHHHHHHHHHooo...............
.............ooHHdddddddddddddd+ddHHHHHHHHoo.............
...........oodddddHHH+dddHddddHHHdddddHHHHHDoo...........
.........oodddHHHHHddHdddHdddHddHHHHHdddddHDDDoo.........
........odhhhHHHHHddHddhhhhhhhhhhhHHHHHHHddddDDDo........
.......ohhhhhH+HddHhhhhhhhhhhhhhhhhhhhHHHHHDDddddo.......
......ohhhhhhHHddhhhhhhhhhHdHHdhhhhhhhhhHHHDDDDDddo......
.....ohhhhhhhddhhhhhhhddHHHddHHdHHHhhhhhhhHDDDDDDDDo.....
....ohhhhhhdddhhhhhdHHdHHHHHdHHddHHHHdhhhhhDDDDDDDDDo....
...ohhhhhhddhhhhhddHHHdHHHHHdHHHddHHHHHdhhHDDDDDDDDDDo...
..ohhhhhdddhhhhhHdHHHddHHHHHddHHHdHHHHHHdddDDDDDDDDDDDo..
..ohhhhddhhhhhhHdHHHHdHHHHHHHHHHHHdHHHHHHHddDDDDDDDDDDo..
.ohhhdddhhhhhHHddHHHHHHHHHHHHHHHHHHHHHHHHHHdddDDDDDDDDDo.
.ohhddhhhhhhhHddHHHHHHHHHHHHHHHHHHHHHHHHHHHDDddDDDDDDDDo.
.odddhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDdddDDDDDDo.
oddhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDddDDDDDDo
dhhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDddDDDDD
hhhhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDDddDDDD
hhhhhhhhhhddhHHHHHHHHHHHHHHHHHHHHHHHHHHHdHHDDDDDDDDDDddDD
`),
};

/** buns: hat shadow. */
export const HAIR_BUNS_HAT_SHADOW: PixMap = {
  anchor: [37, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
.oddHHHdDDDdDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDddDDDddddo.
oHHHHHDDdHHDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdddDDDddddddo
oHHHddDDDHHDDDHHDDDDDdHDDDDDdHDDDDDdHDDDDDdHDDDDDdHHDDDDDddddddDDdddddddo
`),
};

/** mohawk: back. */
export const HAIR_MOHAWK_BACK: PixMap = {
  anchor: [22, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
KSSSSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSkkkkkK
KSSSSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSkkkkkK
..SSSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSkkkkk.
..ssssssSSSSSSSSSSSSS..SSSSSSSSSSSSSSkkkkk.
..ssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkk.
..ssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkk.
..ssssssSSSS.SSSSSS......SSSSSS.SSSSSkkkkk.
..s.ssssSSSS..SSSSS......SSSSS..SSSSSkkk.k.
..s.ssssSSS...SSSSS......SSSSS...SSSSkkk.k.
..s..sssSSS....SSS........SSS....SSSSkk..k.
......ssSS.....SSS........SSS.....SSSk.....
......ssSS......S..........S......SSSk.....
.......sS..........................SS......
`),
};

/** mohawk: front. */
export const HAIR_MOHAWK_FRONT: PixMap = {
  anchor: [22, 19],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
.o........................................o.
.o........................................o.
`),
};

/** mohawk: crown. */
export const HAIR_MOHAWK_CROWN: PixMap = {
  anchor: [22, 60],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
.....................o.....................
.....................o.....................
.....................o.....................
.....................o.....................
.....................o.....................
.................o...o...o.................
.................o..oHo..o.................
.................o..oHo..o.................
.................oo.oHo.oo.................
.................oo.oHo.oo.................
................oho.oHo.oDo................
................oho.oHo.oDo................
................ohhodHHoDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhHHHHDDo................
.............KKKhhhhHHHHDDDKKK.............
...........KKSSShhhhHHHHDDDSSSKK...........
.........KKSSSSShhhhHHHHDDDSSSSkKK.........
.......KKssSSSSShhhhHHHHDDDSSSSkkkKK.......
......KssssSSSSShhhhHHHHDDDSSSSkkkkkK......
.....KsssssSSSSShhhhHHHHDDDSSSSkkkkkkK.....
....KssssssSSSSShhhhHHHHDDDSSSSkkkkkkkK....
...KsssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkK...
...KsssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkK...
..KssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkK..
.KsssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkK.
.KsssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkK.
.KsssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkK.
KssssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkkK
KssssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkkK
KssssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkkK
sssssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkkk
`),
};

/** mohawk: hat shadow. */
export const HAIR_MOHAWK_HAT_SHADOW: PixMap = {
  anchor: [22, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
KSSSSSSSSSSSSSSSDDDDDDDDDDDSSSSSSSSSSkkkkkK.
KSSSSSSSSSSSSSSSDDDDDDDDDDDSSSSSSSSSSkkkkkK.
oDSSSSSSSSSSSSSSDDDDDDDDDDDSSSSSSSSSSkkkkkdo
`),
};


/** Every hair style's four layers by the creator's names (back, front, crown with the hat off, the brim's shadow with it on). */
export interface HairMaps { back: PixMap; front: PixMap; crown: PixMap; hatShadow: PixMap }
export const HAIR_MAPS: Record<string, HairMaps> = {
  long: { back: HAIR_LONG_BACK, front: HAIR_LONG_FRONT, crown: HAIR_LONG_CROWN, hatShadow: HAIR_LONG_HAT_SHADOW },
  bob: { back: HAIR_BOB_BACK, front: HAIR_BOB_FRONT, crown: HAIR_BOB_CROWN, hatShadow: HAIR_BOB_HAT_SHADOW },
  buns: { back: HAIR_BUNS_BACK, front: HAIR_BUNS_FRONT, crown: HAIR_BUNS_CROWN, hatShadow: HAIR_BUNS_HAT_SHADOW },
  mohawk: { back: HAIR_MOHAWK_BACK, front: HAIR_MOHAWK_FRONT, crown: HAIR_MOHAWK_CROWN, hatShadow: HAIR_MOHAWK_HAT_SHADOW },
};
