// The other hair styles as hand-placed maps (art builder 1, round 2), drawn like the long hair (hairLong.ts) and in its four
// layers: the bob (locks to her jaw), the buns (a coiled knot each side of her head, short locks), and the mohawk (no fringe,
// her head shaved, the crest standing up along the middle: with her hat on, only her bare forehead shows under the brim).

import { HAIR_LEGEND, HAIR_LONG_BACK, HAIR_LONG_CROWN, HAIR_LONG_FRONT, HAIR_LONG_HAT_SHADOW } from "./hairLong";
import { rows, type PixMap } from "./pixmap";

/** bob: back. */
export const HAIR_BOB_BACK: PixMap = {
  anchor: [27, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
oHHH..............................................HHHo
......................................................
......................................................
......sssssssSSSSSSSSSSSSS..SSSSSSSSSSSSSSkkkkkk......
......sssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkkk......
......sssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkkk......
......sssssssSSSS.SSSSSS......SSSSSS.SSSSSkkkkkk......
......ss.ssssSSSS..SSSSS......SSSSS..SSSSSkkk.kk......
......ss.ssssSSS...SSSSS......SSSSS...SSSSkkk.kk......
......ss..sssSSS....SSS........SSS....SSSSkk..kk......
......s....ssSS.....SSS........SSS.....SSSk....k......
......s....ssSS......S..........S......SSSk....k......
............sS..........................SS............
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
.....DDD......................................DDD.....
.....D..........................................D.....
.....DD........................................DD.....
.....DDd......................................DDD.....
.....DdDD....................................DDDd.....
.....DdDD....................................DDDd.....
.....DdDD....................................DDDd.....
.....dDDD....................................DDdD.....
.....dDDDD..................................DDDdD.....
.....dDDDDD................................DDDDdD.....
.....DDDDDDd..............................DDDDdDD.....
.....DDDDDDdD............................DDDDDdDD.....
.....DDDDDDdDD..........................DDDDDDdDD.....
.....oDDDDdDDDDD......................dDDDDDDdDDo.....
.....oDDDDdDDDDDDd..................DDdDDDDDDdDDo.....
.....oDDDDdDDDDDDdDD..............DDDDdDDDDDDdDDo.....
.....oDDDdDDDDDDdDDDDDD........DDDDDDdDDDDDDdDDDo.....
.....oDDDdDDDDDDdDDDD............DDDDdDDDDDDdDDDo.....
.....oDDDdDDDDDDdDDDD............DDDDdDDDDDDdDDDo.....
.....oDDdDDDDDDdDDDDD............DDDdDDDDDDdDDDDo.....
.....oDDdDDDDDDdDDDDD............DDDdDDDDDDdDDDDo.....
.....oDDdooDDDDdDDooD............DDDooDDDDDdDooDo.....
.....oDdo..oDDdDDo..o............DDo..oDDDdDo..oo.....
.....oDo....oDdDo................Do....oDDdo....o.....
.....ooo.....oooo................oo.....ooo...........
`),
};

/** bob: front. */
export const HAIR_BOB_FRONT: PixMap = {
  anchor: [31, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
...ohHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDHo...
...ohHHHhhHHHHHHdHHdhhHHHHHHDdHHHdHHHHHHHHHDDdHHHHHDDdDDDHo...
...ohHHHhhHHHHHHdHHdhhHHHHHHDdHHHdHHHHHHHHHDDdHHHHHDDdDDDHo...
...ohHHHhhHHHHHDdHHdhhHHHHHHDdHHHdHHHHHHHHHDDdHHHHHDDdDDDHo...
...ohHHHhhHHHHHDdHHdhhHHHHHHDdHHHdHHHHHHHHHDDkHHHHHDDdDDDHo...
...ohHHHhhHHHHHDdHDdhhHHHHHHDDkHHHdHHHHHHHDDD.kHHHHDDdDDDHo...
...ohHHHDhHHHHDDkkDdhhHHHHHHDD.HHHdHHHHHHHDDD..HHHDDddDDDHo...
...ohHHHDHHHHHDD..HkhhHHHHHDDD.kHHdHHHHHHHDDk..kHHDDddDDDHo...
...ohHHHDHHHDDDk..H.khhHHHHDDk..kHHHHHHHHDDk....kHDDddDDDHo...
...ohHHHDHHHDDk...k..HHHHHHDD....kHHHHHHDDD......kHkddDDDHo...
..ohHHHHDHHDDk.......HHHHDDDk.....kDHHHDDDk.......k.ddDDDDHo..
..ohHHHHDHHDk........kHHHDDD.......HHHHDDk..........ddDDDDHo..
..ohHHHHDDDD..........HHHDDk.......kHHHDD...........ddDDDDHo..
.ohhHHHHDDDk..........HHHDD.........kHDDk...........ddDDDDHHo.
.ohhHHHHDDk...........kHDDk..........HDk............ddDDDDHHo.
.ohhHHHHDD.............HDk...........Hk.............ddDDDDHHo.
.ohhHHHHDD.............kD............k..............ddDDDDHHo.
ohhdHHHHDD..............k...........................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhhdHHHHDDD......................................dddDDDDdHHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhHHHHHDDD........................................dddDDDDDHHo
ohhhdHHHHDDD......................................dddDDDDdHHHo
.ohhHHHHHDDD......................................dddDDDDDHHo.
.ohhHHHHdDDD......................................ddddDDDDHHo.
.ohhHHHHdDDD......................................ddddDDDDHHo.
.ohhHHHHdDDD......................................ddddDDDDHHo.
..ohhdHHdHDD......................................ddDdDDdHHo..
..ohhdHHdHDD......................................ddDdDDdHHo..
..ohhdHHdHDD......................................ddDdDDdHHo..
..ohhdHHdHDD......................................ddDdDDdHHo..
...ohhHHoHD........................................dDoDDHHo...
...ohdHo.oD........................................do.oDdHo...
...ohoHo.oD........................................do.oDoHo...
...oo.oo..............................................oo.oo...
...o.oHo..............................................oDo.o...
......oo..............................................oo......
`),
};

/** bob: crown. */
export const HAIR_BOB_CROWN: PixMap = {
  anchor: [29, 39],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
......................ooooooooooooo......................
..................ooooHHHdHHHHHHHHHoooo..................
...............oooHHHdddddddddHHHHHHHHHooo...............
.............ooHHdddddddddddddd+ddHHHHHHHHoo.............
...........oodddddHHH+dddHddddHHHdddddHHHHHDoo...........
.........oodddHHHHHddHdddHdddHddHHHHHdddddHDDDoo.........
........odhhhHHHHHddHddhhhhhhhhhhhHHHHHHHddddDDDo........
.......ohhhhhH+HddHhhhhhhhhhhhhhhhhhhhHHHHHDDddddo.......
......ohhhhhhHHddhhhhhhhhhHdHHdhhhhhhhhhHHHDDDDDddo......
.....ohhhhhhhddhhhhhhhddHHHddHHdHHHhhhhhhhHDDDDDDDDo.....
....ohhhhhhdddhhhhhdHHdHHHHHdHHddHHHHdhhhhhDDDDDDDDDo....
...ohhhhhhddhhhhhddHHHdHHHHHdHHHddHHHHHdhhHDDDDDDDDDDo...
..ohhhhhdddhhhhhHdHHHddHHHHHddHHHdHHHHHHdddDDDDDDDDDDDo..
..ohhhhddhhhhhhHdHHHHdHHHHHHHHHHHHdHHHHHHHddDDDDDDDDDDo..
.ohhhdddhhhhhHHddHHHHHHHHHHHHHHHHHHHHHHHHHHdddDDDDDDDDDo.
.ohhddhhhhhhhHddHHHHHHHHHHHHHHHHHHHHHHHHHHHDDddDDDDDDDDo.
.odddhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDdddDDDDDDo.
oddhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDddDDDDDDo
ohhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDddDDDDo
ohhhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDDddDDDo
hhhhhhhhhhddhHHHHHHHHHHHHHHHHHHHHHHHHHHHdHHDDDDDDDDDDddDD
`),
};

/** bob: hat shadow. */
export const HAIR_BOB_HAT_SHADOW: PixMap = {
  anchor: [28, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
.oDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDo.
oHDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdddDo
oHDDDHHDDDDDDdDDdHHDDDDDDddDDDdDDDDDDDDDdddDDDDDddddddDo
`),
};

/** buns: back. */
export const HAIR_BUNS_BACK: PixMap = {
  anchor: [38, 23],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
.......h...........................................................H.......
....hhhhhHH.....................................................HHHHHDD....
..oddhhhdHHHdHH..............................................HHddHHHdDDDo..
.ohhhhhHHddHHd...............................................dHHHHHDDddDDo.
.ohhhddHHHdHHd...............................................HHHHddDDDdDDo.
ohhddHHHdHHdHHd..sssssssSSSSSSSSSSSSS..SSSSSSSSSSSSSSkkkkkk.dHHddDDDdDDdDDo
ohdhHHHHHHHdHHd..sssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkkk.HHdHDDDDDDDdDDo
ohdHHdHHHHHdHDd..sssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkkk.HHdDDdDDDDDdDdo
ohdHHdHHHHdHDdD..sssssssSSSS.SSSSSS......SSSSSS.SSSSSkkkkkk.HHdDDdDDDDdDddo
oHdHHHHHHddDDdD..ss.ssssSSSS..SSSSS......SSSSS..SSSSSkkk.kk.HDdDDDDDDdddddo
oHdHHdHHHHDDdDD..ss.ssssSSS...SSSSS......SSSSS...SSSSkkk.kk.DDdDDdDDDDddddo
.odHHHdHHDDdDD...ss..sssSSS....SSS........SSS....SSSSkk..kk..DdDDDdDDddddo.
.oHdHHHddddDDD...s....ssSS.....SSS........SSS.....SSSk....k..DDdDDDddddddo.
..oodHHDDDDDD....s....ssSS......S..........S......SSSk....k...DDdDDddddoo..
....oooDoDD............sS..........................SS...........Ddddooo....
.......o...........................................................o.......
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
................DDD......................................DDD...............
................D..........................................D...............
................DD........................................DD...............
................DDd......................................DDD...............
................DdDD....................................DDDd...............
................DdDD....................................DDDd...............
................DdDD....................................DDDd...............
................oDDD....................................DDdo...............
................oDDDD..................................DDDdo...............
................oDDDDD................................DDDDdo...............
................oDDDDDd..............................DDDDdDo...............
................oDDDDDdD............................DDDDDdDo...............
................oDDDDDdDD..........................DDDDDDdDo...............
................oDDDDdDDDDD......................dDDDDDDdDDo...............
................oDDDDdDDDDDDd..................DDdDDDDDDdDDo...............
................oDDDDdDDDDDDdDD..............DDDDdDDDDDDdDDo...............
................oDDDdDDDDDDdDDDDDD........DDDDDDdDDDDDDdDDDo...............
................oDDDooDDDDDdDooD............DDDooDDDDDDdooDo...............
................oDDo..oDDDDdo..o............DDo..oDDDDDo..oo...............
................oDo....oDDdo................Do....oDDDo....o...............
................oDo.....oDdo................Do.....oDo.....................
................oo.......oo.................o.......oo.....................
`),
};

/** buns: front. */
export const HAIR_BUNS_FRONT: PixMap = {
  anchor: [31, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
...hhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDHH...
...hhHHHhhHHHHHHdHHdhhHHHHHHDdHHHdHHHHHHHHHDDdHHHHHDDdDDDHH...
...hhHHHhhHHHHHHdHHdhhHHHHHHDdHHHdHHHHHHHHHDDdHHHHHDDdDDDHH...
...hhHHHhhHHHHHDdHHdhhHHHHHHDdHHHdHHHHHHHHHDDdHHHHHDDdDDDHH...
...hhHHHhhHHHHHDdHHdhhHHHHHHDdHHHdHHHHHHHHHDDkHHHHHDDdDDDHH...
...hhHHHhhHHHHHDdHDdhhHHHHHHDDkHHHdHHHHHHHDDD.kHHHHDDdDDDHH...
...hhHHHDhHHHHDDkkDdhhHHHHHHDD.HHHdHHHHHHHDDD..HHHDDddDDDHH...
...hhHHHDHHHHHDD..HkhhHHHHHDDD.kHHdHHHHHHHDDk..kHHDDddDDDHH...
...hhHHHDHHHDDDk..H.khhHHHHDDk..kHHHHHHHHDDk....kHDDddDDDHH...
...hhHHHDHHHDDk...k..HHHHHHDD....kHHHHHHDDD......kHkddDDDHH...
..hhHHHHDHHDDk.......HHHHDDDk.....kDHHHDDDk.......k.ddDDDDHH..
..hhHHHHDHHDk........kHHHDDD.......HHHHDDk..........ddDDDDHH..
..ohHHHHDDDD..........HHHDDk.......kHHHDD...........ddDDDDHH..
.ohhHHHHDDDk..........HHHDD.........kHDDk...........ddDDDDHHo.
.ohhHHHHDDk...........kHDDk..........HDk............ddDDDDHHo.
.ohhHHHHDD.............HDk...........Hk.............ddDDDDHHo.
.ohhHHHHDD.............kD............k..............ddDDDDHHo.
ohhdHHHHDD..............k...........................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhhdHHHHDDD......................................dddDDDDdHHHo
ohhdHHHHDD..........................................ddDDDDdHHo
ohhHHHHHDDD........................................dddDDDDDHHo
ohhhdHHHHDDD......................................dddDDDDdHHHo
.ohhHHHHHDDD......................................dddDDDDDHHo.
.ohhHHHHdDDD......................................ddddDDDDHHo.
..ohoHHHoDD........................................ddoDDDoHo..
..oo.oHo.oD........................................do.oDo.oo..
..oo.oHo.oD........................................do.oDo.oo..
..o..oo..o..........................................o..oo..o..
..o..oo..o..........................................o..oo..o..
.....oo................................................oo.....
......o................................................o......
`),
};

/** buns: crown. */
export const HAIR_BUNS_CROWN: PixMap = {
  anchor: [29, 39],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
......................ooooooooooooo......................
..................ooooHHHdHHHHHHHHHoooo..................
...............oooHHHdddddddddHHHHHHHHHooo...............
.............ooHHdddddddddddddd+ddHHHHHHHHoo.............
...........oodddddHHH+dddHddddHHHdddddHHHHHDoo...........
.........oodddHHHHHddHdddHdddHddHHHHHdddddHDDDoo.........
........odhhhHHHHHddHddhhhhhhhhhhhHHHHHHHddddDDDo........
.......ohhhhhH+HddHhhhhhhhhhhhhhhhhhhhHHHHHDDddddo.......
......ohhhhhhHHddhhhhhhhhhHdHHdhhhhhhhhhHHHDDDDDddo......
.....ohhhhhhhddhhhhhhhddHHHddHHdHHHhhhhhhhHDDDDDDDDo.....
....ohhhhhhdddhhhhhdHHdHHHHHdHHddHHHHdhhhhhDDDDDDDDDo....
...ohhhhhhddhhhhhddHHHdHHHHHdHHHddHHHHHdhhHDDDDDDDDDDo...
..ohhhhhdddhhhhhHdHHHddHHHHHddHHHdHHHHHHdddDDDDDDDDDDDo..
..ohhhhddhhhhhhHdHHHHdHHHHHHHHHHHHdHHHHHHHddDDDDDDDDDDo..
.ohhhdddhhhhhHHddHHHHHHHHHHHHHHHHHHHHHHHHHHdddDDDDDDDDDo.
.ohhddhhhhhhhHddHHHHHHHHHHHHHHHHHHHHHHHHHHHDDddDDDDDDDDo.
.odddhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDdddDDDDDDo.
oddhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDddDDDDDDo
dhhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDddDDDDD
hhhhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDDddDDDD
hhhhhhhhhhddhHHHHHHHHHHHHHHHHHHHHHHHHHHHdHHDDDDDDDDDDddDD
`),
};

/** buns: hat shadow. */
export const HAIR_BUNS_HAT_SHADOW: PixMap = {
  anchor: [37, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
.oddHHHdDDDdDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDddDDDddddo.
oHHHHHDDdHHDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdddDDDddddddo
oHHHddDDDHHDDDHHDDDDDDdDDdHHDDDDDDddDDDdDDDDDDDDDdddDDDDDddddddDDdddddddo
`),
};

/** mohawk: back. */
export const HAIR_MOHAWK_BACK: PixMap = {
  anchor: [22, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
KSSSSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSkkkkkK
KSSSSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSkkkkkK
.sSSSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSkkkkkk
.sssssssSSSSSSSSSSSSS..SSSSSSSSSSSSSSkkkkkk
.sssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkkk
.sssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkkk
.sssssssSSSS.SSSSSS......SSSSSS.SSSSSkkkkkk
.ss.ssssSSSS..SSSSS......SSSSS..SSSSSkkk.kk
.ss.ssssSSS...SSSSS......SSSSS...SSSSkkk.kk
.ss..sssSSS....SSS........SSS....SSSSkk..kk
.s....ssSS.....SSS........SSS.....SSSk....k
.s....ssSS......S..........S......SSSk....k
.......sS..........................SS......
`),
};

/** mohawk: front. */
export const HAIR_MOHAWK_FRONT: PixMap = {
  anchor: [22, 19],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
oH........................................Do
.o........................................o.
.o........................................o.
`),
};

/** mohawk: crown. */
export const HAIR_MOHAWK_CROWN: PixMap = {
  anchor: [22, 60],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
.....................o.....................
.....................o.....................
.....................o.....................
.....................o.....................
.....................o.....................
.................o...o...o.................
.................o..oHo..o.................
.................o..oHo..o.................
.................oo.oHo.oo.................
.................oo.oHo.oo.................
................oho.oHo.oDo................
................oho.oHo.oDo................
................ohhodHHoDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhdHHHDDo................
................ohhhHHHHDDo................
.............KKKhhhhHHHHDDDKKK.............
...........KKSSShhhhHHHHDDDSSSKK...........
.........KKSSSSShhhhHHHHDDDSSSSkKK.........
.......KKssSSSSShhhhHHHHDDDSSSSkkkKK.......
......KssssSSSSShhhhHHHHDDDSSSSkkkkkK......
.....KsssssSSSSShhhhHHHHDDDSSSSkkkkkkK.....
....KssssssSSSSShhhhHHHHDDDSSSSkkkkkkkK....
...KsssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkK...
...KsssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkK...
..KssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkK..
.KsssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkK.
.KsssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkK.
.KsssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkK.
KssssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkkK
KssssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkkK
KssssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkkK
sssssssssssSSSSShhhhHHHHDDDSSSSkkkkkkkkkkkk
`),
};

/** mohawk: hat shadow. */
export const HAIR_MOHAWK_HAT_SHADOW: PixMap = {
  anchor: [22, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
KSSSSSSSSSSSSSSSDDDDDDDDDDDSSSSSSSSSSkkkkkK.
KSSSSSSSSSSSSSSSDDDDDDDDDDDSSSSSSSSSSkkkkkK.
oDSSSSSSSSSSSSSSDDDDDDDDDDDSSSSSSSSSSkkkkkdo
`),
};


/** Every hair style's four layers by the creator's names (back, front, crown with the hat off, the brim's shadow with it on). */
export interface HairMaps { back: PixMap; front: PixMap; crown: PixMap; hatShadow: PixMap }
export const HAIR_MAPS: Record<string, HairMaps> = {
  long: { back: HAIR_LONG_BACK, front: HAIR_LONG_FRONT, crown: HAIR_LONG_CROWN, hatShadow: HAIR_LONG_HAT_SHADOW },
  bob: { back: HAIR_BOB_BACK, front: HAIR_BOB_FRONT, crown: HAIR_BOB_CROWN, hatShadow: HAIR_BOB_HAT_SHADOW },
  buns: { back: HAIR_BUNS_BACK, front: HAIR_BUNS_FRONT, crown: HAIR_BUNS_CROWN, hatShadow: HAIR_BUNS_HAT_SHADOW },
  mohawk: { back: HAIR_MOHAWK_BACK, front: HAIR_MOHAWK_FRONT, crown: HAIR_MOHAWK_CROWN, hatShadow: HAIR_MOHAWK_HAT_SHADOW },
};
