// Long hair as hand-placed maps (art builder 1, round 2; docs/PORTRAIT-STYLE.md "Hair"): clumps, not strands. The fringe is six
// big pointed clumps, tips at different heights curving outwards, each lit on its left and shaded on its right, a deep line where
// two meet, skin in the V's between, and a 1 px shadow on her forehead under each. The side locks frame her face, run down over
// her shoulders and end in three points; the far one (her left, our right) is a tone darker. The back hair fills behind her jaw
// and neck. The crown (with her hat off) falls in clumps from a parting with a shine arc and three glints; with a hat on the
// brim's shadow darkens the top rows. All four anchored on the head's centre; drawn back (behind her head), then her face, then
// front; the crown before back when the hat's off, the shadow after front when it's on.

import { BASE, DEEP, LIGHT, MAT, SHADE } from "../palette";
import { OUTLINE, rows, type PixMap } from "./pixmap";

export const HAIR_LEGEND = {
  o: [MAT.HAIR, OUTLINE], d: [MAT.HAIR, DEEP], D: [MAT.HAIR, SHADE], H: [MAT.HAIR, BASE], h: [MAT.HAIR, LIGHT],
  "+": [MAT.WHITE, BASE], S: [MAT.SKIN, BASE], s: [MAT.SKIN, LIGHT], k: [MAT.SKIN, SHADE], K: [MAT.SKIN, OUTLINE],
} as const;

/** Behind her head: the hair's top under the brim and the back hair behind her jaw and neck. */
export const HAIR_LONG_BACK: PixMap = {
  anchor: [27, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
oHHH..............................................HHHo
......................................................
......................................................
......sssssssSSSSSSSSSSSSS..SSSSSSSSSSSSSSkkkkkk......
......sssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkkk......
......sssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkkk......
......sssssssSSSS.SSSSSS......SSSSSS.SSSSSkkkkkk......
......ss.ssssSSSS..SSSSS......SSSSS..SSSSSkkk.kk......
......ss.ssssSSS...SSSSS......SSSSS...SSSSkkk.kk......
......ss..sssSSS....SSS........SSS....SSSSkk..kk......
......s....ssSS.....SSS........SSS.....SSSk....k......
......s....ssSS......S..........S......SSSk....k......
............sS..........................SS............
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
.....DDD......................................DDD.....
.....D..........................................D.....
.....DD........................................DD.....
.....DDd......................................DDD.....
.....DdDD....................................DDDd.....
.....DdDD....................................DDDd.....
.....DdDD....................................DDDd.....
.....dDDD....................................DDdD.....
.....dDDDD..................................DDDdD.....
.....dDDDDD................................DDDDdD.....
.....DDDDDDd..............................DDDDdDD.....
.....DDDDDDdD............................DDDDDdDD.....
.....DDDDDDdDD..........................DDDDDDdDD.....
.....DDDDDdDDDDD......................dDDDDDDdDDD.....
.....DDDDDdDDDDDDd..................DDdDDDDDDdDDD.....
.....DDDDDdDDDDDDdDD..............DDDDdDDDDDDdDDD.....
.....DDDDdDDDDDDdDDDDDD........DDDDDDdDDDDDDdDDDD.....
.....DDDDdDDDDDDdDDDD............DDDDdDDDDDDdDDDD.....
.....DDDDdDDDDDDdDDDD............DDDDdDDDDDDdDDDD.....
.....DDDdDDDDDDdDDDDD............DDDdDDDDDDdDDDDD.....
.....DDDdDDDDDDdDDDDD............DDDdDDDDDDdDDDDD.....
.....DDDdooDDDDdDDooD............DDDooDDDDDdDoDDD.....
.....DDdo..oDDdDDo..o............DDo..oDDDdDo..DD.....
.....DDo....oDdDo................Do....oDDdo....D.....
.....DDo.....oooo................oo.....ooo...........
`),
};

/** Over her face: the six fringe clumps (with their shadow on her forehead) and the side locks down over her shoulders. */
export const HAIR_LONG_FRONT: PixMap = {
  anchor: [33, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
..........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..........
.....ohHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDHo.....
.....ohHHHhhHHHHHHdHHdhhHHHHHHDdHHHdHHHHHHHHHDDdHHHHHDDdDDDHo.....
.....ohHHHhhHHHHHHdHHdhhHHHHHHDdHHHdHHHHHHHHHDDdHHHHHDDdDDDHo.....
.....ohHHHhhHHHHHDdHHdhhHHHHHHDdHHHdHHHHHHHHHDDdHHHHHDDdDDDHo.....
.....ohHHHhhHHHHHDdHHdhhHHHHHHDdHHHdHHHHHHHHHDDkHHHHHDDdDDDHo.....
.....ohHHHhhHHHHHDdHDdhhHHHHHHDDkHHHdHHHHHHHDDD.kHHHHDDdDDDHo.....
.....ohHHHDhHHHHDDkkDdhhHHHHHHDD.HHHdHHHHHHHDDD..HHHDDddDDDHo.....
.....ohHHHDHHHHHDD..HkhhHHHHHDDD.kHHdHHHHHHHDDk..kHHDDddDDDHo.....
.....ohHHHDHHHDDDk..H.khhHHHHDDk..kHHHHHHHHDDk....kHDDddDDDHo.....
.....ohHHHDHHHDDk...k..HHHHHHDD....kHHHHHHDDD......kHkddDDDHo.....
....ohHHHHDHHDDk.......HHHHDDDk.....kDHHHDDDk.......k.ddDDDDHo....
....ohHHHHDHHDk........kHHHDDD.......HHHHDDk..........ddDDDDHo....
....ohHHHHDDDD..........HHHDDk.......kHHHDD...........ddDDDDHo....
...ohhHHHHDDDk..........HHHDD.........kHDDk...........ddDDDDHHo...
...ohhHHHHDDk...........kHDDk..........HDk............ddDDDDHHo...
...ohhHHHHDD.............HDk...........Hk.............ddDDDDHHo...
...ohhHHHHDD.............kD............k..............ddDDDDHHo...
..ohhdHHHHDD..............k...........................ddDDDDdHHo..
..ohhdHHHHDD..........................................ddDDDDdHHo..
..ohhdHHHHDD..........................................ddDDDDdHHo..
..ohhdHHHHDD..........................................ddDDDDdHHo..
..ohhdHHHHDD..........................................ddDDDDdHHo..
..ohhdHHHHDD..........................................ddDDDDdHHo..
..ohhdHHHHDD..........................................ddDDDDdHHo..
..ohhhdHHHHDDD......................................dddDDDDdHHHo..
..ohhdHHHHDD..........................................ddDDDDdHHo..
..ohhHHHHHDDD........................................dddDDDDDHHo..
..ohhhdHHHHDDD......................................dddDDDDdHHHo..
...ohhHHHHHDDD......................................dddDDDDDHHo...
...ohhHHHHdDDD......................................ddddDDDDHHo...
...ohhHHHHdDDD......................................ddddDDDDHHo...
...ohhHHHHdDDD......................................ddddDDDDHHo...
....ohhdHHdHDD......................................ddDdDDdHHo....
....ohhdHHdHDD......................................ddDdDDdHHo....
....ohhdHHdHDD......................................ddDdDDdHHo....
....ohhdHHdHDD......................................ddDdDDdHHo....
.....ohhHHHHDD......................................ddDDDDHHo.....
.....ohhHHHHDD......................................ddDDDDHHo.....
.....ohhHHHHDD......................................ddDDDDHHo.....
.....ohhHHHHDD......................................ddDDDDHHo.....
.....ohhHHHHDD......................................ddDDDDHHo.....
......ohHHHHDD......................................ddDDDDHo......
......ohHHHHDD......................................ddDDDDHo......
.....ohhHHHHDD......................................ddDDDDHHo.....
.....ohhHHHHDD......................................ddDDDDHHo.....
.....ohhHHHHDD......................................ddDDDDHHo.....
.....ohhHHHHDD......................................odDDDDHHo.....
.....ohhHHHHDo......................................odDDDDHHo.....
....ohhdHHdHDo......................................odDdDDdHHo....
....ohhdHHdHDo......................................odDdDDdHHo....
....ohhdHHdHDo......................................odDdDDdHHo....
...ohhHHHHdDDo......................................odddDDDDHHo...
...ohhHHHHdDDo......................................odddDDDDHHo...
...ohhHHHHdDDo......................................odddDDDDHHo...
...ohhdHHdHDo........................................odDdDDdHHo...
...ohhdHHdHDo........................................odDdDDdHHo...
..ohhHHHHdDDo........................................odddDDDDHHo..
..ohhHHHHdDDo........................................odddDDDDHHo..
..ohhHHHHdDDo........................................odddDDDDHHo..
..ohhHHHHdDDo........................................odddDDDDHHo..
.ohhhdHHoHDo..........................................odDoDDdHHHo.
ohhhdHHo.oDo..........................................odo.oDDdHHHo
.ohhdHHo.oo............................................oo.oDDdHHo.
.ohodHHo.o..............................................o.oDDdoHo.
.oo.oHHo.o..............................................o.oDDo.oo.
..o.oHHo..................................................oDDo.o..
.o..oHo....................................................oDo..o.
....oHo....................................................oDo....
.....o......................................................o.....
.....o......................................................o.....
.....o......................................................o.....
`),
};

/** The crown when her hat's off: clumps from the parting, a shine arc and its glints. */
export const HAIR_LONG_CROWN: PixMap = {
  anchor: [29, 39],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
......................ooooooooooooo......................
..................ooooHHHdHHHHHHHHHoooo..................
...............oooHHHdddddddddHHHHHHHHHooo...............
.............ooHHdddddddddddddd+ddHHHHHHHHoo.............
...........oodddddHHH+dddHddddHHHdddddHHHHHDoo...........
.........oodddHHHHHddHdddHdddHddHHHHHdddddHDDDoo.........
........odhhhHHHHHddHddhhhhhhhhhhhHHHHHHHddddDDDo........
.......ohhhhhH+HddHhhhhhhhhhhhhhhhhhhhHHHHHDDddddo.......
......ohhhhhhHHddhhhhhhhhhHdHHdhhhhhhhhhHHHDDDDDddo......
.....ohhhhhhhddhhhhhhhddHHHddHHdHHHhhhhhhhHDDDDDDDDo.....
....ohhhhhhdddhhhhhdHHdHHHHHdHHddHHHHdhhhhhDDDDDDDDDo....
...ohhhhhhddhhhhhddHHHdHHHHHdHHHddHHHHHdhhHDDDDDDDDDDo...
..ohhhhhdddhhhhhHdHHHddHHHHHddHHHdHHHHHHdddDDDDDDDDDDDo..
..ohhhhddhhhhhhHdHHHHdHHHHHHHHHHHHdHHHHHHHddDDDDDDDDDDo..
.ohhhdddhhhhhHHddHHHHHHHHHHHHHHHHHHHHHHHHHHdddDDDDDDDDDo.
.ohhddhhhhhhhHddHHHHHHHHHHHHHHHHHHHHHHHHHHHDDddDDDDDDDDo.
.odddhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDdddDDDDDDo.
oddhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDddDDDDDDo
ohhhhhhhhhhhdHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDddDDDDo
ohhhhhhhhhhddHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDDddDDDo
hhhhhhhhhhddhHHHHHHHHHHHHHHHHHHHHHHHHHHHdHHDDDDDDDDDDddDD
`),
};

/** The brim's shadow on her hair: its top rows a tone darker, drawn only with a hat on. */
export const HAIR_LONG_HAT_SHADOW: PixMap = {
  anchor: [28, 21],
  legend: HAIR_LEGEND,
  rows: rows(String.raw`
.oDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDo.
oHDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdddDo
oHDDDHHDDDDDDdDDdHHDDDDDDddDDDdDDDDDDDDDdddDDDDDddddddDo
`),
};

