// The other hair styles as hand-placed maps (art builder 1, round 2), drawn like the long hair (hairLong.ts) and in its four
// layers: the bob (locks to her jaw), the buns (a coiled knot each side of her head, short locks), and the mohawk (no fringe,
// her head shaved, the crest standing up along the middle: with her hat on, only her bare forehead shows under the brim).

import { HAIR_LONG_BACK, HAIR_LONG_CROWN, HAIR_LONG_FRONT, HAIR_LONG_HAT_SHADOW } from "./hairLong";
import { rows, type PixMap } from "./pixmap";

/** bob: back. */
export const HAIR_BOB_BACK: PixMap = {
  anchor: [27, 21],
  rows: rows(String.raw`
oHHH..............................................HHHo
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
.....ddd......................................ddd.....
.....d..........................................d.....
.....dd........................................dd.....
.....ddD......................................ddd.....
.....dDdd....................................dddD.....
.....dDdd....................................dddD.....
.....dDdd....................................dddD.....
.....Dddd....................................ddDd.....
.....Ddddd..................................dddDd.....
.....Dddddd................................ddddDd.....
.....ddddddD..............................ddddDdd.....
.....ddddddDd............................dddddDdd.....
.....odddddDdd..........................ddddddDdo.....
.....oddddDddddd......................DddddddDddo.....
.....oddddDddddddD..................ddDddddddDddo.....
.....oddddDddddddDdd..............ddddDddddddDddo.....
.....odddDddddddDdddddd........ddddddDddddddDdddo.....
.....odddDddddddDdddd............ddddDddddddDdddo.....
.....odddDddddddDdddd............ddddDddddddDdddo.....
.....oddDddddddDddddd............dddDddddddDddddo.....
.....oddDddddddDddddd............dddDddddddDddddo.....
.....oddDooddddDddood............dddoodddddDdoodo.....
.....odDo..oddDddo..o............ddo..odddDdo..oo.....
.....odo....odDdo................do....oddDo....o.....
.....ooo.....oooo................oo.....ooo...........
`),
};

/** bob: front. */
export const HAIR_BOB_FRONT: PixMap = {
  anchor: [29, 21],
  rows: rows(String.raw`
......HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH......
.ohHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddHo.
.ohHHHhhHHHHHDhHHHHHDhHHHHHDhHHHHHDhHHHHHDhhHHHHHddDdddHo.
.ohHHHhhHHHHHDhHHHHHDhHHHHHDhHHHHHDhhHHHHDhhHHHHHddDdddHo.
.ohHHHhhHHHHHDhHHHHHDhHHHHHDhHHHHHDhhHHHHdDhHHHHHddDdddHo.
.ohHHHhhHHHHdDhHHHHHDhhHHHdDhhHHHHDhhHHHHdDhhHHHHddDdddHo.
.ohHHHhhHHHHdDhHHHHHDhhHHHdDhhHHHHdDhHHHHddkhHHHHddDdddHo.
.ohHHHdhHHHHdDhHHHHdDHHHHHdDhhHHHHdDhhHHHdd.HHHHddDDdddHo.
.ohHHHdHHHHddkhhHHHddkHHHddkkhHHHHddkHHHddd.kHHHddDDdddHo.
.ohHHHdHHHddd.hhHHHdd.HHHdd..HHHHHdk.HHHddk..kHHddDDdddHo.
.ohHHHdHHHddk.HHHHHdk.kHddk..HHHddd..kHHdd....kHdkDDdddHo.
.ohHHHddHddk..kHHddd...Hdk...kHHddd...kHdd.....kH.DDdddHo.
.ohHHHddHdd....HHddd...kd.....HHddk....kdk......k.DDdddHo.
.ohHHHddHdk....HHddk....k.....kHdd......H.........DDdddHo.
.ohHHHddHk.....HHdd............Hdd......k.........DDdddHo.
.ohHHHddk......kHdk............kdk................DDdddHo.
.ohDHHdd........Hd..............H.................DDddDHo.
.ohDHHdd........Hk..............k.................DDddDHo.
.ohDHHdd........k.................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohhHHHHdd......................................DDddddHHo.
ohHHHHdd..........................................DDddddHo
ohhHHHHdd........................................DDddddHHo
ohhDHHHHdd......................................DDddddDHHo
ohhDHHHHdd......................................DDddddDHHo
ohhDHHDHdd......................................DDdDddDHHo
ohhDHHDHdd......................................DDdDddDHHo
ohhDHHDHdd......................................DDdDddDHHo
ohhDHHDHdd......................................DDdDddDHHo
ohhDHHDHdd......................................DDdDddDHHo
ohhDHHDHdd......................................DDdDddDHHo
ohhDHHoHdd......................................DDdoddDHHo
ohhDHo.od........................................Do.odDHHo
.ohDHo.od........................................Do.odDHo.
.ohoHo.od........................................Do.odoHo.
.oo.oo..............................................oo.oo.
....oo..............................................oo....
....oo..............................................oo....
`),
};

/** bob: crown. */
export const HAIR_BOB_CROWN: PixMap = {
  anchor: [29, 39],
  rows: rows(String.raw`
......................ooooooooooooo......................
..................ooooHHHDHHHHHHHHHoooo..................
...............oooHHHDDDDDDDDDHHHHHHHHHooo...............
.............ooHHDDDDDDDDDDDDDDgDDHHHHHHHHoo.............
...........ooDDDDDHHHgDDDHDDDDHHHDDDDDHHHHHdoo...........
.........ooDDDHHHHHDDHDDDHDDDHDDHHHHHDDDDDHdddoo.........
........oDhhhHHHHHDDHDDhhhhhhhhhhhHHHHHHHDDDDdddo........
.......ohhhhhHgHDDHhhhhhhhhhhhhhhhhhhhHHHHHddDDDDo.......
......ohhhhhhHHDDhhhhhhhhhHDHHDhhhhhhhhhHHHdddddDDo......
.....ohhhhhhhDDhhhhhhhDDHHHDDHHDHHHhhhhhhhHddddddddo.....
....ohhhhhhDDDhhhhhDHHDHHHHHDHHDDHHHHDhhhhhdddddddddo....
...ohhhhhhDDhhhhhDDHHHDHHHHHDHHHDDHHHHHDhhHddddddddddo...
..ohhhhhDDDhhhhhHDHHHDDHHHHHDDHHHDHHHHHHDDDdddddddddddo..
..ohhhhDDhhhhhhHDHHHHDHHHHHHHHHHHHDHHHHHHHDDddddddddddo..
.ohhhDDDhhhhhHHDDHHHHHHHHHHHHHHHHHHHHHHHHHHDDDdddddddddo.
.ohhDDhhhhhhhHDDHHHHHHHHHHHHHHHHHHHHHHHHHHHddDDddddddddo.
.oDDDhhhhhhhhDDHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddDDDddddddo.
oDDhhhhhhhhhhDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddddDDddddddo
ohhhhhhhhhhhDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddddddDDddddo
ohhhhhhhhhhDDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHddddddddDDdddo
hhhhhhhhhhDDhHHHHHHHHHHHHHHHHHHHHHHHHHHHDHHddddddddddDDdd
`),
};

/** bob: hat shadow. */
export const HAIR_BOB_HAT_SHADOW: PixMap = {
  anchor: [28, 21],
  rows: rows(String.raw`
.oddddddddddddddddddddddddddddddddddddddddddddddddddddo.
oHdddddddddddddddddddddddddddddddddddddddddddddddddDDDdo
oHdddHHdddddDHdddddDHdddddDHdddddDHdddddDHHdddddDDDDDDdo
`),
};

/** buns: back. */
export const HAIR_BUNS_BACK: PixMap = {
  anchor: [38, 23],
  rows: rows(String.raw`
.......h...........................................................H.......
....hhhhhHH.....................................................HHHHHdd....
..oDDhhhDHHHDHH..............................................HHDDHHHDdddo..
.ohhhhhHHDDHHD...............................................DHHHHHddDDddo.
.ohhhDDHHHDHHD...............................................HHHHDDdddDddo.
ohhDDHHHDHHDHHD.............................................DHHDDdddDddDddo
ohDhHHHHHHHDHHD.............................................HHDHdddddddDddo
ohDHHDHHHHHDHdD.............................................HHDddDdddddDdDo
ohDHHDHHHHDHdDd.............................................HHDddDddddDdDDo
oHDHHHHHHDDddDd.............................................HdDddddddDDDDDo
oHDHHDHHHHddDdd.............................................ddDddDddddDDDDo
.oDHHHDHHddDdd...............................................dDdddDddDDDDo.
.oHDHHHDDDDddd...............................................ddDdddDDDDDDo.
..ooDHHdddddd.................................................ddDddDDDDoo..
....ooodood.....................................................dDoDooo....
.......o...........................................................o.......
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
................ddd......................................ddd...............
................d..........................................d...............
................dd........................................dd...............
................ddD......................................ddd...............
................dDdd....................................dddD...............
................dDdd....................................dddD...............
................oDdd....................................dddo...............
................oddd....................................ddDo...............
................odddd..................................dddDo...............
................oddddd................................ddddDo...............
................odddddD..............................ddddDdo...............
................odddddDd............................dddddDdo...............
................odddddDdd..........................ddddddDdo...............
................oddddDddddd......................DddddddDddo...............
................oddddDddddddD..................ddDddddddDddo...............
................oddddDddddddDdd..............ddddDddddddDddo...............
................odddDddddddDdddddd........ddddddDddddddDdddo...............
................odddoodddddDdood............dddooddddddDoodo...............
................oddo..oddddDo..o............ddo..odddddo..oo...............
................odo....oddDo................do....odddo....o...............
................odo.....odDo................do.....odo.....................
................oo.......oo.................o.......oo.....................
`),
};

/** buns: front. */
export const HAIR_BUNS_FRONT: PixMap = {
  anchor: [29, 21],
  rows: rows(String.raw`
......HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH......
.hhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddHH.
.hhHHHhhHHHHHDhHHHHHDhHHHHHDhHHHHHDhHHHHHDhhHHHHHddDdddHH.
.hhHHHhhHHHHHDhHHHHHDhHHHHHDhHHHHHDhhHHHHDhhHHHHHddDdddHH.
.hhHHHhhHHHHHDhHHHHHDhHHHHHDhHHHHHDhhHHHHdDhHHHHHddDdddHH.
.hhHHHhhHHHHdDhHHHHHDhhHHHdDhhHHHHDhhHHHHdDhhHHHHddDdddHH.
.hhHHHhhHHHHdDhHHHHHDhhHHHdDhhHHHHdDhHHHHddkhHHHHddDdddHH.
.hhHHHdhHHHHdDhHHHHdDHHHHHdDhhHHHHdDhhHHHdd.HHHHddDDdddHH.
.hhHHHdHHHHddkhhHHHddkHHHddkkhHHHHddkHHHddd.kHHHddDDdddHH.
.hhHHHdHHHddd.hhHHHdd.HHHdd..HHHHHdk.HHHddk..kHHddDDdddHH.
.hhHHHdHHHddk.HHHHHdk.kHddk..HHHddd..kHHdd....kHdkDDdddHH.
.hhHHHddHddk..kHHddd...Hdk...kHHddd...kHdd.....kH.DDdddHH.
.hhHHHddHdd....HHddd...kd.....HHddk....kdk......k.DDdddHH.
.ohHHHddHdk....HHddk....k.....kHdd......H.........DDdddHo.
.ohHHHddHk.....HHdd............Hdd......k.........DDdddHo.
.ohHHHddk......kHdk............kdk................DDdddHo.
.ohDHHdd........Hd..............H.................DDddDHo.
.ohDHHdd........Hk..............k.................DDddDHo.
.ohDHHdd........k.................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohDHHdd..........................................DDddDHo.
.ohhHHHHdd......................................DDddddHHo.
ohHHHHdd..........................................DDddddHo
ohhHHHHdd........................................DDddddHHo
ohhDHHHHdd......................................DDddddDHHo
ohhDHHHHdd......................................DDddddDHHo
ohhDHHoHdd......................................DDdoddDHHo
.ohDHo.od........................................Do.odDHo.
.ohoHo.od........................................Do.odoHo.
.oo.oo.od........................................Do.oo.oo.
....oo..............................................oo....
....oo..............................................oo....
`),
};

/** buns: crown. */
export const HAIR_BUNS_CROWN: PixMap = {
  anchor: [29, 39],
  rows: rows(String.raw`
......................ooooooooooooo......................
..................ooooHHHDHHHHHHHHHoooo..................
...............oooHHHDDDDDDDDDHHHHHHHHHooo...............
.............ooHHDDDDDDDDDDDDDDgDDHHHHHHHHoo.............
...........ooDDDDDHHHgDDDHDDDDHHHDDDDDHHHHHdoo...........
.........ooDDDHHHHHDDHDDDHDDDHDDHHHHHDDDDDHdddoo.........
........oDhhhHHHHHDDHDDhhhhhhhhhhhHHHHHHHDDDDdddo........
.......ohhhhhHgHDDHhhhhhhhhhhhhhhhhhhhHHHHHddDDDDo.......
......ohhhhhhHHDDhhhhhhhhhHDHHDhhhhhhhhhHHHdddddDDo......
.....ohhhhhhhDDhhhhhhhDDHHHDDHHDHHHhhhhhhhHddddddddo.....
....ohhhhhhDDDhhhhhDHHDHHHHHDHHDDHHHHDhhhhhdddddddddo....
...ohhhhhhDDhhhhhDDHHHDHHHHHDHHHDDHHHHHDhhHddddddddddo...
..ohhhhhDDDhhhhhHDHHHDDHHHHHDDHHHDHHHHHHDDDdddddddddddo..
..ohhhhDDhhhhhhHDHHHHDHHHHHHHHHHHHDHHHHHHHDDddddddddddo..
.ohhhDDDhhhhhHHDDHHHHHHHHHHHHHHHHHHHHHHHHHHDDDdddddddddo.
.ohhDDhhhhhhhHDDHHHHHHHHHHHHHHHHHHHHHHHHHHHddDDddddddddo.
.oDDDhhhhhhhhDDHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddDDDddddddo.
oDDhhhhhhhhhhDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddddDDddddddo
DhhhhhhhhhhhDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddddddDDddddd
hhhhhhhhhhhDDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHddddddddDDdddd
hhhhhhhhhhDDhHHHHHHHHHHHHHHHHHHHHHHHHHHHDHHddddddddddDDdd
`),
};

/** buns: hat shadow. */
export const HAIR_BUNS_HAT_SHADOW: PixMap = {
  anchor: [37, 21],
  rows: rows(String.raw`
.oDDHHHDdddDddddddddddddddddddddddddddddddddddddddddddddddddddDDdddDDDDo.
oHHHHHddDHHdddddddddddddddddddddddddddddddddddddddddddddddddDDDdddDDDDDDo
oHHHDDdddHHdddHHdddddDHdddddDHdddddDHdddddDHdddddDHHdddddDDDDDDddDDDDDDDo
`),
};

/** mohawk: back. */
export const HAIR_MOHAWK_BACK: PixMap = {
  anchor: [22, 21],
  rows: rows(String.raw`
KSSSSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSkkkkkK
KSSSSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSkkkkkK
..SSSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSkkkkk.
..ssssssSSSSSSSSSSSSS..SSSSSSSSSSSSSSkkkkk.
..ssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkk.
..ssssssSSSSSSSSSSSS....SSSSSSSSSSSSSkkkkk.
..ssssssSSSS.SSSSSS......SSSSSS.SSSSSkkkkk.
..s.ssssSSSS..SSSSS......SSSSS..SSSSSkkk.k.
..s.ssssSSS...SSSSS......SSSSS...SSSSkkk.k.
..s..sssSSS....SSS........SSS....SSSSkk..k.
......ssSS.....SSS........SSS.....SSSk.....
......ssSS......S..........S......SSSk.....
.......sS..........................SS......
`),
};

/** mohawk: front. */
export const HAIR_MOHAWK_FRONT: PixMap = {
  anchor: [22, 19],
  rows: rows(String.raw`
oH........................................do
oH........................................do
oH........................................do
oH........................................do
oH........................................do
oH........................................do
oH........................................do
oH........................................do
oH........................................do
oH........................................do
oH........................................do
.o........................................o.
.o........................................o.
`),
};

/** mohawk: crown. */
export const HAIR_MOHAWK_CROWN: PixMap = {
  anchor: [22, 60],
  rows: rows(String.raw`
.....................o.....................
.....................o.....................
.....................o.....................
.....................o.....................
.....................o.....................
.................o...o...o.................
.................o..oHo..o.................
.................o..oHo..o.................
.................oo.oHo.oo.................
.................oo.oHo.oo.................
................oho.oHo.odo................
................oho.oHo.odo................
................ohhoDHHoddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhDHHHddo................
................ohhhHHHHddo................
.............KKKhhhhHHHHdddKKK.............
...........KKSSShhhhHHHHdddSSSKK...........
.........KKSSSSShhhhHHHHdddSSSSkKK.........
.......KKssSSSSShhhhHHHHdddSSSSkkkKK.......
......KssssSSSSShhhhHHHHdddSSSSkkkkkK......
.....KsssssSSSSShhhhHHHHdddSSSSkkkkkkK.....
....KssssssSSSSShhhhHHHHdddSSSSkkkkkkkK....
...KsssssssSSSSShhhhHHHHdddSSSSkkkkkkkkK...
...KsssssssSSSSShhhhHHHHdddSSSSkkkkkkkkK...
..KssssssssSSSSShhhhHHHHdddSSSSkkkkkkkkkK..
.KsssssssssSSSSShhhhHHHHdddSSSSkkkkkkkkkkK.
.KsssssssssSSSSShhhhHHHHdddSSSSkkkkkkkkkkK.
.KsssssssssSSSSShhhhHHHHdddSSSSkkkkkkkkkkK.
KssssssssssSSSSShhhhHHHHdddSSSSkkkkkkkkkkkK
KssssssssssSSSSShhhhHHHHdddSSSSkkkkkkkkkkkK
KssssssssssSSSSShhhhHHHHdddSSSSkkkkkkkkkkkK
sssssssssssSSSSShhhhHHHHdddSSSSkkkkkkkkkkkk
`),
};

/** mohawk: hat shadow. */
export const HAIR_MOHAWK_HAT_SHADOW: PixMap = {
  anchor: [22, 21],
  rows: rows(String.raw`
KSSSSSSSSSSSSSSSdddddddddddSSSSSSSSSSkkkkkK.
KSSSSSSSSSSSSSSSdddddddddddSSSSSSSSSSkkkkkK.
odSSSSSSSSSSSSSSdddddddddddSSSSSSSSSSkkkkkDo
`),
};


/** Every hair style's four layers by the creator's names (back, front, crown with the hat off, the brim's shadow with it on). */
export interface HairMaps { back: PixMap; front: PixMap; crown: PixMap; hatShadow: PixMap }
export const HAIR_MAPS: Record<string, HairMaps> = {
  long: { back: HAIR_LONG_BACK, front: HAIR_LONG_FRONT, crown: HAIR_LONG_CROWN, hatShadow: HAIR_LONG_HAT_SHADOW },
  bob: { back: HAIR_BOB_BACK, front: HAIR_BOB_FRONT, crown: HAIR_BOB_CROWN, hatShadow: HAIR_BOB_HAT_SHADOW },
  buns: { back: HAIR_BUNS_BACK, front: HAIR_BUNS_FRONT, crown: HAIR_BUNS_CROWN, hatShadow: HAIR_BUNS_HAT_SHADOW },
  mohawk: { back: HAIR_MOHAWK_BACK, front: HAIR_MOHAWK_FRONT, crown: HAIR_MOHAWK_CROWN, hatShadow: HAIR_MOHAWK_HAT_SHADOW },
};
