// Long hair as hand-placed maps (art builder 1, round 2; docs/PORTRAIT-STYLE.md "Hair"): clumps, not strands. The fringe is six
// big pointed clumps, tips at different heights curving outwards, each lit on its left and shaded on its right, a deep line where
// two meet, skin in the V's between, and a 1 px shadow on her forehead under each. The side locks frame her face, run down over
// her shoulders and end in three points; the far one (her left, our right) is a tone darker. The back hair fills behind her jaw
// and neck. The crown (with her hat off) falls in clumps from a parting with a shine arc and three glints; with a hat on the
// brim's shadow darkens the top rows. All four anchored on the head's centre; drawn back (behind her head), then her face, then
// front; the crown before back when the hat's off, the shadow after front when it's on.

import { rows, type PixMap } from "./pixmap";

/** Behind her head: the hair's top under the brim and the back hair behind her jaw and neck. */
export const HAIR_LONG_BACK: PixMap = {
  anchor: [27, 21],
  rows: rows(String.raw`
oHHH..............................................HHHo
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
.....ddd......................................ddd.....
.....d..........................................d.....
.....dd........................................dd.....
.....ddD......................................ddd.....
.....dDdd....................................dddD.....
.....dDdd....................................dddD.....
.....dDdd....................................dddD.....
.....Dddd....................................ddDd.....
.....Ddddd..................................dddDd.....
.....Dddddd................................ddddDd.....
.....ddddddD..............................ddddDdd.....
.....ddddddDd............................dddddDdd.....
.....ddddddDdd..........................ddddddDdd.....
.....dddddDddddd......................DddddddDddd.....
.....dddddDddddddD..................ddDddddddDddd.....
.....dddddDddddddDdd..............ddddDddddddDddd.....
.....ddddDddddddDdddddd........ddddddDddddddDdddd.....
.....ddddDddddddDdddd............ddddDddddddDdddd.....
.....ddddDddddddDdddd............ddddDddddddDdddd.....
.....dddDddddddDddddd............dddDddddddDddddd.....
.....dddDddddddDddddd............dddDddddddDddddd.....
.....dddDooddddDddood............dddoodddddDdoddd.....
.....ddDo..oddDddo..o............ddo..odddDdo..dd.....
.....ddo....odDdo................do....oddDo....d.....
.....ddo.....oooo................oo.....ooo...........
`),
};

/** Over her face: the six fringe clumps (with their shadow on her forehead) and the side locks down over her shoulders. */
export const HAIR_LONG_FRONT: PixMap = {
  anchor: [31, 21],
  rows: rows(String.raw`
........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
...ohHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddHo...
...ohHHHhhHHHHHDhHHHHHDhHHHHHDhHHHHHDhHHHHHDhhHHHHHddDdddHo...
...ohHHHhhHHHHHDhHHHHHDhHHHHHDhHHHHHDhhHHHHDhhHHHHHddDdddHo...
...ohHHHhhHHHHHDhHHHHHDhHHHHHDhHHHHHDhhHHHHdDhHHHHHddDdddHo...
...ohHHHhhHHHHdDhHHHHHDhhHHHdDhhHHHHDhhHHHHdDhhHHHHddDdddHo...
...ohHHHhhHHHHdDhHHHHHDhhHHHdDhhHHHHdDhHHHHddkhHHHHddDdddHo...
...ohHHHdhHHHHdDhHHHHdDHHHHHdDhhHHHHdDhhHHHdd.HHHHddDDdddHo...
...ohHHHdHHHHddkhhHHHddkHHHddkkhHHHHddkHHHddd.kHHHddDDdddHo...
...ohHHHdHHHddd.hhHHHdd.HHHdd..HHHHHdk.HHHddk..kHHddDDdddHo...
...ohHHHdHHHddk.HHHHHdk.kHddk..HHHddd..kHHdd....kHdkDDdddHo...
...ohHHHddHddk..kHHddd...Hdk...kHHddd...kHdd.....kH.DDdddHo...
...ohHHHddHdd....HHddd...kd.....HHddk....kdk......k.DDdddHo...
...ohHHHddHdk....HHddk....k.....kHdd......H.........DDdddHo...
...ohHHHddHk.....HHdd............Hdd......k.........DDdddHo...
...ohHHHddk......kHdk............kdk................DDdddHo...
...ohDHHdd........Hd..............H.................DDddDHo...
...ohDHHdd........Hk..............k.................DDddDHo...
...ohDHHdd........k.................................DDddDHo...
...ohDHHdd..........................................DDddDHo...
...ohDHHdd..........................................DDddDHo...
...ohDHHdd..........................................DDddDHo...
...ohDHHdd..........................................DDddDHo...
...ohDHHdd..........................................DDddDHo...
...ohDHHdd..........................................DDddDHo...
...ohhHHHHdd......................................DDddddHHo...
..ohHHHHdd..........................................DDddddHo..
..ohhHHHHdd........................................DDddddHHo..
..ohhDHHHHdd......................................DDddddDHHo..
..ohhDHHHHdd......................................DDddddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
..ohhDHHDHdd......................................DDdDddDHHo..
.ohhHHHHDddd......................................DDDDddddHHo.
.ohhHHHHDddd......................................DDDDddddHHo.
.ohhHHHHDddd......................................DDDDddddHHo.
.ohhHHHHDddd......................................oDDDddddHHo.
.ohhHHHHDddo......................................oDDDddddHHo.
.ohhHHHHDddo......................................oDDDddddHHo.
.ohhHHHHDddo......................................oDDDddddHHo.
.ohhHHHHDddo......................................oDDDddddHHo.
.ohhHHHHDddo......................................oDDDddddHHo.
.ohhHHHHDddo......................................oDDDddddHHo.
.ohhHHHHDddo......................................oDDDddddHHo.
.ohhDHHDHdo........................................oDdDddDHHo.
.ohhDHHDHdo........................................oDdDddDHHo.
ohhHHHHDddo........................................oDDDddddHHo
ohhHHHHDddo........................................oDDDddddHHo
ohhHHHHDddo........................................oDDDddddHHo
ohhHHHHDddo........................................oDDDddddHHo
ohhHHHHodo..........................................oDoddddHHo
ohhHHHo.oo..........................................oo.odddHHo
.ohDHo.oo............................................oo.odDHo.
.ohDHo..................................................odDHo.
.ooDHo..................................................odDoo.
...oHo..................................................odo...
...oHo..................................................odo...
...oHo..................................................odo...
....o....................................................o....
....o....................................................o....
....o....................................................o....
`),
};

/** The crown when her hat's off: clumps from the parting, a shine arc and its glints. */
export const HAIR_LONG_CROWN: PixMap = {
  anchor: [29, 39],
  rows: rows(String.raw`
......................ooooooooooooo......................
..................ooooHHHDHHHHHHHHHoooo..................
...............oooHHHDDDDDDDDDHHHHHHHHHooo...............
.............ooHHDDDDDDDDDDDDDDgDDHHHHHHHHoo.............
...........ooDDDDDHHHgDDDHDDDDHHHDDDDDHHHHHdoo...........
.........ooDDDHHHHHDDHDDDHDDDHDDHHHHHDDDDDHdddoo.........
........oDhhhHHHHHDDHDDhhhhhhhhhhhHHHHHHHDDDDdddo........
.......ohhhhhHgHDDHhhhhhhhhhhhhhhhhhhhHHHHHddDDDDo.......
......ohhhhhhHHDDhhhhhhhhhHDHHDhhhhhhhhhHHHdddddDDo......
.....ohhhhhhhDDhhhhhhhDDHHHDDHHDHHHhhhhhhhHddddddddo.....
....ohhhhhhDDDhhhhhDHHDHHHHHDHHDDHHHHDhhhhhdddddddddo....
...ohhhhhhDDhhhhhDDHHHDHHHHHDHHHDDHHHHHDhhHddddddddddo...
..ohhhhhDDDhhhhhHDHHHDDHHHHHDDHHHDHHHHHHDDDdddddddddddo..
..ohhhhDDhhhhhhHDHHHHDHHHHHHHHHHHHDHHHHHHHDDddddddddddo..
.ohhhDDDhhhhhHHDDHHHHHHHHHHHHHHHHHHHHHHHHHHDDDdddddddddo.
.ohhDDhhhhhhhHDDHHHHHHHHHHHHHHHHHHHHHHHHHHHddDDddddddddo.
.oDDDhhhhhhhhDDHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddDDDddddddo.
oDDhhhhhhhhhhDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddddDDddddddo
ohhhhhhhhhhhDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHdddddddDDddddo
ohhhhhhhhhhDDHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHddddddddDDdddo
hhhhhhhhhhDDhHHHHHHHHHHHHHHHHHHHHHHHHHHHDHHddddddddddDDdd
`),
};

/** The brim's shadow on her hair: its top rows a tone darker, drawn only with a hat on. */
export const HAIR_LONG_HAT_SHADOW: PixMap = {
  anchor: [28, 21],
  rows: rows(String.raw`
.oddddddddddddddddddddddddddddddddddddddddddddddddddddo.
oHdddddddddddddddddddddddddddddddddddddddddddddddddDDDdo
oHdddHHdddddDHdddddDHdddddDHdddddDHdddddDHHdddddDDDDDDdo
`),
};

