// The classic witch's hat as a hand-placed map (art builder 1, round 2; from the round-1 target, docs/PORTRAIT-STYLE.md "Hat
// (classic)"): a tall cone bending at its tip with one crease, a red band (light top row, deep bottom row) with a gold buckle and
// its dark hole, a brim about 80 px across (base and light on top, a shade and deep near edge), outlined in the hat's own dark
// blue-violet, its stepped ends anti-aliased by hand. The creator's sliders (classicHat): height adds or drops the cone's middle
// rows, brim repeats the brim's middle columns between its drawn ends, tilt shears the cone by whole pixels.

import { BASE, DEEP, LIGHT, MAT, SHADE } from "../palette";
import { OUTLINE, rows, shear, stretchCols, stretchRows, type PixMap } from "./pixmap";
import type { Look } from "../rig";

export const HAT_LEGEND = {
  O: [MAT.HAT, OUTLINE], l: [MAT.HAT, LIGHT], p: [MAT.HAT, BASE], q: [MAT.HAT, SHADE], Q: [MAT.HAT, DEEP],
  e: [MAT.BAND, LIGHT], r: [MAT.BAND, BASE], f: [MAT.BAND, DEEP], Y: [MAT.GOLD, BASE], y: [MAT.GOLD, SHADE], G: [MAT.GOLD, LIGHT],
} as const;

/** The classic witch's hat, as drawn (sliders at 1, 1, 0): its anchor the brim's centre. */
export const HAT_CLASSIC: PixMap = {
  anchor: [41, 44],
  legend: HAT_LEGEND,
  rows: rows(String.raw`
.................................................OO...............................
................................................OlqO..............................
...............................................OlpqO..............................
..............................................OlppqO..............................
.............................................OllppqO..............................
............................................OllpppqO..............................
...........................................OllppppqO..............................
..........................................OlllpppqqqO.............................
..........................................OllppppqqqO.............................
.........................................OlllppppqqqO.............................
........................................OlllpppppqqqO.............................
.......................................OllllpppppqqqO.............................
......................................OllllppppppqqqO.............................
......................................OllllpppqppqqqO.............................
.....................................OllllppppqpqqqqqO............................
....................................OlllllppppqpqqqqqO............................
...................................OlllllppppqppqqqqqO............................
...................................OlllllppppqppqqqqqO............................
..................................OlllllpppppqppqqqqqO............................
.................................OllllllppppppqpqqqqqO............................
.................................OllllllpppppqppqqqqqqO...........................
................................OllllllpppppqpppqqqqqqO...........................
...............................OlllllllpppppqpppqqqqqqO...........................
...............................OlllllllpppppqpppqqqqqqO...........................
..............................OlllllllppppppqpppqqqqqqO...........................
..............................OlllllllppppppqpppqqqqqqqO..........................
.............................OlllllllppppppppqppqqqqqqqO..........................
.............................OlllllllpppppppqpppqqqqqqqO..........................
............................OllllllllpppppppqpppqqqqqqqO..........................
...........................OlllllllllpppppppqpppqqqqqqqqO.........................
...........................OllllllllpppppppqppppqqqqqqqqO.........................
..........................OlllllllllpppppppqppppqqqqqqqqO.........................
..........................OlllllllllpppppppqppppqqqqqqqqO.........................
.........................OlllllllllpppppppppqpppqqqqqqqqqO........................
.........................OlllllllllppppppppqppppqqqqqqqqqO........................
........................OllllllllllppppppppqppppqqqqqqqqqO........................
........................OllllllllllppppppppqpppppqqqqqqqqqO.......................
........................OllllllllllppppppppppppppqqqqqqqqqO.......................
.......................OeeeeeeeeeeeeeeGYYYYyeeeeeerrrrrrrrO.......................
....................OOOOeeeeeeeeeerrrrYffffyrrrrrrffffffffOOOO....................
............OOOOOOOOqppeeeeeeeeeeerrrrYffffyrrrrrrfffffffffppqOOOOOOOO............
.......OOOOOpllllllppppeeeeeeeeeeerrrrYffffyrrrrrrfffffffffppppppppppqOOOOO.......
....OOOplllllllllllppppeeeeeeeeeeerrrryyyyyyrrrrrrffffffffffppppppppppppppqOOO....
..OOpllllllllllllllpppffffffffffffffffffffffffffffffffffffffpppppppppppppppppqOO..
.OlllllllllllllllllppplllllllllllpppppppppppppppppqqqqqqqqqqppppppppppppppppppppO.
OllllllllllllllllllppllllllllllllpppppppppppppppppqqqqqqqqqqqppppppppppppppppppppO
OllllllllllllllllllppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppO
.OlllllllllllllllllpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppO.
..OOQqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQOO..
....OOOQqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQOOO....
.......OOOOOQqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQOOOOO.......
............OOOOOOOOQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQOOOOOOOO............
....................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO....................
`),
};

/** Where the sliders work, in HAT_CLASSIC's rows: the cone's middle rows, the band's top row, and the brim's middle columns
 *  each side (between its drawn end and the band). */
export const CLASSIC_SLIDERS = { cone: [8, 34], bandTop: 38, brimLeft: [11, 19], brimRight: [62, 70] } as const;

/** The classic hat with the creator's sliders: hatHeight (0.3 to 3: 18 rows a unit), hatBrim (0.3 to 2.6: 12 columns a unit
 *  each side) and hatTilt (-0.9 to 1: the tip moves about 7 px a unit, 1 px every 6 rows). Its anchor stays the brim's centre. */
export function classicHat(l: Pick<Look, "hatHeight" | "hatBrim" | "hatTilt">): PixMap {
  const S = CLASSIC_SLIDERS, [ax, ay] = HAT_CLASSIC.anchor;
  const extra = Math.max(-(S.cone[1] - S.cone[0]), Math.round((l.hatHeight - 1) * 18));
  let rs = stretchRows(HAT_CLASSIC.rows, S.cone[0], S.cone[1], S.cone[1] - S.cone[0] + 1 + extra);
  const k = Math.max(-(S.brimLeft[1] - S.brimLeft[0]), Math.round((l.hatBrim - 1) * 12));
  rs = stretchCols(rs, S.brimRight[0], S.brimRight[1], S.brimRight[1] - S.brimRight[0] + 1 + k); // (the right first: the left's columns stay put)
  rs = stretchCols(rs, S.brimLeft[0], S.brimLeft[1], S.brimLeft[1] - S.brimLeft[0] + 1 + k);
  const band = S.bandTop + extra, pad = 8;
  rs = shear(rs, band, y => Math.round((l.hatTilt * (band - y)) / 6), pad);
  return { anchor: [ax + k + pad, ay + extra], legend: HAT_LEGEND, rows: rs };
}
